### PR TITLE
fix(evm/anvil): recover BackedHandler performance

### LINKED ISSUE #1561: Anvil's CPU usage is suspiciously high when it's idle
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (85f69d9 2022-05-09T00:04:25.613861+00:00)

### What command(s) is the bug in?

anvil -f https://bsc-dataseed.binance.org

### Operating System

macOS (M1)

### Describe the bug

I used Anvil to fork BSC mainnet from latest block number. No problem when interacting with forked chain, everything was fine, Anvil ran very fast compared to Ganache. But I noticed that my M1 Macbook Air was getting warm when idle. After checking Activity Monitor, I saw that Anvil used 160% CPU when doing nothing.

### PR DESCRIPTION
**Pull request by univerz**
## Motivation

Solves [anvil hang](https://github.com/foundry-rs/foundry/pull/1037#discussion_r865694469) without performance cost. Closes #1561 

## Solution

not sure if it is best we can do, but this helps tokio to handle scheduling.

### CODE REVIEW

**Review by mattsse — CHANGES_REQUESTED** [review]
Thanks for looking into this

what I think probably might have happened is that the sync database functions are called from an asynchronous context (spawned task from within the axum rpc handler) and are blocking the executor which interferes with the other spawned task that drives the fork provider

`block_in_place`

> Runs the provided blocking function on the current thread without blocking the executor.

which is exactly what we want here.

lgtm, but would like a brief note about this

**Comment by univerz** [comment]
after a quick test, whether lifting `block_in_place` to `anvil::Backend` (`::call`) would not be faster (~no), it looks like we can can do exactly the opposite - make this simpler & move blocking down to `SharedBackend` - but i would like to test it more thoroughly.

**Comment by mattsse** [comment]
since this solution is definitely an improvement and solves #1565 
I used it here #1565 which supersedes this PR

should we keep this open until we've found a more appropriate solution or closing @univerz ?

**Comment by univerz** [comment]
> should we keep this open until we've found a more appropriate solution or closing @univerz ?

pls give me a few hours to test if i can move it to sharedbackend and we fix ti in one go - if looks like it even solves one of subtler spawn problems i experienced & is definitelly less error prone place to do it, but want to be sure that there is no cost in other scenarios.

> performance-wise from the sender pov, the difference is negligible to anvil/foundry's use case

i would expect this would even lead to perf improvement with more parallel use - how to setup this benchmark https://twitter.com/gakonst/status/1522282345440501760/photo/1 ?

**Comment by univerz** [comment]
perf ok, I'm glad how it turned out - it will save someone a lot of headaches :).

want to rebase your PR or push docs here?

**Review by mattsse — APPROVED** [review]
great, mind copy, paste, modifying my comments as you see fit?

thanks so much!

**Review by mattsse — APPROVED** [review]

**Pull request merged**
