### PR TITLE
invariant: #6694 add `preserve_state` config

### PR DESCRIPTION
**Pull request by grandizzy**
- add preserve_state invariant config: useful for handlers that change state (e.g. using cheatcodes like roll, warp), see #6694
- active only in conjunction with fail_on_revert true

## Motivation

- see https://github.com/foundry-rs/foundry/issues/6694#issuecomment-1961222360
## Solution
- use `call_raw_committing` if `preserve_state` and `fail_on_revert` enabled

### CODE REVIEW

**Comment by mds1** [comment]
See also #5444, so deferring to @Evalir on how this should be implemented.

Committing/preserving state is more intuitive and should be the default though—assuming the performance issue is resolved, what is the reason you'd want to disable it? It should also apply whether or not `fail_on_revert` is enabled

**Comment by grandizzy** [comment]
> See also #5444, so deferring to @Evalir on how this should be implemented.
> 
> Committing/preserving state is more intuitive and should be the default though—assuming the performance issue is resolved, what is the reason you'd want to disable it? It should also apply whether or not `fail_on_revert` is enabled

the only reason for disabling by default and applying with `fail_on_revert` is to avoid any potential performance issue for existing integrations, so projects could tweak these params, run with them and report back if something really bad. then after some time passed and feedback collected should be good to turn defaults on...

**Review by mattsse — APPROVED** [review]
I think that makes sense and a reasonable usecase

lgtm, pending @Evalir

**Comment by PaulRBerg** [comment]
Is this feature still implemented in the latest Foundry? I can't find any documentation for it on https://book.getfoundry.sh/

**Comment by grandizzy** [comment]
> Is this feature still implemented in the latest Foundry? I can't find any documentation for it on https://book.getfoundry.sh/

Yeah, that was made default behavior and config no longer needed / removed.

**Pull request merged**
