### PR TITLE
fix inline test config: enable ast for test

### LINKED ISSUE #7310: In-line test configuration not respected
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3df3e0c 2024-03-04T00:19:46.775990000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

`forge test` no longer respects [In-line test configuration](https://book.getfoundry.sh/reference/config/inline-test-config).

To replicate, simply `forge init` a new `Counter` project. Add an in-line fuzz runs config to `testFuzz_SetNumber`:
```Solidity
    /// forge-config: default.fuzz.runs = 100
    function testFuzz_SetNumber(uint256 x) public {
        counter.setNumber(x);
        assertEq(counter.number(), x);
    }
```
Run `forge test`. Output:
```
Ran 2 tests for test/Counter.t.sol:CounterTest
[PASS] testFuzz_SetNumber(uint256) (runs: 256, μ: 27787, ~: 28409)
[PASS] test_Increment() (gas: 28379)
Suite result: ok. 2 passed; 0 failed; 0 skipped; finished in 8.41ms (8.13ms CPU time)
```

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
Closes #7310

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
I think we need this

pending @DaniPopes

**Comment by grandizzy** [comment]
pending some test fixes

**Comment by DaniPopes** [comment]
I thought it never worked, we don't have any tests for inline config.
In any case, I don't want to enable this for all tests since this defeats the purpose of https://github.com/foundry-rs/foundry/pull/7197. I would much rather refactor inline config parsing to not use Solc AST.

**Comment by shuhuiluo** [comment]
> I thought it never worked, we don't have any tests for inline config. In any case, I don't want to enable this for all tests since this defeats the purpose of #7197. I would much rather refactor inline config parsing to not use Solc AST.

Hope you bring it back soon. The use case for me is to limit the runs for fork fuzzing tests which are rate limited while going crazy on local fuzzing runs.

**Comment by grandizzy** [comment]
> I thought it never worked, we don't have any tests for inline config. In any case, I don't want to enable this for all tests since this defeats the purpose of #7197. I would much rather refactor inline config parsing to not use Solc AST.

There are actually couple of tests but seems they are run with ast on https://github.com/foundry-rs/foundry/blob/master/crates/forge/tests/it/inline.rs

**Comment by DaniPopes** [comment]
> Hope you bring it back soon. The use case for me is to limit the runs for fork fuzzing tests which are rate limited while going crazy on local fuzzing runs.

Understandable, I will look into this today, thanks for flagging

**Comment by DaniPopes** [comment]
Opened https://github.com/foundry-rs/foundry/pull/7431

**Pull request closed without merging**
