### PR TITLE
feat: track ignored tests

### LINKED ISSUE #1123: Function Modifier or an Opcode to mark a test as skipped conditionally
### Component

Forge

### Describe the feature you would like

It would be nice to have a Forge provided modifier that lets one mark a test as skipped `[SKIP]` depending on some custom condition. The specific use case we need it for is to mark which tests are run on different mainnet forks

The code that we currently use looks like this (below) but it marks the skipped tests as passed `[PASS]` 

```
  uint256 BSC_MAINNET = 56;
  uint256 ETH_KOVAN = 42;
  uint256 ETH_RINKEBY = 4;
  uint256 EVMOS_TESTNET = 9000;

  /// custom modifier for running tests conditionally
  modifier shouldRun(bool run) {
    if (run) {
      _;
    }
  }

 // filter function for a specific chain
  function forChains(uint256 id0) public view returns (bool) {
    return block.chainid == id0;
  }

 // filter function for multiple chains
  function forChains(uint256 id0, uint256 id1) public view returns (bool) {
    return block.chainid == id0 || block.chainid == id1;
  }


  // TEST CASES


  function testSomething() public {
    // this test will be run on all chains
  }
 
  function testSomethingElse() public shouldRun(forChains(BSC, ETH_KOVAN)) {
    // this test will be skipped on EVMOS_TESTNET and ETH_RINKEBY
  }
```

I would imagine that we're provided by the forge env either a modifier like `shouldRun(forChains(...))` or some assembly opcode to return from the test marking it as skipped `[SKIP]` and then we can craft the modifier in the same way

```
  modifier shouldRun(bool run) {
    if (run) {
      _;
    }
    else {
      assembly {
        some_op_code_to_mark_test_as_skipped()
      }
    }
  }
```

### Additional context

image

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #1123

filters "ignored" tests and include them in the test output.

what should the test output look like?

just

`[IGNORED] <skip|ingore>testFuzz(uint256)` ?

### CODE REVIEW

**Comment by onbjerg** [comment]
I think `[SKIP]` is better (works w/ pass and fail)

**Comment by gakonst** [comment]
+1 `Skip`

**Review by gakonst — COMMENTED** [review]
hm should this also be on the contract name as well then?

**Comment by mds1** [comment]
Ah good point, it would be nice to support contract-level skips too, but `contract SkipMyContract` would be a new naming approach + seems more likely to clash with a real contract name than a `test` prefix. I'd be ok with it, but could also be an argument to go the cheatcode route instead.

**Comment by mattsse** [comment]
this adds `skip[tT]est.*´ naming convention to identify skipped test

output is now:

```
Running 1 test for src/dummy.sol:DummyTest
[SKIP] skipTestAnother()
[SKIP] skiptestCall()
[PASS] testCall() (gas: 179)
Test result: ok. 1 passed; 0 failed; 2 skipped; finished in 3.27ms

```

**Review by onbjerg — CHANGES_REQUESTED** [review]
If we go with function names determining if tests are skipped or not (as opposed to cheatcode as @mds1 suggested) I think it is better to use `testSkip` (not `skipTest`) since it is more in line with our other naming conventions

**Comment by mattsse** [comment]
that's a good point

will revise

**Comment by onbjerg** [comment]
No it's only the start of the test function: `testSkip*`. However you bring up a good point separately: it would make something like `testFail` not skippable :( Not sure

**Comment by mattsse** [comment]
it is now `test(.*)[sS]kip`


for contracts, this means we should stick to `<name>TestSkip`

**Comment by mattsse** [comment]
> No it's only the start of the test function: `testSkip*`. However you bring up a good point separately: it would make something like `testFail` not skippable :( Not sure

it would need to be `testSkipFail` then.

but not sure, I'd expect it to be either at the start or end

**Comment by mds1** [comment]
Some issues the naming convention approach may cause:
- forge-std has a test called `testSkip` to test it's `skip` helper method, so that will need to be renamed
- Maker has a parameter named `skip` and a corresponding test named [`test_cage_skip`](https://github.com/makerdao/dss/blob/fa4f6630afb0624d04a003e920b0d71a00331d98/src/test/end.t.sol#L440)
- Fei has a test called [`testQueueSkipCycle `](https://github.com/fei-protocol/flywheel-v2/blob/5ac5d314362188e3ece31a9db7deba529f4e8cc7/src/test/rewards/FlywheelGaugeRewardsTest.t.sol#L84)
- I didn't find any that were `testSkip*` but I may have missed some

Found with
https://sourcegraph.com/search?q=context:global+function+test%28.*%29%5BsS%5Dkip+lang:Solidity+&patternType=regexp

**Comment by mattsse** [comment]
thanks for this.

I don't have strong feelings about this convention, changing this would only require changing the `TestFunctionExt::is_test_skipped` impl

but I guess we narrowed it down to
* testSkip.*
* test(.*)Skip

following the convention for Fuzz, `testSkip(Fuzz|Fail)` would make sense

**Comment by mds1** [comment]
Based on existing tests it seems testSkip.* makes the most sense. Though I do feel a cheatcode would be simpler UX since it doesn't require remembering the nuances on the ordering/naming, and makes `--match-test` simpler to use also

**Comment by gakonst** [comment]
Feel like we want this to be with a cheatcode. Also we got a bunch of things going on at the same time so vote close and reprioritize separately

**Comment by mattsse** [comment]
sg, is not a critical feature so closing and turn this into cheatcode

**Pull request closed without merging**
