### PR TITLE
fix(coverage): lcov avoid double reporting for line hit

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
The line hit is reported doubled in lcov report. That can be repro with a contract 
```Solidity
contract AContract {
    int256 public i;

    function foo() public {
        i = 1;
    }
}
```
and test
```Solidity
contract AContractTest is Test {
    function testFoo() public {
        AContract a = new AContract();
        a.foo();
    }
}
```
running
`forge coverage --report lcov && genhtml lcov.info -o report  && firefox report/index.html` will generate report below

image

That happens because the generated lcov report contains `DA:8,1` line 2 times (`DA: line number, hit count`)

## Solution

- avoid adding line hit count twice (as a line and also as a statement)

### CODE REVIEW

**Review by DaniPopes — CHANGES_REQUESTED** [review]
Needs snapbox assertions

**Comment by grandizzy** [comment]
> Needs snapbox assertions

not sure how to do that since this one is LCOV report related only (that is to make sure certain line is not written twice in lcov.info file), do you have any suggestion? thanks

**Comment by DaniPopes** [comment]
Just replace assert_eq with assert_data_eq

**Comment by grandizzy** [comment]
> Just replace `assert_eq!` with `assert_data_eq!`, and use `str![]` for the string literal

done https://github.com/foundry-rs/foundry/pull/8400/commits/ba4d7594146ee257f72bcd4873b53541c77e01a7 thank you!

**Review by mattsse — APPROVED** [review]

**Review by DaniPopes — APPROVED** [review]

**Pull request merged**
