### PR TITLE
chore: fix flaky inline config test

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
- order of test contracts within same file could differ, see from https://github.com/foundry-rs/foundry/actions/runs/12453169770/job/34762982884#step:12:625
- split inline config test

### CODE REVIEW

**Comment by DaniPopes** [comment]
I think that is just because they are ran in parallel so the order is not deterministic

**Comment by grandizzy** [comment]
> I think that is just because they are ran in parallel so the order is not deterministic

ah right, that makes more sense

**Comment by grandizzy** [comment]
@DaniPopes is there any change you'd like to be done for this or good to go as it is? Thanks!

**Comment by DaniPopes** [comment]
should add -j1 instead of duplicating the command

**Comment by grandizzy** [comment]
> should add -j1 instead of duplicating the command (if it fixes it)

yep, changed to that, had to change the order of test though as they're picked up by suite name, pls check

**Review by DaniPopes — APPROVED** [review]

**Pull request merged**
