### PR TITLE
ci: nextext cross jobs

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
@onbjerg  started porting the cross jobs to nextest, I'm unsure how to replicate the different jobs (unit-test,...) with the cross setup which uses 2 matrixes without much duplication.

Not sure if possible to run the jobs (unit-test,..) use steps using additional matrixes for `non-forking,/forking` or if should run those as separate jobs and download the archive

wdyt?

### CODE REVIEW

**Comment by onbjerg** [comment]
Should be possible to do the matrix thing as well for xplatform since it's running all of the tests? Otherwise this looks good to me, not really a requirement to dedupe it

**Comment by mattsse** [comment]
yeh that was my initial idea to just replicate the matrix if there's no better.

will do that, will still be readable

**Comment by mattsse** [comment]
@onbjerg most of the checks are working now but the number of checks is a bit excessive even if a lot of them don't take much time, but this could result in a lot of backpressure if we merge multiple PRs and would block new PRs.

should we

* omit external integration test
* remove the `partition` matrix
* skip forking for unit tests

**Comment by onbjerg** [comment]
For cross platform I think it's ok to skip some of the tests which would also give us the ability to remove the partitions. Not sure what suite is best to remove, but ideally we would test most things that result in cross-platform errors in non-forking stuff (e.g. paths when building and so on)

Maybe skipping forking stuff + external integration and removing partition is really the way to go?

**Pull request closed without merging**
