### PR TITLE
feat(forge): --silent flag in CoreBuildArgs

### PR DESCRIPTION
**Pull request by shawnharmsen**
closes: https://github.com/foundry-rs/foundry/issues/1800

Still bumbling about trying to understand where to have the logic for https://github.com/foundry-rs/foundry/blob/0e258fb191ad32db70a8a461763053990dc88789/cli/src/compile.rs#L208

Currently have it commented out in: config/src/lib.rs

Any tips appreciated!

## Motivation

add `--silent` flag to supress all output

### CODE REVIEW

**Comment by shawnharmsen** [comment]
apologies but I'm a bit stuck here

1. Current commit works for `forge build --silent --force`
2. However, having trouble implementing for the other commands using CoreBuildArgs
```bash
forge debug
forge create
forge inspect
forge test
forge script
```

Will come back with fresh eyes

**Review by mattsse — CHANGES_REQUESTED** [review]
that's a good start

I believe most of them also share the  `CoreBuildArgs` so we don't need to replicate the `silent: bool` flag

I believe `forge create` already uses suppress if --json is provided so we need to fine-tune how `Project::compile` is invoked respectively.


since debug opens a tui, silent isn't really useful here

so main focus is build + test

adding `--silent` for test can be done here 
https://github.com/foundry-rs/foundry/blob/0342bc24b7d248d3049ca7cf78caf6df59a81e52/cli/src/cmd/forge/test.rs#L478

by accessing the `CoreBuildArgs`

**Comment by shawnharmsen** [comment]
results updated here

### forge build --silent
```bash
➜  playground git:(main) ✗ ~/CLionProjects/foundry/target/debug/forge build --force --silent
➜  playground git:(main) ✗
```

### forge test --silent
```bash
➜  playground git:(main) ✗ ~/CLionProjects/foundry/target/debug/forge test --force --silent

Running 1 test for test/Simple.t.sol:SimpleTest
[PASS] testValues() (gas: 8002)
Test result: ok. 1 passed; 0 failed; finished in 1.46ms

Running 5 tests for test/Greeter.t.sol:GreeterTest
[PASS] test_custom_greeting() (gas: 10206)
[PASS] test_default_greeting() (gas: 9822)
[PASS] test_get_greeting() (gas: 9813)
[PASS] test_non_owner_cannot_set_greeting() (gas: 12202)
[PASS] test_set_greeting() (gas: 18728)
Test result: ok. 5 passed; 0 failed; finished in 5.25ms
➜  playground git:(main) ✗
```


### forge create --silent
```bash
➜  playground git:(main) ✗ ~/CLionProjects/foundry/target/debug/forge create ./src/Simple.sol:Simple --verify --etherscan-api-key $ETHERSCAN_API_KEY --chain goerli --rpc-url $GOERLI_RPC_URL --private-key $PRIVATE_KEY --constructor-args "" --force --silent
Deployer: 0x28a435d0fe95e127e6b95babf232d5739217b3f0
Deployed to: 0xbd747107c78c5638b71f852b338a47976b307d84
Transaction hash: 0x5f64d0355016134b5244ae30fecdaae969c2310f24b4e0bbc8b0542efe465eb9
Starting contract verification...
Waiting for etherscan to detect contract deployment...

Submitting verification for [src/Simple.sol:Simple] 0xbd747107c78c5638b71f852b338a47976b307d84.

Submitting verification for [src/Simple.sol:Simple] 0xbd747107c78c5638b71f852b338a47976b307d84.
Submitted contract for verification:
	Response: `OK`
	GUID: `xumqziwiqcaccfrqa9j2i1wpb1ests6a9f6xn9hidrtbsfw7nb`
	URL: https://goerli.etherscan.io/address/0xbd747107c78c5638b71f852b338a47976b307d84#code
Waiting for verification result...
Contract source code already verified
```

**Review by mattsse — APPROVED** [review]
thanks lgtm!

**Pull request merged**
