### PR TITLE
feat(forge): add `selectors list` subcommand 

### LINKED ISSUE #6038: `forge selectors list`
### Component

Forge

### Describe the feature you would like

Sometimes I am debugging a local issue where I have an error with function selector and want to locate the function signature via selector, but without uploading these to the registry.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by schroyar**
## Motivation
Lists functions, events and errors signatures + selectors of an individual contract or all contracts in the workspace

Closes #6038 

## Solution

* add `List` to the `SelectorsSubcommands` enum on `inspector.rs` and implement the logic, using `comfy_table` to print the results

# Example output:

`forge selectors ls Dummy`

image

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
lgtm, I made some simplifications now that we moved to alloy types

pending @Evalir

**Review by Evalir — APPROVED** [review]
nice! will be useful for a lot of people. Love the simplifications @mattsse

**Comment by holic** [comment]
thanks all!

**Comment by seanmc9** [comment]
Just want to say thank you for this!! This is so helpful!

**Pull request merged**
