### PR TITLE
fix(coverage): proper instruction for 1st branch anchor

### LINKED ISSUE #7784: `forge coverage` produces incorrect output
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e01038f 2024-04-25T00:19:46.228617080Z)

### What command(s) is the bug in?

forge coverage

### Operating System

Linux

### Describe the bug

All branches are covered (look at if-else), but coverage is incorrect.

image

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
Re https://t.me/foundry_support/55383
PR https://github.com/foundry-rs/foundry/pull/8414 fixed the branch coverage report (issue reported in #7784 ) by properly mapping if/else source bodies

https://github.com/foundry-rs/foundry/blob/5af9d16ecb620192d4fe5ae61d33e429b7f5aff3/crates/evm/coverage/src/analysis.rs#L236-L241

but it also made the wrong assumption that the first branch opcode after JUMPI should be `pc + 1`

https://github.com/foundry-rs/foundry/blob/5af9d16ecb620192d4fe5ae61d33e429b7f5aff3/crates/evm/coverage/src/anchors.rs#L149-L153

This is not true because the evaluation is done for the opcode before JUMPI (so JUMPI is `pc + 1` and next opcode is `pc + 2`)

https://github.com/foundry-rs/foundry/blob/5af9d16ecb620192d4fe5ae61d33e429b7f5aff3/crates/evm/coverage/src/anchors.rs#L134-L136

## Solution

Proper source mappings fixes #7784 and #4294 (require and assert branches properly reported now), hence this PR reverts the instruction for first branch and adds back branching for asserts
Added unit tests for all require/assert branches
#4309 #4310 and #4315 tests were passing with wrong branch opcode, will follow up with a fix for them

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
cool

**Comment by KholdStare** [comment]
@mattsse @grandizzy I just upgraded Foundry, and found `assert` being counted as a branch again. I thought this was already agreed upon here: https://github.com/foundry-rs/foundry/issues/4294 .

There is no way to get 100% coverage if `assert` is considered a branch.

**Comment by KholdStare** [comment]
> > @mattsse @grandizzy I just upgraded Foundry, and found `assert` being counted as a branch again. I thought this was already agreed upon here: #4294 .
> > There is no way to get 100% coverage if `assert` is considered a branch.
> 
> @KholdStare pls check test here with assert branch and coverage 100% https://github.com/foundry-rs/foundry/blob/master/crates/forge/tests/cli/coverage.rs#L248

That is not the intended use of `assert` like was discussed and "litigated" in the previous issues. That's a job for `require` to check external inputs. Failing an assert should indicate a fundamental bug in the code, and therefore should be impossible to actually trigger in practice. All `assert`s in our codebase are impossible to trigger, so we will _never_ get coverage.

It's really disheartening to be building on a tool that has regressions _every single time_ we upgrade, seemingly reversing previously established facts. Tests were added with specific reasoning - making changes and reverting the tests at the same time should raise red flags. I am going to repeat what I mentioned before in the comment https://github.com/foundry-rs/foundry/pull/8413#issuecomment-2223638150. 

There is a subtle difference between require and assert:

- assert deals with asserting invariants that should hold no matter what the input is. Hence why it shouldn't be possible to hit "the other branch" - that would indicate a bug in the code.
- require deals with pre/post conditions that may get violated due to erroneous/malicious inputs. Both sides of the branch need to be checked as both cases can occur. That's why we have expectRevert in tests.

There is a semantic difference and it's very well highlighted [in the solidity docs](https://docs.soliditylang.org/en/latest/control-structures.html#panic-via-assert-and-error-via-require):

> Assert should only be used to test for internal errors, and to check invariants. Properly functioning code should never create a Panic, not even on invalid external input. If this happens, then there is a bug in your contract which you should fix. Language analysis tools can evaluate your contract to identify the conditions and function calls which will cause a Panic.

There is also a concrete/practical difference - [the SMTChecker in solc relies on this distinction](https://docs.soliditylang.org/en/latest/smtchecker.html):

> The SMTChecker module automatically tries to prove that the code satisfies the specification given by require and assert statements. That is, it considers require statements as assumptions and tries to prove that the conditions inside assert statements are always true. If an assertion failure is found, a counterexample may be given to the user showing how the assertion can be violated.

**Comment by grandizzy** [comment]
@KholdStare I see, please open a ticket and will remedy. This is a change that was done looong time ago so suspect you hit only now

**Comment by KholdStare** [comment]
> @KholdStare I see, please open a ticket and will remedy. This is a change that was done looong time ago so suspect you hit only now

Yeah, we keep our foundry version fixed between contract releases, so now that we're doing a new release, I upgraded foundry and ran into this issue.

Thanks!

**Comment by grandizzy** [comment]
Makes sense. We're heading to a 1.0 stable release candidate soon and would be great to have all the features used tested again. This should mitigate the kind of regressions you see and will give you the option to pin stable releases only.

**Pull request merged**
