### PR TITLE
test: add fork-prank-deal-transfer test

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
ref #3651

@marktoda I wasn't able to replicate the issue, could you please have a look at the added test and check if that differs from your setup that causes this.

Since this happens sporadically, I wonder if this has something todo with the provider.

### CODE REVIEW

**Comment by marktoda** [comment]
Thanks so much for running through this @mattsse ! I guess I should have tested my repro before sharing it, I just ran it locally and also couldn't repro with it. 

> has something to do with provider

Yeah I was wondering about this too, seeing it on both alchemy and infura apis, free and paid keys though

I went and tried to generate a minimal repro that causes this issue for me locally, but having trouble getting it to happen outside of our rather large test suite. I have noticed one interesting thing:
- It seems to only happen in the context of a large test suite run. I.e. I get the issue every few runs on `forge test`, but if I take a specific failing test and isolate it with `forge test --match-test <failingTestName>`, I can run it hundreds of times without a failure

In any case, until I have a good reliable repro for you I don't want to take any more of your cycles - appreciate the help again

**Comment by mattsse** [comment]
I see, then this sounds like a weird edge case with the underlying request handler, since that's the only thing that's somewhat shared across multiple test runs.

will take a closer look.

**Comment by marktoda** [comment]
and note moving the env check to before deal and it passes

**Comment by marktoda** [comment]
note maybe its not the io, as removing the try/catch and it works again

**Comment by mattsse** [comment]
this could be related to this `deal` bug #3687

**Comment by gakonst** [comment]
Mark, can you take another look on master? Is this still an issue? Else let's close.

**Comment by marktoda** [comment]
Still seeing this on master

Though luckily now I can share the code that we're seeing this in! https://github.com/Uniswap/universal-router-sdk

```
> yarn test # builds interop files
> for x in {1..100}; do forge test -vvv; done
...

    │   └─ ← "InsufficientETH()"
    └─ ← "call failed"
```

**Comment by marktoda** [comment]
oh, oops - re-fetch main, we changed the package name. And actually you shouldn't need to do the yarn stuff as interop.json is written to main now

**Comment by mattsse** [comment]
@marktoda after debugging this for a while, I finally found the issue: https://github.com/Uniswap/universal-router-sdk/pull/80 

closing this

**Comment by marktoda** [comment]
Wow, thank you - apologies for the bother

**Pull request closed without merging**
