### PR TITLE
chore(invariant): remove persist_state config, commit by default

### LINKED ISSUE #4994: feat(forge): native support for simulating the passage of time when running invariants
### Component

Forge

### Describe the feature you would like

Because most smart contract systems expect time to pass, it is a common need to simulate the passage of time (with `vm.warp`) when running invariant test campaigns with Foundry.

But this is difficult to do today because [state is not preserved during invariants runs](https://github.com/foundry-rs/foundry/issues/3005). Just look at [Maple Finance's solution](https://github.com/maple-labs/maple-core-v2/blob/00f01ae7175885f8d49ac201a1c72465e320b2f6/tests/invariants/BaseInvariants.t.sol#L34-L37) - they have to apply the `useCurrentTimestamp` modifier to all invariant tests, as well as all functions in the handler contracts.

Now, regardless of the state-preserving limitation and if and when it will be lifted, I posit that it would be helpful to offer native support for time warps in invariants.

Here's what I have in mind :

```toml
[profile.default.invariant]
  time_jump_min = 50
  time_jump_max = 1000
```

Nevermind the names - we can think about what would fit best later. What matters is the idea - to introduce two new config options which would be used for bounding a time jump that gets applied after every invariant test run, i.e. have Foundry do something like this:

```solidity
modifier jump() {
    uint256 timeWarp = block.timestamp;
    timeWarp = _bound(timeWarp, 50 seconds, 1000 seconds);
    timestampStore.increaseCurrentTimestamp(timeWarp);
    vm.warp(timestampStore.currentTimestamp());
    _;
}
```

This way, an invariant test campaign would more accurately simulate the real world, where time passes between function calls.

### Additional context

Related discussions:

- https://github.com/foundry-rs/forge-std/issues/376
- https://github.com/foundry-rs/foundry/issues/3005#issuecomment-1556141136
- https://t.me/foundry_support/34043
- https://t.me/foundry_support/35144

### LINKED ISSUE #7268: Unreachable revert path in invariant test
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (551bcb5 2024-02-28T07:40:04.170939000Z)

### What command(s) is the bug in?

forge test 

### Operating System

macOS (Intel)

### Describe the bug

When running a invariant test with `fail_on_revert = true` I get a call sequence which causes an arithmetic error: 

```
[FAIL. Reason: panic: arithmetic underflow or overflow (0x11)]
        [Sequence]
                sender=0x87b2D08110b7d50861141d7BBdd49326af3Ecb32 addr=[test/invariant/IonPool/ActorManager.t.sol:ActorManager]0x9334769e07df3B12e28D251c0DA84b72cfC0C1b6 calldata=borrow(uint128,uint128,uint128,uint128) args=[14234 [1.423e4], 10026 [1.002e4], 220588068670147766524049031157215289046 [2.205e38], 413]
                sender=0x00000000000000000000000000000000000000Bc addr=[test/invariant/IonPool/ActorManager.t.sol:ActorManager]0x9334769e07df3B12e28D251c0DA84b72cfC0C1b6 calldata=borrow(uint128,uint128,uint128,uint128) args=[340282366920938463463374607431768211452 [3.402e38], 2137374361896347860762549462890 [2.137e30], 340282366920938463463374607431768211452 [3.402e38], 1]
 invariant_meaningLessInvariant() (runs: 1, calls: 2, reverts: 1)
 ```
Looking at the second call trace with -vvv where the revert is supposed to be, there is no error:

image

I've added logging statements to the called `borrow` function that log different points in the function execution, including when the function call is complete and  from the logs can see that both calls made by the fuzzer reach the end of their execution:
```solidity
function borrow(uint128 borrowerIndex, uint128 ilkIndex, uint128 amount, uint128 warpTimeAmount) external {
        console.log("borrow is called");
        borrowerIndex = uint128(bound(borrowerIndex, 0, borrowers.length - 1));
        ilkIndex = uint128(bound(ilkIndex, 0, ionPool.ilkCount() - 1));

        borrowers[borrowerIndex].borrow(uint8(ilkIndex), amount, warpTimeAmount);
        console.log("borrow call completes successfully");
    }
```

image

It seems like the revert is due to an extra function call made by the fuzzer that isn't included in the call sequence which makes it impossible to reproduce with a unit test. 

To rule out the possibility of a revert in the invariant I used the following invariant definition:
```
function invariant_meaningLessInvariant() external {
        console.log("this invariant does nothing");
    }
```

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
Closes #7268 
Closes #4994 

## Solution

Remove `preserve_state` config and commit call by default - this will enable using `vm.warp` and `vm.roll` in invariants tests without any additional config (which is expected behavior)
From test result it can be seen there is a slightly penalty from persisting cheatcode state (not something to worry about IMO).

## Tests

Results were collected by performing different number of runs and depth on a test contract with:
- handler that advance block timestamp by 100 and increments block number on each call by using `vm.warp` and `vm.roll`  (worst case scenario as persisting cheatcode states is now done by default)
- target contract with single selector that makes several state updates

<details>
<summary>Test contract</summary>

```solidity
contract CommitState {
    uint256 state;
    mapping(address => uint256) public state1;
    mapping(address => mapping(address => bool)) public state2;

    function saveState(uint256 x, address y, address z) public {
        state = x;
        state1[y] = x;
        state2[y][z] = true;
    }
}

contract CommitStateHandler is Test {
    CommitState target;

    constructor() {
        target = new CommitState();
    }

    function fuzzTarget(uint256 x, address y, address z) public {
        vm.warp(block.timestamp + 100);
        vm.roll(block.number + 1);
        target.saveState(x, y, z);
    }
}

contract CommitStateTest is Test {
    function setUp() public {
        CommitStateHandler handler = new CommitStateHandler();
        targetContract(address(handler));
    }

    function invariant_commit_state() public view {}
}
```
</details>

| Runs/Depth | time with Master | time with PR |
| --- | --- | --- |
| 100/1000 | 0m18.601s | 0m19.587s |
| 1000/1000 | 2m54.369s | 3m12.411s |
| 1000/5000 | 15m21.012s | 15m55.039s |
| 1/10000 | 0m10.528s | 0m10.827s |
| 10/10000 | 0m27.174s | 0m29.075s |
| 100/10000 | 3m18.966s | 3m26.910s |
| 10000/100 | 2m55.770s | 3m1.623s |

* time contains test contract compile time too

### CODE REVIEW

**Comment by grandizzy** [comment]
hey @pcaversaccio wanted to let you know that this change breaks `sneakmate` invariant `invariantExecutingNotReadyProposal` because time is now preserved between calls

Let's say there's a first run calling `invariantExecutingNotReadyProposal`
https://github.com/pcaversaccio/snekmate/blob/e20185c1776256984d888d02dc243fe793119f2e/test/governance/TimelockController.t.sol#L4352-L4368 which calls `TimelockControllerHandler.execute` and properly reverts with `"TimelockController: operation is not ready"`. However, `TimelockControllerHandler.execute` already does
```
        vm.warp(block.timestamp + minDelay);
```
before calling `timelockController.execute` (which reverts), see https://github.com/pcaversaccio/snekmate/blob/e20185c1776256984d888d02dc243fe793119f2e/test/governance/TimelockController.t.sol#L4424-L4433

Therefore  2nd time when  `invariantExecutingNotReadyProposal` is called time has properly passed (advanced from prev call) and proposal will pass / call won't revert (see logs here [snekmate.txt](https://github.com/foundry-rs/foundry/files/15162148/snekmate.txt)). I think it's safe to assume a fix is to just remove the warp call or make sure you're not advancing time so much as the proposal becomes executable.

**Comment by pcaversaccio** [comment]
@grandizzy thanks for the heads-up; what's the time plan on the release on this breaking change?

**Comment by grandizzy** [comment]
> @grandizzy thanks for the heads-up; what's the time plan on the release on this breaking change?

@pcaversaccio I am checking with other projects how this affects their usage, so probably 1 week or so

**Comment by pcaversaccio** [comment]
Addressed via https://github.com/pcaversaccio/snekmate/pull/241 in snekmate.

**Comment by grandizzy** [comment]
ping @PaulRBerg @lucas-manuel do you forsee any issue (like the one above) in your projects? Thank you

**Comment by PaulRBerg** [comment]
tagging @smol-ninja and @andreivladbrg

**Comment by grandizzy** [comment]
btw, if you want to give it a quick check you can set `preserve_state = true` as this will be made default with this PR

**Comment by smol-ninja** [comment]
@grandizzy we are good with this PR. I have tested and there are no issues with the change.

**Comment by grandizzy** [comment]
tested ok ajna, morpho and maple

**Review by DaniPopes — APPROVED** [review]

**Review by mattsse — APPROVED** [review]
nice!

**Pull request merged**
