### PR TITLE
chore: bump strum

### PR DESCRIPTION
**Pull request by odyslam**
- bump strum
- rust-analyzer style, lmk if we like them or we want to revert to original

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
I think this also needs to bump the lock file?
or is it 0.25 there already?

**Comment by odyslam** [comment]
Without this PR, forge does not compile if consumed as a lib

**Review by Evalir — CHANGES_REQUESTED** [review]
Also need to bump chisel's cargo.toml

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
@odyslam pending broken build

**Review by mattsse — APPROVED** [review]

**Review by Evalir — APPROVED** [review]
This looks good, but had to nuke the cargo lock for this to build. Unsure why this was happening. Maybe there was a weird version mismatch somewhere here.

**Pull request merged**
