### PR TITLE
chore: add git to docker image

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
since several forge commands depend on git we should include in the image

### CODE REVIEW

**Comment by dmfxyz** [comment]
@gakonst @mattsse let's add git if users need it. We don't want to be slowing people down if it's impeding their use of the docker image. 

We can in the future follow best practices of having a development image and slim image (the former including git and maybe other build tools). Since we only have one image for now, my thinking is let's make it usable for as many people as possible.

**Review by dmfxyz — APPROVED** [review]
LGTM

**Comment by mattsse** [comment]
oh that's actually a good point and makes total sense.

but I don't think there's any downside in including git

**Comment by gakonst** [comment]
cool - thx folks

**Pull request merged**
