### PR TITLE
fix(fmt): write files on disk only if they're not perfect match

### LINKED ISSUE #6033: bug(`forge fmt`): Files are formatted even if they are unaffected thus updating their `Last Modified` timestamp
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

_No response_

### What command(s) is the bug in?

_No response_

### Operating System

Linux

### Describe the bug

When running `forge fmt`, all files touched by it have their `Last Modified` time updated even if the file remains unchanged.

This negatively impacts the DX of using `forge fmt` e.g. in a Makefile.

### LINKED ISSUE #8769: bug(`forge fmt`): files sometimes get formatted to entirely empty or partially
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2442e7a 2024-08-28T00:20:11.390296375Z)

### What command(s) is the bug in?

forge fmt

### Operating System

Linux

### Describe the bug

Sometimes running `forge fmt` on a large codebase entirely empties the file content of a file, often unrelated to the file a user has performed changes to. It also sometimes removes a leading `/` in front of `// SPDX-License-Identifier: `.

It is not consistent. Sometimes one file is emptied, sometimes it is many files, sometimes it doesn't happen. Appears to be some kind of race condition.

~~This appears to be behavior introduced relatively recently.~~ see https://github.com/foundry-rs/foundry/issues/8769#issuecomment-2317340461

### To reproduce

Optional: comment out `solc = "0.8.18"` in `foundry.toml` in `foundry/testdata`

Run `forge fmt` inside of the `foundry/testdata` directory multiple times in relatively rapid succession.

### Examples

When running `forge fmt` multiple times (no user edits were made):

```
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   default/cheats/GetFoundryVersion.t.sol
	modified:   default/cheats/MockCall.t.sol
	modified:   default/cheats/SignP256.t.sol
```

Example of it removing a single `/`:

```diff
diff --git a/testdata/default/cheats/MockCall.t.sol b/testdata/default/cheats/MockCall.t.sol
index df7ee89c73..8a6c050089 100644
--- a/testdata/default/cheats/MockCall.t.sol
+++ b/testdata/default/cheats/MockCall.t.sol
@@ -1,4 +1,5 @@
-// SPDX-License-Identifier: MIT OR Apache-2.0
+
+/ SPDX-License-Identifier: MIT OR Apache-2.0
 pragma solidity 0.8.18;
 
 import "ds-test/test.sol";
 ```

Example of it emptying a file:

```diff
diff --git a/testdata/default/cheats/SignP256.t.sol b/testdata/default/cheats/SignP256.t.sol
index f1b62fe78d..8b13789179 100644
--- a/testdata/default/cheats/SignP256.t.sol
+++ b/testdata/default/cheats/SignP256.t.sol
@@ -1,18 +1 @@
-// SPDX-License-Identifier: MIT OR Apache-2.0
-pragma solidity 0.8.18;
 
-import "ds-test/test.sol";
-import "cheats/Vm.sol";
-
-contract SignTest is DSTest {
-    Vm constant vm = Vm(HEVM_ADDRESS);
-
-    function testSignP256() public {
-        bytes32 pk = hex"A8568B74282DCC66FF70F10B4CE5CC7B391282F5381BBB4F4D8DD96974B16E6B";
-        bytes32 digest = hex"54705ba3baafdbdfba8c5f9a70f7a89bee98d906b53e31074da7baecdc0da9ad";
-
-        (bytes32 r, bytes32 s) = vm.signP256(uint256(pk), digest);
-        assertEq(r, hex"7C11C3641B19E7822DB644CBF76ED0420A013928C2FD3E36D8EF983B103BDFE1");
-        assertEq(s, hex"317D89879868D484810D4E508A96109F8C87617B7BE9337411348D7B786F945F");
-    }
-}
```

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
Closes #6033 
Closes #8769 
Fixes issue reported in https://github.com/foundry-rs/foundry/pull/8762#issuecomment-2315644909

## Solution

- do not write files on disk if no change (ratio = 1.0)
- return false if statement empty and block doesn't fit on a single line

### CODE REVIEW

**Comment by zerosnacks** [comment]
Fix works! Haven't been able to replicate the issue with this PR,  even with multiple modified files

**Comment by mds1** [comment]
Does this also fix https://github.com/foundry-rs/foundry/pull/8762#issuecomment-2315644909? Wondering if I should test this PR to verify

**Comment by grandizzy** [comment]
> Does this also fix [#8762 (comment)](https://github.com/foundry-rs/foundry/pull/8762#issuecomment-2315644909)? Wondering if I should test this PR to verify

No, it doesn't, I'll work on it next and tag you when ready.

**Comment by mds1** [comment]
Got it, thanks :)

**Comment by grandizzy** [comment]
> Got it, thanks :)

hey @mds1 I included a fix for that comment in this PR pls see https://github.com/foundry-rs/foundry/pull/8775/commits/0c413abde25fa522b9f721314f7730471ce8b31b The issue was related to if/else statements when prev branch didn't have any statement then the current branch was moved on a new line, pls give it a try, thank you!

**Review by zerosnacks — APPROVED** [review]
Thanks!

**Comment by mds1** [comment]
@grandizzy Confirmed that `forge fmt` using this PR results in no more diff, so that issue is fixed—thank you!

**Pull request merged**
