### PR TITLE
Revert "feat(cheatcodes): Make `expectCall` only work for the next call's subcalls"

### PR DESCRIPTION
**Pull request by mattsse**
Reverts foundry-rs/foundry#4986

this was blocked for 1.0 and should not have been merged yet.

### CODE REVIEW

**Comment by PaulRBerg** [comment]
Could you please cut another release, @mattsse?

Our tests are failing now:

https://app.warp.dev/block/mLxbng37Ztgs9OxSko3PMf

**Comment by mattsse** [comment]
already running, sorry for the inconvenience

**Comment by PaulRBerg** [comment]
TY @mattsse!

Also, FWIW, I don't think the implementation in #4986 works as expected.

Our tests already adhere to the rule of not counting calls made at the root test level, so it's strange that we started getting errors.

FWIW, the depth in our case is greater than usual, as we're routing the calls via delegatecall, specifically via the `execute` function in PRBProxy:

https://github.com/PaulRBerg/prb-proxy/blob/b5338c7e5a3a10468f584ea1f1caca08a510939a/src/PRBProxy.sol#L87

Lmk if you'd like access to the private repo @mattsse @Evalir for investigation. We also have a CI run that failed:

https://github.com/sablier-labs/v2-periphery/actions/runs/5071179085/jobs/9107504005

**Comment by Evalir** [comment]
Hey @PaulRBerg, gotcha, this is great feedback. We're gonna start merging these into a feature branch, so we can run extended QA on big repos that use foundry heavily—we'll integrate prb-math and prb-proxy into external integration tests for this as well.

Would love access to the private repo—that way I can run QA and debug what might not be working as expected!

**Comment by PaulRBerg** [comment]
Can confirm that the latest release (`3764b55 2023-05-24T17:24:24.100981000Z`) works now, thanks guys.

**Comment by Evalir** [comment]
Amazing, great to hear. Will probably be poking around really soon and testing with the new/upcoming changes!

**Pull request merged**
