### PR TITLE
chore(deps): bump revm-inspectors

### PR DESCRIPTION
**Pull request by DaniPopes**
Fixes https://github.com/foundry-rs/foundry/issues/8283

### CODE REVIEW

**Comment by DaniPopes** [comment]
No idea why we're off in gas

cc @klkvr @zerosnacks PTAL

**Comment by DaniPopes** [comment]
Actually nvm, it fails on main too. I just re-ran CI and it failed: https://github.com/foundry-rs/foundry/actions/runs/9725944379/job/26846412657

Don't really know what that is

**Comment by DaniPopes** [comment]
cc @mattsse

**Comment by DaniPopes** [comment]
https://github.com/foundry-rs/foundry/pull/8302

**Review by mattsse — APPROVED** [review]

**Pull request merged**
