### PR TITLE
chore(forge): sort snapshot report

### LINKED ISSUE #4127: Alphabetical sorting of gas snapshot results
### Component

Forge

### Describe the feature you would like

It would be nice to have an `--alpha` or `--alphabetical` flag in `forge snapshot` that would sort the gas snapshot results alphabetically.

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #4127

sort snapshot reports by default

### CODE REVIEW

**Review by rkrasiuk — APPROVED** [review]
lgtm

**Comment by mds1** [comment]
Worth noting this will be a breaking change for everyone using `forge snapshot` in CI, so I'm not sure this should be the default until we have real semver releases 😅 So maybe behind a flag for now?

**Comment by mattsse** [comment]
> Worth noting this will be a breaking change for everyone using forge snapshot in CI

this changes the order, but not how we compare against previous runs, so I guess this is fine?

**Comment by mds1** [comment]
Ahh didn't realize that, yea that seems ok then. Thanks 👌

**Comment by PaulRBerg** [comment]
@mds1 as Matt said this is only an aesthetic change.

I think many people will smile upon this new behavior though, since it will make gas snapshots more readable - before this, I always had to use CMD+F to find the test function I was interested in.

**Pull request merged**
