### PR TITLE
chore(cast): add 0x prefix to `cast wallet new` output

### LINKED ISSUE #3635: [BUG -cast] Prefix of 0x - when generating vanity wallets via cast wallet vanity
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c8431ed 2022-11-07T00:08:05.346696623Z)

### What command(s) is the bug in?

cast wallet vanity --starts-with / --ends-with

### Operating System

Linux

### Describe the bug

# Description 

- When generating a vanity address using `cast wallet vanity --starts-with or --ends-with` a prefix of `0x` is added to the private key. 

# Repro 
image

- Following is the screen shot of the command and the issue

[screen shot](https://i.ibb.co/92kg0G6/image.png)

### PR DESCRIPTION
**Pull request by rkrasiuk**
## Motivation

close #3635

## Solution

add `0x` prefix to make `cast wallet new` output consistent with `cast wallet vanity`

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
lgtm

**Comment by mds1** [comment]
I'd actually suggest we always include the 0x prefix, as that's what most tooling does  IME

**Comment by rkrasiuk** [comment]
@mds1 sounds good. neither me nor @mattsse were strongly opinionated on this one

**Comment by mattsse** [comment]
> I'd actually suggest we always include the 0x prefix, as that's what most tooling does IME. Also makes it consistent with traces where the 0x prefix is always shown

I'd also lean towards that.
just because it's hex. so I guess we close this and fix in wallet new instead @rkrasiuk ?

**Review by mattsse — APPROVED** [review]

**Pull request merged**
