### PR TITLE
chore: tables cleanup

### PR DESCRIPTION
**Pull request by DaniPopes**
## Motivation

Small cleanup

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
lgtm

fyi @DoTheBestToGetTheBest

**Comment by DoTheBestToGetTheBest** [comment]
> lgtm
> 
> fyi @DoTheBestToGetTheBest

hey, i'm confused, was going to add Hex_Value but based on this PR value is now Hex. We don't need hex value table ?

**Comment by DaniPopes** [comment]
This is just code cleanup, no functional changes

**Comment by DoTheBestToGetTheBest** [comment]
> is is just code cleanup, no functional changes

well i just tested

 cast storage --rpc-url https://mainnet.optimism.io --etherscan-api-key <YOUR_API_KEY> 0x13b0D85CcB8bf860b6b79AF3029fCA081AE9beF2
 
 
 and value are not anymore decimal instead they are hex
 
 0x000000000000000000000000554282cf65b42fc8fddc6041eb24ce5e8a0632ad

**Comment by DaniPopes** [comment]
Oh you're right, I guess we can add both

**Pull request merged**
