### PR TITLE
test: add cast proof test

### PR DESCRIPTION
**Pull request by mattsse**
ref https://github.com/foundry-rs/book/pull/1052

### CODE REVIEW

**Comment by DaniPopes** [comment]
Can you also add `0x1` `0x01` or something which is not padded

**Review by excaliborr — COMMENTED** [review]
The thing is the proofs that are generated from `0` and `bytes32(0)` are not the same, I found this when verifying them against an MPT where the proof from `cast proof 0` reverts and `cast proof bytes32(0)` was a valid proof, thats why I was updating the documentation

**Comment by mattsse** [comment]
hmm, odd, as shown here both are parsed the same

**Comment by excaliborr** [comment]
> hmm, odd, as shown here both are parsed the same

Ok so my above comment is wrong, both proofs are the same however the proof I get from my eth_getProof rpc when RLP encoding generates the correct output from an MPT, but the proof from `cast proof` is there a chance this is a known issue?

**Comment by excaliborr** [comment]
Ok I figured it out, it ended up being error in my scripts interacting with cast proof sorry for the confusion

**Pull request merged**
