### PR TITLE
fix(invariant): merge logs & traces from error and replay

### PR DESCRIPTION
**Pull request by shekhirin**
## Motivation

https://github.com/foundry-rs/foundry/issues/2962

### CODE REVIEW

**Comment by gakonst** [comment]
Closing as stale.

**Comment by mds1** [comment]
@lucas-manuel this is the PR that you still use because it did work and improve logging right?

If so, @shekhirin @gakonst can we re-open this / resolve any conflicts and merge it? The state of logging/observability in invariant tests is a bit rough

**Comment by shekhirin** [comment]
@mds1 oof yeah sorry about that, it became stale quite a while ago. i'll resolve the conflicts and open it for the review!

**Comment by mds1** [comment]
awesome, thanks!

**Comment by shekhirin** [comment]
@mds1 @lucas-manuel does any of you guys have a repro when not enough logs/traces are outputted with the current master? I remember Lucas was reporting it on the Maple codebase but I can't figure out what do I need to do to break the invariant correctly for this repro lol.

**Comment by lucas-manuel** [comment]
@shekhirin on this branch https://github.com/lucas-manuel/invariant-examples/tree/demo-log-issue run `forge t --mt invariant_C` I updated this line to fail on purpose: https://github.com/lucas-manuel/invariant-examples/blob/7569a2a11dde346b1a7c2305f977927c9592f120/test/WrappedTests.t.sol#L35

Don't see `expected` vs `actual`

**Pull request closed without merging**
