### PR TITLE
feat(cli): Update Flashbots URL to use `fast` endpoint to improve transaction inclusion guarantees

### PR DESCRIPTION
**Pull request by zerosnacks**
## Motivation

To improve transaction inclusion guarantees Flashbots offers a [fast](https://docs.flashbots.net/flashbots-protect/quick-start#faster-transactions) endpoint that shares the transaction with all [registered builders](https://github.com/flashbots/dowg/blob/main/builder-registrations.json).

## Solution

To prevent introducing unnecessary breaking changes whilst offering major benefits I suggest using Flashbots' fast route.

A future solution could be to allow the user to define their own `BUILDER_RPC_URL` (separate from the `ETH_RPC_URL`). and get rid of the vendor lock-in naming of `flashbots` to something more neutral like `private`.

### CODE REVIEW

**Review by onbjerg — APPROVED** [review]
lgtm

**Review by Evalir — APPROVED** [review]

**Comment by mds1** [comment]
What's the rationale for using `/fast` as the default, when flashbots doesn't use it as their default, i.e. what security tradeoff is being made with fast mode?

**Comment by zerosnacks** [comment]
> What's the rationale for using `/fast` as the default, when flashbots doesn't use it as their default, i.e. what security tradeoff is being made with fast mode? IMO foundry should lean towards being conservative here, and users can manually specify the fast URL when needed

Rationale is that at the time this feature was introduced Flashbots was the dominant builder RPC offering private transactions whereas nowadays there is a much more diverse builders market.

According to https://libmev.com/builders Flashbots only builds 2.3% of the blocks on mainnet, hardly competitive anymore.

The `/fast` route sends to a subset of all builders, curated by Flashbots, that are trusted by Flashbots.

It makes sense that Flashbots doesn't default to `/fast` because sharing all private orderflow with all builders means losing your competitive advantage.

Searchers often maintain their own list of builders that they trust and send their bundles to, ranked by likeliness of transaction inclusion and personal preference. Asking Foundry to do the same is unrealistic and out of scope I think.

**Comment by mds1** [comment]
Got it, thanks for the explanation! Seems reasonable to me then

**Review by mds1 — APPROVED** [review]

**Comment by zerosnacks** [comment]
> i.e. what security tradeoff is being made with fast mode? IMO foundry should lean towards being conservative here, and users can manually specify the fast URL when needed

The security tradeoff is that by sharing the transaction with many builders you increase the odds of being vulnerable to a builder acting maliciously (front running, back running, sandwiching).

**Pull request merged**
