### PR TITLE
chore: add nix flake for dev shell

### PR DESCRIPTION
**Pull request by beeb**
This PR adds a nix flake definition for a dev shell that provides the necessary components to building and testing foundry.

## Motivation

In order to compile and test successfully, the workspace requires Rust nightly, solc and libusb. These dependencies must be installed by users and could be provided system wide. However, it's a good idea to provide nix users with a pre-configured devShell that includes all these dependencies.

## Solution

A nix flake is a deterministic definition file that configures the required nix packages that must be present in the PATH when developing a project.

The shell can be activated with the `nix develop` command and provides the rust toolchain on nightly with clippy and rustfmt, the solidity compiler at v0.8.20 and libusb1.

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
unfortunately, I haven't gotten into nix yet...
so I'm not really familiar with these settings, but I think these don't require too much maintenance so I'm okay with including this.

wdyt @DaniPopes @onbjerg @Evalir ?

**Review by Evalir — APPROVED** [review]
I also don't really know nix, so i'm not too qualified to review this—but I think what we want is something that ideally is not opinionated and therefore won't lead us to get many patches for this. I'm ok with including this if it's like so

**Comment by beeb** [comment]
The only maintenance would be to update the lock file when a new nightly for the rust compiler would be desirable or when a different version of solc would be required (in this case also the flake would require an update). This is done with `nix flake update .`

**Comment by beeb** [comment]
Later I can check on my Mac that everything is also included for mac development

**Comment by beeb** [comment]
In case absolutely no maintenance is required, I think publishing the flake.nix without the lock file (and adding it to .gitignore) could also be a viable solution. But then it's not 100% reproducible, someone might use a different nightly than someone else. At the moment since you don't include a  `rust-toolchain.toml` I think anyway there is no version of the rust compiler that is enforced.

**Comment by mattsse** [comment]
> nix flake update .

I think that we can manage

sgtm

any concerns @onbjerg ?

**Comment by Evalir** [comment]
let's wait for breg's approval before merging

**Comment by sambacha** [comment]
I will literally stop shitposting if this is merged 

Inshallah @gakonst sees this pls ser make it a happy merry christmas

**Comment by cawfree** [comment]
add a what to the what now

**Comment by Evalir** [comment]
@onbjerg sir

**Pull request merged**
