### PR TITLE
add timestamp to release tag for nightly

### PR DESCRIPTION
**Pull request by thedavidmeister**
## Motivation

https://github.com/foundry-rs/foundry/issues/6732

https://github.com/shazow/foundry.nix/pull/32

## Solution

include unix stamp as well as github sha in nightly tags

### CODE REVIEW

**Comment by shazow** [comment]
Is there any other way to fix the release builders from having a race condition?

This would also disrupt the purging (which takes last N builds, having duplicate builds would reduce the effective number of N).

**Comment by onbjerg** [comment]
I'm not super filled in on the context, what exactly does adding a timestamp solve?

**Comment by thedavidmeister** [comment]
@onbjerg @shazow it's not a race condition during the build

the assets are being _rebuilt and replaced_ for the same tag

296535124-26fc72a1-b673-4a16-91cb-f61c1f29ab6c

you can see in this screenshot that there's a 14 hour gap between the first time the tag was created and when the assets were rebuilt and replaced

because rust is not deterministic when it rebuilt the assets all their shas changed, so anything downstream that checks the sha of its dependencies will error

the nix overlay does this, but the issue is not specific to nix, most tooling that has a concept of lock files would also be checking hashes of downloaded dependencies

**Comment by shazow** [comment]
Do we have any ideas why existing assets with the same tag are being rebuilt, though?

**Comment by thedavidmeister** [comment]
@shazow i don't know that, would need someone from foundry to provide that context

if it's time based though, there's always a chance that 2+ builds could happen on the same commit, if nothing is merged in the meantime

**Comment by shazow** [comment]
> if it's time based though, there's always a chance that 2+ builds could happen on the same commit, if nothing is merged in the meantime

That's a race condition. :) We can add a mutex to the github action to prevent multiple actions from running at the same time under some key.

But yes I agree it would help if someone from foundry would help us look into what's going on here.

**Comment by shazow** [comment]
@thedavidmeister Is there anything indicative of the behaviour you've seen in this page? https://github.com/foundry-rs/foundry/actions/workflows/release.yml

For example, 4 days ago there were failures, so the action was re-run manually, was that when the assets got rugged?

**Comment by thedavidmeister** [comment]
@shazow it's not that multiple actions are running at the same time

it could be days apart

consider that some sha xyz exists on monday, a build runs on tuesday and creates a tag `nightly-xyz`, then nothing happens wednesday, then on thursday a build runs and rebuilds `nightly-xyz` because no new shas have been created

on thursday all the assets will appear corrupt to anyone who read the sha at any time on tuesday and wednesday

**Comment by thedavidmeister** [comment]
> @thedavidmeister Is there anything indicative of the behaviour you've seen in this page? https://github.com/foundry-rs/foundry/actions/workflows/release.yml
> 
> For example, 4 days ago there were failures, so the action was re-run manually, was that when the assets got rugged?

hmmm, so let's distinguish between "assets being rugged" as when they just get flat out deleted and 404'd vs. "corrupted" which is when they are rebuilt to a different sha from their initial release state

the corruption i was seeing happen every day til i created my own fork, maybe this was a co-incidence or indicates a pattern

**Comment by thedavidmeister** [comment]
@onbjerg yes, i understand the tag happens first, and it's not a problem because the downstream build has a filter on it already that ignores incomplete releases while they are still building

skipping tags that already exist would be fine too, i don't know why the releases are happening multiple times so i just figured it would be safest to keep every build that someone wanted for whatever reason

**Comment by onbjerg** [comment]
I'd rather we implement that fix than add a timestamp

**Comment by Evalir** [comment]
Can this be closed? @shazow / @thedavidmeister

**Comment by shazow** [comment]
I believe so

**Pull request closed without merging**
