### PR TITLE
Int256 fuzz strategy

### PR DESCRIPTION
**Pull request by alexeuler**
This PR adds better int256 fuzzing strategy akin to [#735](https://github.com/foundry-rs/foundry/pull/735)

## Motivation
Pretty much the same as in [#735](https://github.com/foundry-rs/foundry/pull/735)

Note: there's also #1259 open, however I don't believe we can reuse Uint strategy that easily unfortunately. Specifically see this comment https://github.com/foundry-rs/foundry/pull/1259/#discussion_r930760189

## Solution

Implement a new fuzz strategy for int256

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
not really familiar with the mentioned PR, wdyt @mds1?

code lgtm

**Comment by alexeuler** [comment]
> does this supersede #1259 ?

Yes

**Comment by mds1** [comment]
Oh awesome thanks for the PR @alexeuler! I'm out this week so can take a closer look next week, but from a quick review this LGTM. Also tagging @brockelmore here in case he has bandwidth to review this before me.

Would be great to have a similar strategy for `bytesNN` too.

Any thoughts on how to dedupe the uintNN, intNN, and byesNN strategies so that if we e.g. change the weights/number of strategies we only need to change things in one place and it's easier to keep them in sync? Mainly I'm thinking that eventually we should merge edge biasing + dict into one strategy, with the dict seeded with the edge values, that way we can expose a single flag in the config to tweak the strategy weights.

**Review by gakonst — APPROVED** [review]
great! +1 on @mds1 question on how can we unify the code across all these. maybe with a macro?

**Comment by gakonst** [comment]
@alexeuler should we merge as-is and investigate the other types as a follow up?

**Comment by alexeuler** [comment]
> Oh awesome thanks for the PR @alexeuler! I'm out this week so can take a closer look next week, but from a quick review this LGTM. Also tagging @brockelmore here in case he has bandwidth to review this before me.
> 
> 
> 
> Would be great to have a similar strategy for `bytesNN` too.
> 
> 
> 
> Any thoughts on how to dedupe the uintNN, intNN, and byesNN strategies so that if we e.g. change the weights/number of strategies we only need to change things in one place and it's easier to keep them in sync? Mainly I'm thinking that eventually we should merge edge biasing + dict into one strategy, with the dict seeded with the edge values, that way we can expose a single flag in the config to tweak the strategy weights.

I think there are some small differences in each - uint, int and bytes, so they couldn't be inferred from one another. Some code sharing is possible but since  strategies doesn't have too much code, prob copy paste is a way to go.

**Comment by alexeuler** [comment]
> @alexeuler should we merge as-is and investigate the other types as a follow up?

I'd probably go one type by one. And then we can figure out if we can abstract something away.

**Pull request merged**
