### PR TITLE
#991 Deterministic Fuzzer with RNG Seeding

### PR DESCRIPTION
**Pull request by Bind**
## Motivation

Allow users to set a RNG seed to get deterministic fuzzing as outlined in [#issue-991](https://github.com/foundry-rs/foundry/issues/991#issuecomment-1125544891)

## Solution

This PR specifically handles RNG-Seeding which simply pipes a `uint256` from the `foundry.toml` or `--fuzz-seed` cli arg into the TestRunner initialization. 

## Open Questions

How should I best leverage the built-in test macros to validate fuzzing is deterministic on _per test_ basis regardless of changes to the contract being tested? (Is there an existing set of tests I should reference while building this?)

### CODE REVIEW

**Comment by gakonst** [comment]
Hey @Bind just checking up on what your plans for next steps are here! @mattsse can provide some guidance regarding how to test this, but I'd check how we do it in the integration tests: https://github.com/foundry-rs/foundry/blob/master/cli/tests/it/test_cmd.rs#L236-L279.

**Comment by gakonst** [comment]
hi @Bind just bumping this again :D

**Comment by mattsse** [comment]
This is ready now @gakonst 

blocked by https://github.com/gakonst/ethers-rs/pull/1524

**Review by gakonst — APPROVED** [review]
LGTM. Clean.

**Comment by 0xKarl98** [comment]
the fuzz_seed is just an uint256 value ? 
here is what i've found : 
pub fuzz_seed: Option<U256>,

**Comment by mds1** [comment]
yes exactly, in your config file you can use something like

```toml
[fuzz]
seed = 10
```

And leave out the `seed` key to set no fuzz seed

**Pull request merged**
