### PR TITLE
revm v1.9 bytecode hash

### PR DESCRIPTION
**Pull request by rakita**
Updating revm to `v1.9`

more on the change here: https://github.com/bluealloy/revm/pull/165

It removes repetitive hashing and speeds up the fuzzing tests in the forge.

Additionally I moved the flag for `limit_contract_code_size` in CREATE/CREATE2 from Inspector `override_spec` to `cfg` and I set it to max value in foundry. Please check if this is okay or maybe in some places it should be consensus value 0x6000?

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
ty!

**Comment by mattsse** [comment]
broke a test that compared used json object of `cfg`

updated

**Comment by gakonst** [comment]
@onbjerg time to run new bench on your box..

**Comment by onbjerg** [comment]
Nightly:

```
solmate on  main is 📦 v6.5.0 via  v18.7.0
❯ hyperfine 'forge test --no-match-test "testSafeTransferFromToEOA"'
Benchmark 1: forge test --no-match-test "testSafeTransferFromToEOA"
  Time (mean ± σ):      2.989 s ±  0.194 s    [User: 34.802 s, System: 0.425 s]
  Range (min … max):    2.740 s …  3.283 s    10 runs
```

This PR:

```
solmate on  main is 📦 v6.5.0 via  v18.7.0 took 2s
❯ hyperfine 'forge test --no-match-test "testSafeTransferFromToEOA"'
Benchmark 1: forge test --no-match-test "testSafeTransferFromToEOA"
  Time (mean ± σ):      2.504 s ±  0.218 s    [User: 24.660 s, System: 0.429 s]
  Range (min … max):    2.189 s …  2.839 s    10 runs
```

:fire:

**Comment by gakonst** [comment]
Amazing. Was this also using `RUSTFLAGS="-C target-cpu=native"` for both?

**Comment by onbjerg** [comment]
None of them used that, can try with those flags

**Comment by gakonst** [comment]
Yep, try `RUSTFLAGS="-C target-cpu=native" cargo b --release`

**Comment by onbjerg** [comment]
@gakonst Results were about the same for me, very minor/insignificant change

**Comment by rakita** [comment]
15-20% sounds right.

I don't see any major low hanging fruits that would give as more performance boosts. 
`calldataload` is probably the biggest one not optimized, but that is just a few percentages of execution.
It is maybe worth looking at  `run_fuzz_test`, it uses `HashMap::insert` a lot.

**Comment by mattsse** [comment]
yeh definitely (invariant)fuzzing, 
there's also a lot of Abi cloning involved that could be optimized

**Pull request merged**
