### PR TITLE
fix: script simulation with default sender

### LINKED ISSUE #8960: `EvmError: Revert` upon deploy; inconsistent with debugger
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (883bb1c 2024-09-25T00:24:44.893538000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Intel)

### Describe the bug

I am trying to execute a more complex deploy, using Solidity Scripting (see script [here](https://github.com/firnprotocol/contracts/blob/master/script/Firn.s.sol)). **TLDR**: the script fails, with a nondescript error. when I step through with the debugger, the problematic line comes and goes without problem. this shows (a) inconsistency between the script and the debugger and (b) it seems a bug in the script execution environment. I have run and tested these contracts _extensively_ outside of Foundry, so I am quite sure that something is wrong.

**Thorough explanation.** I have not yet worked up a MWE; but this should give a lot of info for now.

I have a contract which—during its constructor—reads from a public state variable of another contract. The problematic reads are [here](https://github.com/firnprotocol/contracts/blob/master/src/TransferVerifier.sol#L36) and [here](https://github.com/firnprotocol/contracts/blob/master/src/WithdrawalVerifier.sol#L36).

upon starting `anvil` in one window and executing
```bash
forge script script/Firn.s.sol:FirnScript --fork-url http://localhost:8545 --broadcast
```
I get:
```bash
[⠒] Compiling...
No files changed, compilation skipped
Script ran successfully.

## Setting up 1 EVM.

Failed with `EvmError: Revert`:


Failed with `EvmError: Revert`:

  [3294] → new <unknown>@0x34A1D3fff3958843C43aD80F30b94c510645C316
    ├─ [0] InnerProductVerifier::gs(0) [staticcall]
    │   └─ ← [Stop] 
    └─ ← [Revert] EvmError: Revert

  [794] → new InnerProductVerifier@0x90193C961A926261B756D1E5bb255e67ff9498A1
    ├─ [0] InnerProductVerifier::gs(0) [staticcall]
    │   └─ ← [Stop] 
    └─ ← [Revert] EvmError: Revert

Error: 
Simulated execution failed.
```

you can see that the problematic line is reading from state of another contract.

If you add `vm.breakpoint("a");` between lines 24 and 25 of [the script](https://github.com/firnprotocol/contracts/blob/master/script/Firn.s.sol)—i.e., before the line `TransferVerifier transfer = new TransferVerifier(ip);`—run `forge debug ./script/Firn.s.sol`, and use `'a` to step past the first few constructors, then you can step into the problematic contract creation. it is clear that instead of failing on the first read of `_ip.gs(0)`, it chugs right past it with no problem.

happy to provide further info. many thanks in advance and apologies for the non-mwe. maybe there is a problem with simulating a read of a "tuple" (i.e., of a `bytes32[2]`).

### PR DESCRIPTION
**Pull request by klkvr**
## Motivation

Closes #8960

Right now, when simulating a script without providing a `--sender` arg, we will use the default sender both for script contract deployment and `setUp`/`run`. This will result in sender nonce being higher than an actual on-chain nonce. For certain scripts, this might result in mismatched addresses and failure during on-chain simulation, if incorrect addresses end up in calldata.

## Solution

Fix contains 2 parts:
1. Follow-up for https://github.com/foundry-rs/foundry/pull/7907 which enables nonce correction even when sender is default foundry sender. Unsure why this case was excluded earlier
2. Hack during script execution — if we're simulating with default sender, we'd set it's nonce to a hardcoded high value for script contract CREATE transaction. This allows us to reset nonce back to on-chain value when simulating the script, and ensure matching contract addresses during on-chain sumlation

### CODE REVIEW

**Comment by grandizzy** [comment]
Possibly fixing https://github.com/foundry-rs/foundry/issues/2002 too

**Comment by klkvr** [comment]
> Possibly fixing https://github.com/foundry-rs/foundry/issues/2002 too

I don't think so. This sounds like an issue with gas estimation on optimism? looks like people are getting around it by using `--with-gas-multiplier`

it could be addressed by enforcing `--slow` for optimism by default, like we do for arbitrum: https://github.com/foundry-rs/foundry/blob/8905af382e04b1bf3a492880abe5904a56e88491/crates/cli/src/utils/cmd.rs#L163

cc @mds1, assume you're running scripts on OP networks quite often and know about hacks that are required

**Comment by mds1** [comment]
> cc @mds1, assume you're running scripts on OP networks quite often and know about hacks that are required

Most scripts I run these days are actually on L1, so I don't have much insight unfortunately. I will see if someone else has more insight than I do here

**Review by grandizzy — APPROVED** [review]
makes sense, lgtm!

**Review by zerosnacks — APPROVED** [review]
Fix LGTM

Initially thought that setting the nonce to a constant `u64::MAX / 2` might result in duplicate nonces / replacement transactions but considering the state is committed directly and synchronously this should not be an issue

**Pull request merged**
