### PR TITLE
bug "fix":  temporarily disable docker build on release version

### PR DESCRIPTION
**Pull request by dmfxyz**
## Motivation
Docker build is currently failing.

After [64087b59c0ac9abb4b5e04d8c84e8bab47f4c6c3](https://github.com/foundry-rs/foundry/commit/64087b59c0ac9abb4b5e04d8c84e8bab47f4c6c3), the docker build has been failing at compiling `group v0.11.0` due to missing openssl-dependency. Adding this dependency solves that issue, but reveals another problem with compiling `foundry-cli`: 

```sh
#13 808.6    Compiling foundry-cli v0.2.0 (/opt/foundry/cli)
#13 809.7 error: failed to run custom build command for `foundry-cli v0.2.0 (/opt/foundry/cli)`
#13 809.7 
#13 809.7 Caused by:
#13 809.7   process didn't exit successfully: `/opt/foundry/target/release/build/foundry-cli-f3551be4cc3b0164/build-script-build` (signal: 11, SIGSEGV: invalid memory reference)
#13 809.7 warning: build failed, waiting for other jobs to finish...
```

Example job with openssl fixed but foundry-cli failing [here](https://github.com/dmfxyz/foundry/runs/6032143566?check_suite_focus=true).
This is definitely some alpine library related issue.

## Solution
Temporarily disable the docker build so that releases do not fail. Restore once fixed (should be able to take a look in a few days).
Bug opened here: https://github.com/foundry-rs/foundry/issues/1314

### CODE REVIEW

**Comment by dmfxyz** [comment]
@gakonst @onbjerg @mattsse FYI

**Review by mattsse — APPROVED** [review]
thank you

**Comment by gakonst** [comment]
@mattsse I now remember - this is why I was against libgit2, because it re-introduced OpenSSL..

**Comment by mattsse** [comment]
oh I think we can disable the ssh feature which should get rid of openssl by default

**Comment by dmfxyz** [comment]
That would at least solve the first issue, and hopefully the alpine `foundry-cli` compilation failure.

Opened this PR as a stop-gap to avoid GHA failures until we can take a closer look. Didn't want to be causing all those ❌. The prior images from before the org migration still work for those using them.

Alpine cuts our docker image size by more than half (last time I checked), but sadly comes with little bugs like this that would likely just "work" on other distros.

**Comment by gakonst** [comment]
let's give a try at removing openssl again, and if doesnt solve we can merge this

**Comment by dmfxyz** [comment]
Disabling libgit2 ssh appears to have [worked](https://github.com/dmfxyz/foundry/actions/runs/2173606376)! Will do some testing with the new image and then close this PR. Thanks @mattsse

**Comment by dmfxyz** [comment]
Confirmed resolved in my fork with #1316. Can someone kick off either a release or Docker Build job in the org repo?

**Comment by gakonst** [comment]
Just triggered!

**Comment by dmfxyz** [comment]
> Just triggered!

Success! I think the last thing needed package is set to public at the org level (github defaults to private).

**Comment by onbjerg** [comment]
Should be public now :smile:

**Pull request closed without merging**
