### PR TITLE
refactor(docker): bake && image fixup

### PR DESCRIPTION
**Pull request by sambacha**
add docker-bake config so buildx can be used natively

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
TIL https://docs.docker.com/engine/reference/commandline/buildx_bake/

I've never used it before, is it worth including a note in the readme section?

https://github.com/foundry-rs/foundry#installing-via-docker

**Comment by sambacha** [comment]
Yes, also would you want to add additional CPUs like ARM? 

[data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACwAAAAAAQABAAACAkQBADs=3D]

**Comment by mattsse** [comment]
that should be possible, and would make sense I think

**Comment by gakonst** [comment]
I think let's not package extra Docker utils

**Comment by sambacha** [comment]
> I think let's not package extra Docker utils

This is not extra docker utils, this enables docker's new buildx system that enables cross compilation to different archs. It also speeds up docker build times

**Pull request closed without merging**
