### PR TITLE
feat: filter non bug panic section

### LINKED ISSUE #2912: Bug: using negative integer in configuration makes `forge` panic
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b1f6a6c 2022-08-23T00:18:35.638369012Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

When running `forge test` with `FOUNDRY_FUZZ_RUNS=-1`, the program panics:

```text
foundry config error: invalid value signed int `-1`, expected u32 for key "FUZZ_RUNS" in `FOUNDRY_` environment variable(s)
The application panicked (crashed).
Message:  failed to extract foundry config
Location: config/src/lib.rs:434

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

This can be reproduced using the Docker container: `docker run --rm -it ghcr.io/foundry-rs/foundry:nightly 'FOUNDRY_FUZZ_RUNS=-1 forge test'`

The error is straightforward (using `-1` in `fuzz_runs` is not supported), but I find it strange to report this as a panic instead of only displaying the first line and exiting with an error. By looking at the code, it seems that `Config::from_provider(figment)` should be replaced by `Config::try_from(figment)` in https://github.com/foundry-rs/foundry/blob/f020b250d788255d49871a0c7a5e39d60fa55236/cli/src/cmd/utils.rs#L246-L249

By the way, I choose to report this issue because the error message said "This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry". Feel free to close it as "won't fix" if this behavior looks right to you.

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #2912

provides a way to inspect panic! messages and conditionally set the panic section with link to new issue

## Solution
* add panichook wrapper that inspects the payload and set the panic section conditionally whether the message is considered a bug or not

### CODE REVIEW

**Comment by onbjerg** [comment]
Any reason we can't just throw an error here? If an error is thrown then the bug section is not displayed

**Comment by mattsse** [comment]
> Any reason we can't just throw an error here? If an error is thrown then the bug section is not displayed

throwing where?

loading the Config with panic makes sense imo, since no way to recover anyways

> The reason I defaulted to adding the "This is a bug" thing on panic is to push us to use errors instead of panicking since a panic would lead users to report the messages (even if it wasn't really a bug - in which case, the panic itself is the bug).

but with the message for all panics we get issues like #2912 even if no bug

**Comment by onbjerg** [comment]
@mattsse Throwing an error when loading the config: imo it doesn't make sense to panic even though the error is not recoverable in the CLI. Panics should be reserved for when something is really wrong. Another way I could phrase it is: error if it's because of the user input, panic if it's because of developer error

>but with the message for all panics we get issues like https://github.com/foundry-rs/foundry/issues/2912 even if no bug

yea given above philosophy it makes sense since the panic itself is the bug imo. distinction is errors -> no stack trace, panics -> stack trace.

**Comment by mattsse** [comment]
closing as overengineered, not very useful after all

**Pull request closed without merging**
