### PR TITLE
fix(anvil): return time offset in `evm_increase_time`

### PR DESCRIPTION
**Pull request by DaniPopes**
## Motivation

Ganache's [`evm_increaseTime`](https://github.com/trufflesuite/ganache/blob/d48d998bd057a82b78c15ce197de06abc3487d2c/src/chains/ethereum/ethereum/RPC-METHODS.md#evm_increasetime) returns the time offset in seconds while Anvil's returns nothing, which leads to unexpected errors. Example: [eth-brownie/brownie](https://github.com/eth-brownie/brownie) uses it to track the time offset of the provider, but it raises an error when trying to parse the call's result since it is not a number:

https://github.com/eth-brownie/brownie/blob/4ae5f527ea86eb95766fe225a0f67620ffd36022/brownie/network/state.py#L375

## Solution

Return the input seconds in `EthApi::evm_increase_time`.

### CODE REVIEW

**Review by mattsse — CHANGES_REQUESTED** [review]
> Promise<number> : Returns the total time adjustment, in seconds.

this would mean it should return the accumulated offset, right?

which is tracked here:

https://github.com/foundry-rs/foundry/blob/4e11d1ff1d01cec67399cb7fdaaf7fa3cf467532/anvil/src/eth/backend/time.rs#L31-L33

so perhaps we simply return the total offset from `fn increase_time`?

**Comment by DaniPopes** [comment]
> so perhaps we simply return the total offset from fn increase_time?

Yep, had to make it public. Also switched to i128 because the time offset can be negative if set manually

**Review by mattsse — APPROVED** [review]
thanks, 

I think that's fine, alternatively, we could also return the new offset in `increase_time` directly

**Comment by DaniPopes** [comment]
Untitled

I believe this is due to the serde_json feature `arbitrary_precision` not being enabled

**Comment by mattsse** [comment]
could be a serialization error with the i128 type, downgrading to i64 should be fine

**Review by mattsse — APPROVED** [review]
lgtm

**Pull request merged**
