### PR TITLE
optimize debug node flatten_to method

### PR DESCRIPTION
**Pull request by MuhtasimTanmoy**
Context: https://github.com/foundry-rs/foundry/issues/7386

### CODE REVIEW

**Comment by DaniPopes** [comment]
I don't think this helps, the problem is the cloning in `flat` rather than the recursion itself,

**Comment by MuhtasimTanmoy** [comment]
Ok. Looking into it.

**Comment by onbjerg** [comment]
What's the status on this? @MuhtasimTanmoy

**Comment by DaniPopes** [comment]
This is not the right approach, and I've found another place to improve performance in https://github.com/foundry-rs/foundry/pull/7468. Thanks for the PR anyway!

**Pull request closed without merging**
