### PR TITLE
forge: fix Etherscan API key not being read from command line during script runs

### PR DESCRIPTION
**Pull request by theforager**
When using `forge script`, the command line option `--etherscan-api-key` isn't passed into the script run.

Validation appears to work correctly, so if `--verify` is passed the script will terminate if `--etherscan-api-key` isn't provided. However, after providing this key, it is ignored and results in verification silently not occurring.

Setting the `ETHERSCAN_API_KEY` does work properly as it's captured in the Figment creation process. 

## Motivation

Passing the Etherscan key via command line is a documented option and enables easier parameterization than solely allowing environment variables.

## Solution

I tried to mirror this off of the private key loading process that also loads from the parsed command line arguments. I'm not sure if there is a more idiomatic way (seems like it could go in the Figment creation), but I didn't see any other patterns.

### CODE REVIEW

**Review by gakonst — APPROVED** [review]
good catch - needs linting etc

**Comment by theforager** [comment]
Edits should pass linter now!

It's slightly out of sync with other parts of the file (e.g. `fn maybe_load_private_key`) but assume minimal edits is better.

**Comment by joshieDo** [comment]
Oops! Thanks!

Can you add that if there's no key and `--verify` is set, we throw error instead?

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
> Oops! Thanks!
> 
> Can you add that if there's no key and `--verify` is set, we throw error instead?

let's get this fixed and do this improvement in a followup

**Pull request merged**
