### PR TITLE
chore: use compat wording in out of gas error

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
ref https://github.com/foundry-rs/foundry/issues/4388

cc @PhilippLgh

use same wording as hardhat.

### CODE REVIEW

**Comment by PhilippLgh** [comment]
Looks good! Have you checked the other matchers in the file?
Like `"replacement transaction underpriced"`, `"nonce has already been used"`...
Might make sense to loop in ricmoo here to better understand how to arrive at a localisation friendly solution

**Comment by PhilippLgh** [comment]
Might be relevant: https://github.com/ethers-io/ethers.js/discussions/2849#discussioncomment-2468199

**Comment by PhilippLgh** [comment]
From my understanding after reading a bit about it renaming the messages is just fighting symptoms of the error missing a standard format with data field.
`{ code: -32603, message: 'EVM error OutOfGas' }`

**Comment by mattsse** [comment]
yeh this not ideal.

> { code: -32603, message: 'EVM error OutOfGas' }

what should we emit here?

**Comment by PhilippLgh** [comment]
Opened a ticket on ethers repo: https://github.com/ethers-io/ethers.js/issues/3801
Seems to be a classic case where communication is required to make up for missing standards. So ricmoo can probably shed some light about best practices and compatibility for the future.

**Comment by ricmoo** [comment]
Clients rewording error messages has certainly been a time sink. I would love a standard, and it should probable be at least a string prefix.

Even between versions of Geth, Parity, etc. and under different configuration the strings can vary. I’ve tried to coalesce them into errors in Ethers that have both a human-readable component and a machine-readable component.

I generally do this with a series of regular expressions (which can be complicated, since some backends decode the `Error(string)` for the user, allowing arbitrary string injection), which have to be updated periodically and with urgency, since clients generally don’t coordinate on string changes.

I recall once that Parity updated the “plural”-ness of some of their errors at one point, which broke everything on newer versions. Which is the next rub; it must still continue to work with the old Parity and new Parity, so you need to find the Karnaugh Map equivalent for regular expressions that works, without over matching. Fun times. :)

One thing I’ve found that does really help in your `checkError` function is to include the method that was called and the full error payload. The method really helps narrow down the possible set of types of errors and hopefully at some point, the error payload will include more “things”. :)

But it is currently a moving target. :)

**Comment by ricmoo** [comment]
FYI; here is the [current coalescence](https://github.com/ethers-io/ethers.js/blob/main/src.ts/providers/provider-jsonrpc.ts#L790) code. Suggestions welcome. ;)

**Review by gakonst — APPROVED** [review]

**Pull request merged**
