### PR TITLE
feat: project level inspection of errors, events and method_identifiers

### PR DESCRIPTION
**Pull request by meetmangukiya**
## Motivation

Wanting to inspect all events, errors, methods and grep over it at once. 

## Solution

Dummy object with aggregated data patched in

### CODE REVIEW

**Comment by onbjerg** [comment]
Could you expand a bit more on what this does? It would be helpful for for example documenting the feature later on

**Comment by meetmangukiya** [comment]
My own personal use case was in a project with lot of dependencies and contracts if you are trying to debug some error and you want to quickly see which contract given error is from you want to be able to grep that. Right now you have to guess which contract might have given error and then do `forge inspect Contract errors | grep <error id|error name>`, same for events, method ids, etc. This way you could just search all the methods, errors and events from all your contracts and all your dependencies too in single command.

**Comment by mds1** [comment]
So example usage is `forge inspect . errors` to list all errors from all projects? I don't think `.` is a good name because `.` refers to the current directory, but the current behavior is the same regardless of which project dir I execute the command from. Should either:
1. support a path argument as an alternate to the contract name, or
2. make the name argument optional if that's feasible without a breaking change.

My preference is option 1.

Also AFAICT the current approach means we lose information, and you can't print which contract(s) a given error/method/etc is from without further searching. Ideally, this would output a table with the file name and contract name for each item

**Comment by meetmangukiya** [comment]
there is `forge selectors` which lists all the selectors, but not across the dependencies, might pr to add an option that, closing this for now

**Pull request closed without merging**
