### PR TITLE
feat: support native dependencies

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
dependency management is currently done via git submodules: `forge install`

Instead of managing submodules, dependencies could also be managed via a foundry registry. and a `[dependencies]` table in `foundry.toml`

this has the advantage that dependencies don't need to be submodules anymore and can be reuused by multiple projects.

however this introduces some challenges:

### keep up to date

via submodules this is a simple update and a commit for the updated submodules. for native dependencies we can add `tag|rev` options to pin the specific commit.

### dependency conflict

what if there multiple versions of the same repository in the dependency graph. Currently this can only be handled via different remappings, otherwise, the top most submodule has precedence, see also #1855. in other build env this problem is handled via lock files. Unsure if beneficial here.

### tooling/auditing

tracking dependencies somewhere else (~/.foundry/registry) could mean that we need to add support for existing editors/lsp so they can be found in the editor.

maybe this makes auditing harder

This PR is merely an initial exploration effort, but imo it would be possible

todo:
- [ ] better git management, luckily `foundry_binder` already has some rudimentary support for this
- [ ] dependency graph support
- [ ] full `forge build` pipeline: resolve imports, checkout, build

### CODE REVIEW

**Comment by gakonst** [comment]
One thing is that people really like that you can grep through your deps when they're in submodules.

**Comment by onbjerg** [comment]
Would this not work with symlinks?

**Comment by onbjerg** [comment]
Another idea as well: since we would have better insight into dependencies/packages, for packages that support it we can generate more "sane" automatic remappings. For example, could provide a way to add package info about your project in `foundry.toml` (name, version, paths), so e.g. if OZ had a simple `foundry.toml` people could access it via `@openzeppelin` like for Hardhat

**Comment by gakonst** [comment]
doubt this will make it into 1.0 so closing to keep the PRs clean. we should revisit for 2.0

**Comment by mattsse** [comment]
+1
was just some weekend hacking, should followup on #2618 for this

**Pull request closed without merging**
