### PR TITLE
refactor(fmt): change default for `override_spacing` to `false`

### LINKED ISSUE #4025: feat(fmt): unified `override_spacing` option for functions and state variables
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a44159a 2023-01-03T00:04:41.810446Z)

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

Setting `fmt.variable_override_spacing` to `false` does nothing. Just try to use it on the following code:

```solidity
pragma solidity >=0.6.0 <0.9.0;

contract Base1 {
    function foo() public virtual { }
}

contract Base2 {
    function foo() public virtual { }
}

contract Inherited is Base1, Base2 {
    // Derives from multiple bases defining foo(), so we must explicitly override it
    function foo() public override (Base1, Base2) { }
}
```

It will keep the spacing between `override` and `(Base1`, and it will re-add it if you delete it yourself.

### PR DESCRIPTION
**Pull request by paulrberg**
## Motivation

[The Solidity documentation](https://docs.soliditylang.org/en/v0.8.17/contracts.html#function-overriding) uses no spacing between the `override` keyword and the overridden contract names:

```solidity
contract Inherited is Base1, Base2
{
    // Derives from multiple bases defining foo(), so we must explicitly
    // override it
    function foo() public override(Base1, Base2) {}
}
```

Anecdotally, most Solidity code bases I've seen adhere to the same pattern where there is no spacing. This is perhaps the same reason why @benesjan opened issue #3522 in the first place.

## Solution

Set the default value of `variable_override_spacing` to `false`.

Though, before this is merged in, we should fix #4025 first.

### CODE REVIEW

**Review by gakonst — APPROVED** [review]
sgtm - yeah good catch

**Comment by paulrberg** [comment]
> what happens when there's no override target?

I wanted to test this but unfortunately the newest [`override_spacing`](https://github.com/foundry-rs/foundry/pull/4031) doesn't work anymore - setting to `false` doesn't remove the spacing now. This started happening immediately after upgrading to the latest version of Forge:

```text
forge 0.2.0 (a44159a 2023-01-03T00:04:41.810446Z)
```

Cc-ing @rkrasiuk in case he can take a look?

**Comment by rkrasiuk** [comment]
@paulrberg ugh, must be some config issue, looking

**Comment by rkrasiuk** [comment]
@paulrberg the issue is unrelated, couple of latest releases failed
https://github.com/foundry-rs/foundry/actions/runs/3851356109

**Comment by paulrberg** [comment]
Thanks, Roman, I will wait for the fix and try test again with only one base contract inherited.

**Comment by rkrasiuk** [comment]
@paulrberg openssl got pulled into foundry again 😢 . we added a [fix](https://github.com/foundry-rs/foundry/pull/4046) and [CI check](https://github.com/foundry-rs/foundry/pull/4047) to prevent this from happening again. will re-release as soon as the fix is merged and ping you

**Comment by gakonst** [comment]
image

what do we think of this?

**Review by rkrasiuk — CHANGES_REQUESTED** [review]
@paulrberg there are some tests that need to be fixed to depict the changed default behavior. there are 3 `override-spacing.fmt.sol` files in [testdata](https://github.com/foundry-rs/foundry/tree/master/fmt/testdata). the easiest way forward is to rename these to `fmt.sol` files and remove `// config: override_spacing = false` line (since this is now the default). the original `fmt.sol` files should be renamed to `override-spacing.fmt.sol` and should include `// config: override_spacing = true` at the top

**Comment by rkrasiuk** [comment]
@paulrberg just checked, `override_spacing` option works on latest release 🫡

**Comment by paulrberg** [comment]
Thanks for the quick turnaround, @rkrasiuk! I can confirm that `override_spacing` works in the latest release.

Re tests - thanks for the guidance! I have updated them to match the new default.

**Review by rkrasiuk — APPROVED** [review]
lgtm, will merge after checks pass

**Comment by rkrasiuk** [comment]
@paulrberg seems like some other files with default behavior need to be fixed as well

**Comment by paulrberg** [comment]
@rkrasiuk I took a look at the CI logs but I don't know what to make out of them .. I don't understand what went wrong. Looks like the "<left>" formatting is the same as the "<right>"?

Screenshot 2023-01-07 at 3 38 05 PM

**Comment by rkrasiuk** [comment]
@paulrberg the CI logs do not show the space diff for some reason (see my response to @gakonst above). fixing the tests

**Comment by paulrberg** [comment]
Oh, I see. Sorry for the back-and-forth, and thanks for the fix.

**Pull request merged**
