### PR TITLE
perf(fuzz): use ahash for state

### PR DESCRIPTION
**Pull request by DaniPopes**
Plus some cleanups.

Note that collecting push bytes still accounts for ~40% of total invariant runtime. What about reducing the max analysis? I don't really know how to improve this further @grandizzy

### CODE REVIEW

**Comment by grandizzy** [comment]
> Note that collecting push bytes still accounts for ~40% of total invariant runtime. What about reducing the max analysis? I don't really know how to improve this further @grandizzy

I think that's fine as `include_push_bytes` is configurable, so one could have different profiles to test (with and without including it). We could set option default value to false though.

**Comment by DaniPopes** [comment]
Is it expected for tests to fail when changing the hasher?

**Comment by grandizzy** [comment]
> Is it expected for tests to fail with different runs when changing the hasher? https://github.com/foundry-rs/foundry/actions/runs/9369294111/job/25793469854?pr=8053#step:12:276

Don't think so, only if the order of insertion is not preserved, going to do a comparison to see what's different for this test with different hashers

**Comment by grandizzy** [comment]
@DaniPopes looks related to the changed way of selecting samples vs non persisting values here

https://github.com/foundry-rs/foundry/pull/8053/files#diff-d37d278bbc4bfc5240900ba4963f1a0f562f98808670ca692658aed9e0fdf624L131-R137

I'd suggest to keep it as it is for now and I'll follow up with a PR to change it, need to run some benchmarks on DSChief test to see if any impact, wdyt?

**Comment by grandizzy** [comment]
@DaniPopes I confirmed there's no impact in selecting samples / non persisting values the new way (needs https://github.com/foundry-rs/foundry/pull/8080 fix though), I pushed a fix for failing test, should be good to go. thank you!

**Review by grandizzy — APPROVED** [review]
lgtm!

**Review by mattsse — APPROVED** [review]

**Pull request merged**
