### PR TITLE
feat(invariant): collect logs & traces for last successful runs

### PR DESCRIPTION
**Pull request by shekhirin**
## Motivation

https://github.com/foundry-rs/foundry/issues/2962

### Cases

1. When invariant succeeds, we collect logs and traces from the last successful run
2. When invariant breaks, we replay the call to collect logs and traces from the last run that broke the invariant

### Demo
<details>
<summary>Code</summary>

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Test.sol";

contract NonceCounter {
  int256 public nonce = 1;

  function increment() public {
    nonce++;
  }
}

contract NonceCounterTest is Test {
  NonceCounter nonceCounter;
  int256 lastNonce;

  function setUp() public {
    nonceCounter = new NonceCounter();
  }

  function invariant_NonceGoUp() external {
    console2.log('lastNonce: ', vm.toString(lastNonce));

    int256 currentNonce = nonceCounter.nonce();
    console2.log('currentNonce: ', vm.toString(nonceCounter.nonce()));

    require(currentNonce > lastNonce, "Invariant violated: Nonce did not increase");
    lastNonce = currentNonce;
  }

  function invariant_NonceNotGoOver10() external {
    int256 currentNonce = nonceCounter.nonce();
    console2.log('currentNonce: ', vm.toString(nonceCounter.nonce()));

    require(currentNonce <= 10, "Invariant violated: Nonce went over 10");
  }
}
```
</details>

<details>
<summary>Before</summary>

```console
➜  invariant-bug git:(main) ✗ forge test -vvvv
[⠆] Compiling...
No files changed, compilation skipped

Running 2 tests for test/Counter.t.sol:NonceCounterTest
[PASS] invariant_NonceGoUp() (runs: 256, calls: 3835, reverts: 60)
[FAIL. Reason: Invariant violated: Nonce went over 10]
        [Sequence]
                sender=0x00000000000000000000000000000000000000e5 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x000000000000000000000000000000000000006d addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x00000000000000000000000000000000ba414fa6 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x96c1077fbd1eeaae1ce08f75352cb0b424d9b481 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x00000000000000000000000000000000000000ad addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x00000000000000000000000000000000f8ccbf47 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x00000000000000000000000000000000000006b3 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0xb568eabb1b0c6cfb2b32393b4aa98ca860b1b6bc addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x5c22070dafc36ad75f3dcf5e7237b22ade9aecc4 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x4defe99ade4fd21a9478cf81ef727aa847c0ab94 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]

 invariant_NonceNotGoOver10() (runs: 256, calls: 3835, reverts: 60)
Logs:
  currentNonce:  11

Traces:
  [118067] NonceCounterTest::setUp()
    ├─ [63599] → new NonceCounter@0xCe71065D4017F316EC606Fe4422e11eB2c47c246
    │   └─ ← 207 bytes of code
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [15130] NonceCounterTest::invariant_NonceNotGoOver10()
    ├─ [2261] NonceCounter::nonce() [staticcall]
    │   └─ ← 11
    ├─ [261] NonceCounter::nonce() [staticcall]
    │   └─ ← 11
    ├─ [0] VM::toString(11)
    │   └─ ← 0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000023131000000000000000000000000000000000000000000000000000000000000
    ├─ [0] console::log(currentNonce: , 11) [staticcall]
    │   └─ ← ()
    └─ ← "Invariant violated: Nonce went over 10"

Test result: FAILED. 1 passed; 1 failed; finished in 284.39ms

Failing tests:
Encountered 1 failing test in test/Counter.t.sol:NonceCounterTest
[FAIL. Reason: Invariant violated: Nonce went over 10]
        [Sequence]
                sender=0x00000000000000000000000000000000000000e5 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x000000000000000000000000000000000000006d addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x00000000000000000000000000000000ba414fa6 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x96c1077fbd1eeaae1ce08f75352cb0b424d9b481 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x00000000000000000000000000000000000000ad addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x00000000000000000000000000000000f8ccbf47 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x00000000000000000000000000000000000006b3 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0xb568eabb1b0c6cfb2b32393b4aa98ca860b1b6bc addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x5c22070dafc36ad75f3dcf5e7237b22ade9aecc4 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x4defe99ade4fd21a9478cf81ef727aa847c0ab94 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]

 invariant_NonceNotGoOver10() (runs: 256, calls: 3835, reverts: 60)

Encountered a total of 1 failing tests, 1 tests succeeded
```
</details>

<details>
<summary>After</summary>

```console
➜  invariant-bug git:(main) ✗ /Users/shekhirin/Projects/foundry/target/debug/forge test -vvvv
[⠒] Compiling...
No files changed, compilation skipped

Running 2 tests for test/Counter.t.sol:NonceCounterTest
[PASS] invariant_NonceGoUp() (runs: 256, calls: 3835, reverts: 67)
Logs:
  lastNonce:  0
  currentNonce:  14

Traces:
  [38977] NonceCounterTest::invariant_NonceGoUp()
    ├─ [0] VM::toString(0)
    │   └─ ← 0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000013000000000000000000000000000000000000000000000000000000000000000
    ├─ [0] console::log(lastNonce: , 0) [staticcall]
    │   └─ ← ()
    ├─ [2261] NonceCounter::nonce() [staticcall]
    │   └─ ← 14
    ├─ [261] NonceCounter::nonce() [staticcall]
    │   └─ ← 14
    ├─ [0] VM::toString(14)
    │   └─ ← 0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000023134000000000000000000000000000000000000000000000000000000000000
    ├─ [0] console::log(currentNonce: , 14) [staticcall]
    │   └─ ← ()
    └─ ← ()

[FAIL. Reason: Invariant violated: Nonce went over 10]
        [Sequence]
                sender=0x0000000000000000000000000000000000000364 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x6f6c617465643a204e6f6e63652077656e74206f addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x00000000000000000003630b9ba2737b731b29d1 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x000000006c63430008100033a264697066735822 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x0000000000000000000000000000000000000040 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x92c9eba133ae5dc4287850bcf804f2b03cd3d776 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x00000000000000000000000000000000000001a0 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x1a9c76fa0d7d6a7f68dc6c539d18f9276fce81b5 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x00000000000000000000000000000000000000dc addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]

 invariant_NonceNotGoOver10() (runs: 256, calls: 3835, reverts: 67)
Logs:
  currentNonce:  11

Traces:
  [118067] NonceCounterTest::setUp()
    ├─ [63599] → new NonceCounter@0xCe71065D4017F316EC606Fe4422e11eB2c47c246
    │   └─ ← 207 bytes of code
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [5242] NonceCounter::increment()
    └─ ← ()

  [15130] NonceCounterTest::invariant_NonceNotGoOver10()
    ├─ [2261] NonceCounter::nonce() [staticcall]
    │   └─ ← 11
    ├─ [261] NonceCounter::nonce() [staticcall]
    │   └─ ← 11
    ├─ [0] VM::toString(11)
    │   └─ ← 0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000023131000000000000000000000000000000000000000000000000000000000000
    ├─ [0] console::log(currentNonce: , 11) [staticcall]
    │   └─ ← ()
    └─ ← "Invariant violated: Nonce went over 10"

Test result: FAILED. 1 passed; 1 failed; finished in 6.01s

Failing tests:
Encountered 1 failing test in test/Counter.t.sol:NonceCounterTest
[FAIL. Reason: Invariant violated: Nonce went over 10]
        [Sequence]
                sender=0x0000000000000000000000000000000000000364 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x6f6c617465643a204e6f6e63652077656e74206f addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x00000000000000000003630b9ba2737b731b29d1 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x000000006c63430008100033a264697066735822 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x0000000000000000000000000000000000000040 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x92c9eba133ae5dc4287850bcf804f2b03cd3d776 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x00000000000000000000000000000000000001a0 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x1a9c76fa0d7d6a7f68dc6c539d18f9276fce81b5 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38 addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]
                sender=0x00000000000000000000000000000000000000dc addr=[test/Counter.t.sol:NonceCounter]0xce71065d4017f316ec606fe4422e11eb2c47c246 calldata=increment(), args=[]

 invariant_NonceNotGoOver10() (runs: 256, calls: 3835, reverts: 67)

Encountered a total of 1 failing tests, 1 tests succeeded
```
</details>

### CODE REVIEW

**Comment by mds1** [comment]
IIUC, I think always, contingent on verbosity setting if performance is a concern. 
- For passing tests: This is a new feature for a lot of people and I think being able to play around with console.logs and get some visibility into the internals that way would be helpful
- For failing tests: This helps gain visibility into the issues

**Comment by brockelmore** [comment]
just tested out this branch as master is broken as well. There is still a bug someplace with traces.

A lot of times I get *no* output even with -vvvv. Sometimes -vvvv and failing invariant test leads to printing of the Setup trace (i believe this happens when an invariant *immediately* fails).

Screen Shot 2022-10-05 at 5 25 41 PM


Screen Shot 2022-10-05 at 5 28 31 PM

**Review by mattsse — APPROVED** [review]
lgtm, good to merge.

the mentioned bug appears to be unrelated?

**Comment by shekhirin** [comment]
@mattsse not sure if that's even a bug though, but since it's reproducible on master too, it's seems to be unrelated yeah.

**Pull request merged**
