### PR TITLE
chore(deps): bump, unpatch Alloy

### PR DESCRIPTION
**Pull request by DaniPopes**
## Motivation

~~Blocked on https://github.com/bluealloy/revm/pull/880~~

### CODE REVIEW

**Review by Evalir — APPROVED** [review]

**Comment by mattsse** [comment]
@DaniPopes we probably want this included in the reth_freez branch of revm

**Comment by DaniPopes** [comment]
@mattsse do you mean I should use branch in https://github.com/bluealloy/revm/pull/875?

**Comment by mattsse** [comment]
yeah, we're currently on reth_freeze

https://github.com/paradigmxyz/reth/blob/337fb311eebdc2e31e7ed257d4cc655ec7c557f0/Cargo.toml#L138-L139

main has still some unstable new API changes (especially inspector) that we want to stabilize first

**Comment by DaniPopes** [comment]
I see, is it possible to cherry pick the alloy bump to that branch? cc @rakita

**Comment by mattsse** [comment]
yep, should be, this would also unblock ssz features that we wanted for some relay rpc-types

**Comment by rakita** [comment]
> I see, is it possible to cherry pick the alloy bump to that branch? cc @rakita

done: https://github.com/bluealloy/revm/pull/875

**Review by mattsse — APPROVED** [review]
lgtm, pending clippy

**Pull request merged**
