### PR TITLE
fix(fmt): yul misc

### PR DESCRIPTION
**Pull request by rkrasiuk**
## Motivation

addressing general Yul comments

### CODE REVIEW

**Comment by gakonst** [comment]
gm - what are we missing here?

**Comment by rkrasiuk** [comment]
@gakonst hey, we are missing the `swtich` indentation & string literal overrides for max line length. will address it today

**Review by mattsse — APPROVED** [review]
lgtm

**Comment by rkrasiuk** [comment]
had to restart non-forking it cause they hanged

**Pull request merged**
