### PR TITLE
feat(fmt): Add support for comments

### PR DESCRIPTION
**Pull request by jpopesculian**
## Motivation

`forge fmt` does not currently handle comments properly and deletes them

## Solution

Find comments appropriately between chunked output and format them correctly

### CODE REVIEW

**Comment by gakonst** [comment]
Can we maybe add some explanation on how this system works with the Chunks etc.?

**Comment by gakonst** [comment]
image

btw I ran it on [forge-std](https://github.com/foundry-rs/forge-std/) and seems to add an extra indent

**Comment by jpopesculian** [comment]
> In the interest of keeping this maintainable / easy to review + others to pick up/improve, can we maybe add some explanation on how this system works with the Chunks etc.?

**Comment by jpopesculian** [comment]
Yeah, I think low hanging fruit at the moment would be to fix postfix comment formatting with contract parts / blocks (the broken unit tests), and generally the statement indents as pictured above

**Comment by jpopesculian** [comment]
Also I wanted to add some thoughts on expression formatting. Ideally we would want to wrap statements nicely into lines if they overflow. I think what would be helpful is to preparse the operator expressions into a flattened list if they evaluate from left to right, something like

```rust
enum FlatExpression {
    Expression(Box<Expression>),
    BinaryOp(&str),
    Prefixed(&str, FlatExpression),
    Postfixed(FlatExpression, &str),
    Grouped(Vec<FlatExpression>), // requires paren
}
```

we can then better implement chunking with rules like

  - is unary op
  - expression/prefixed/postfix is followed by binary op

and we can then check to see if the expression is multiline or not and if necessary render the flat expression uniformly multiline / grouped

**Comment by jpopesculian** [comment]
The only problem would be that we would be then doing a kind of recursive multiline check, so it might be smart to add something similar to the `simulated` helper for checking if something is multiline which pops on some kind of `SingleLineFormatBuffer` which would basically just wrap a `FormatBuffer` and implements `write_str` by doing `FormatBuffer::write_str` and then checking if the buffer has a newline in it and throws an error. This way we can kind of short-circuit the execution and not have to write everything all the time when checking if something is multiline

**Comment by gakonst** [comment]
Agree with basically everything you wrote as a direction - great work overall @rkrasiuk @jpopesculian, we're getting there..

**Review by mattsse — COMMENTED** [review]
since this is reaching a fairly large size and is quite complex, we should also document all things and add some docs on how everything works

**Comment by gakonst** [comment]
Yep

**Comment by jpopesculian** [comment]
@gakonst @rkrasiuk the current TODO list off the top of my head. lemme know what you think

in this PR there are probably a couple things that make sense to include

- [ ] operator expressions (math, comparison, binary, etc)? should be finished today
- [ ] lots more tests for comments

for the next PRs, I think we just have to implement all the missing nodes. this list includes

- [ ] statements (each a little PR?)
    - [ ] `Statement::If`
    - [ ] `Statement::Args`
    - [ ] `Statement::Break` and `Statement::Continue` should include comment support via Loc
    - [ ] `Statement::Return`
    - [ ] `Statement::Revert`
    - [ ] `Statement::RevertNamedArgs`
    - [ ] `Statement::Emit`
    - [ ] `Statement::Try`

- [ ] expressions (each a little PR? maybe lump the Easy stuff?)
    - [ ] `Expression::ArraySubscript`
    - [ ] `Expression::ArraySlice`
    - [ ] `Expression::ArrayLiteral`
    - [ ] `Expression::FunctionCall`
    - [ ] `Expression::FunctionCallBlock`
    - [ ] `Expression::NamedFunctionCall`
    - [ ] `Expression::Ternary`
    - [ ] `Expression::List`
    - [ ] Easy stuff
        - [ ] `Expression::Unit`
        - [ ] `Expression::This`
        - [ ] `Expression::Variable`
        - [ ] `Expression::Type`
        - [ ] `Expression::BoolLiteral`
        - [ ] `Expression::NumberLiteral`
        - [ ] `Expression::HexNumberLiteral`
        - [ ] `Expression::RationalNumberLiteral`
        - [ ] `Expression::StringLiteral`
        - [ ] `Expression::HexLiteral`
        - [ ] `Expression::AddressLiteral`

at then end Yul support?

**Comment by gakonst** [comment]
@jpopesculian do you think we could instead:
1. fix all failing unit tests (think there's some issue with postfix comments per @rkrasiuk)
2. add docs on _how_ this works (i love the work here but am unable to follow why this is correct :D, think @mattsse had a similar thought)
3. merge the PR
4. add operator expressions and everything else in a follow up?

PR is already 2.5k lines and feels like there's a lot already :P

**Review by gakonst — APPROVED** [review]
Alright - cautiously merging, have tested myself on a few repos and it's now 1) idempotent, 2) does not omit any comments, 3) works well enough in terms of fixing weirdly formatted stuff, 4) is -instant-

Let's iterate in follow up PRs:
1. the missing nodes as written above
2. foundry.toml config options (and maybe in-line options either at the top of the file or on a per-line basis)
3. default formatting which makes the maintainers of some popular projects happy (e.g. OZ / Solmate etc.)
4. docs on _how_ this works. we'll need to onboard more ppl over time and it'd be best if we have more ppl that understand how this works at a low level (i dont know anything about parsers)

Sick work guys - this has been a beast PR / enormous amount of work.

**Pull request merged**
