### PR TITLE
fix(foundryup): actually make `set -e` work

### LINKED ISSUE #6329: `foundryup` does not properly exit on errors in piped commands
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8c11482 2023-11-16T00:32:37.968294000Z)

### What command(s) is the bug in?

foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

Since piped commands run in a subshell, when we have something like `ensure download "$BIN_ARCHIVE_URL" | ensure tar -xzC "$FOUNDRY_BIN_DIR"`, `foundryup` will not properly exit if `tar` fails.

Steps to reproduce:
`foundryup -v abc`

Output:
```
foundryup: installing foundry (version abc, tag abc)
foundryup: downloading latest forge, cast, anvil, and chisel
############################################################################################################################################################################################################################################## 100.0%
tar: Error opening archive: Unrecognized archive format
foundryup: command failed: tar -xzC <redacted>/.foundry/bin
foundryup: downloading manpages
############################################################################################################################################################################################################################################## 100.0%
tar: Error opening archive: Unrecognized archive format
foundryup: installed - forge 0.2.0 (8c11482 2023-11-16T00:32:37.968294000Z)
foundryup: installed - cast 0.2.0 (8c11482 2023-11-16T00:32:38.016628000Z)
foundryup: installed - anvil 0.2.0 (8c11482 2023-11-16T00:32:37.882016000Z)
foundryup: installed - chisel 0.2.0 (8c11482 2023-11-16T00:32:37.924862000Z)
foundryup: done!
```

Explanation:
When `curl`ing a file that doesn't exist, `curl` seems to exit with code 0 when piping that output, and since the piped output 
to `tar` runs in a subshell, it doesn't exit the script.

### PR DESCRIPTION
**Pull request by DaniPopes**
## Motivation
Fixes #6329

TIL that using `||` on a function disables the global `set -e` for the function. lol.

5:18
https://youtu.be/30YWsGDr8mA?si=FfN-Fdbadxu_yJnZ&t=318

### CODE REVIEW

**Review by Evalir — APPROVED** [review]
Oh wow, TIL!

**Comment by warrickwicket** [comment]
This is a breaking change. `foundryup` now returns 1 if `FOUNDRY_BIN_DIR` is not in the PATH, which is not unreasonable for CI setups. I think it might make sense to relax this requirement.

**Comment by DaniPopes** [comment]
How would foundryup fail if `FOUNDRY_BIN_DIR` is not in `PATH`?

**Comment by imulmat4** [comment]
Any chance we could revert this change? Not sure this exit is giving a ton of value.

**Pull request merged**
