### PR TITLE
feat(`cheatcodes`): mark rpc + eth_getLogs cheatcodes as script safe

### PR DESCRIPTION
**Pull request by Evalir**

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
what does Safe/Unsafe mean hear?

**Comment by Evalir** [comment]
Safe/Unsafe refer to script safety or unsafety—cheatcodes unsafe to use in scripts are marked as such

**Review by mattsse — APPROVED** [review]
lgtm, pending @DaniPopes

**Comment by mds1** [comment]
Certain fork cheats like `createSelectFork` and `selectFork` can also be marked as safe even though their currently unsafe (but some like `rollFork` or `transact` should stay unsafe). I'm ok doing this here or in a follow up PR—more broadly we may want to just take a pass at the safety status and make sure everything looks good, in which case a follow up PR might be a better fit

**Review by DaniPopes — APPROVED** [review]

**Pull request merged**
