### PR TITLE
chore: use revm head

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
check https://github.com/bluealloy/revm/pull/126 works as expected

### CODE REVIEW

**Comment by onbjerg** [comment]
Should close #1894 if it works, correct?

**Comment by mattsse** [comment]
correct, but there's a new issue since that change: https://github.com/bluealloy/revm/pull/132

**Comment by onbjerg** [comment]
@mattsse Bumped to REVM 1.6.0 and attempted to fix the errors. The clippy lints are fixed in #2198

**Comment by mattsse** [comment]
cc @meetmangukiya any update on the revm migration?

**Comment by onbjerg** [comment]
I broked it

**Comment by onbjerg** [comment]
Something is borked with storage, not sure if it's upstream or here, I don't see any glaring issues

**Comment by meetmangukiya** [comment]
The recent PR https://github.com/bluealloy/revm/pull/145 should help with setting account state I think?

**Comment by onbjerg** [comment]
Current status: can't use the latest REVM (from git) because k256 version conflicts with what the rest of our codebase uses (0.11 in revm, 0.10 in ethers-rs & co)

**Comment by mattsse** [comment]
needs a patched revm, since this PR is not published yet https://github.com/bluealloy/revm/pull/144

**Comment by clifton** [comment]
🙏

**Review by gakonst — APPROVED** [review]

**Pull request merged**
