### PR TITLE
fix(forge debug): dunce canonicalize provided path

### LINKED ISSUE #9136: bug(`debugger`): `forge debug` uses backslash in path when compiling on Windows
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (adb6aba 2024-10-17T00:23:10.989722000Z)

### What command(s) is the bug in?

forge debug Contract.sol

### Operating System

Windows

### Describe the bug

When using debug on windows, `forge debug` uses a backslash to connect the absolute path, and the relative path to the file being compiled, causing the path to be malformed.

<REPO_PATH> and <RELATIVE_PATH> are substituted for the literal paths in this error.

`2024-10-17T17:32:41.843446Z ERROR foundry_compilers_artifacts_solc::sources: error="C:/<REPO_PATH>\<RELATIVE_PATH_>/Contract.sol": The system cannot find the file specified. (os error 2)
Error: failed to read artifact source file for <REPO_PATH>\<RELATIVE_PATH_>/Contract.sol`

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
Closes #9136 
Also outputs proper file does not exist err message

### CODE REVIEW

**Review by klkvr — COMMENTED** [review]
we already do this here https://github.com/foundry-rs/foundry/blob/97be9b9a2e128633b17589cd58bfde4b4d544e23/crates/script/src/build.rs#L172

looks like the error is coming from here https://github.com/foundry-rs/foundry/blob/97be9b9a2e128633b17589cd58bfde4b4d544e23/crates/evm/traces/src/debug/sources.rs#L188

I think it likely needs to be fixed on compilers side. Here we need to also normalize paths in `build_infos`: https://github.com/foundry-rs/compilers/blob/21617d05ae9bab42a509c8c2021977d31b93809a/crates/compilers/src/compile/output/mod.rs#L535

**Comment by grandizzy** [comment]
> we already do this here

I see, was thinking that since this comes from `ValueHint::FilePath` we might want to apply early, same as we do here

https://github.com/foundry-rs/foundry/blob/97be9b9a2e128633b17589cd58bfde4b4d544e23/crates/forge/bin/cmd/eip712.rs#L33

**Comment by klkvr** [comment]
> > we already do this here
> 
> I see, was thinking that since this comes from `ValueHint::FilePath` we might want to apply early, same as we do here
> 
> https://github.com/foundry-rs/foundry/blob/97be9b9a2e128633b17589cd58bfde4b4d544e23/crates/forge/bin/cmd/eip712.rs#L33

value hint doesn't affect the input values and eip712 has different flow and doesn't reach the script specific compilation logic which I've linked

**Comment by grandizzy** [comment]
Closing per comments above, will fix in compilers

**Pull request closed without merging**
