### PR TITLE
fix(`abi`): sanitize function args to avoid passing in prefixed empty bytes

### LINKED ISSUE #6211: Unable to encode empty bytes ("0x")
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1c7bf46 2023-11-03T13:18:06.065760000Z)

### What command(s) is the bug in?

cast calldata, cast abi-encode, cast send

### Operating System

macOS (Apple Silicon)

### Describe the bug

Possible regression, worked well before I updated yesterday using `foundryup`.

```
$ cast calldata "foo(bytes memory)" "0x"
Error: 
parser error:
0x
   ^


Context:
- parser error:
0x
   ^
```

### PR DESCRIPTION
**Pull request by Evalir**
Fixes #6211. Maybe we want alloy to support this?

### CODE REVIEW

**Comment by DaniPopes** [comment]
0x is [], 0x00 is [0]

**Comment by DaniPopes** [comment]
> Maybe we want alloy to support this?

It's a bug. I'll fix it

**Comment by Evalir** [comment]
ah kk @DaniPopes — can close this then right? and just bump on fix

**Comment by DaniPopes** [comment]
Yes

**Pull request closed without merging**
