### PR TITLE
fix(forge): improve fuzzing error message for assume rejections

### PR DESCRIPTION
**Pull request by 0xYYY**
## Motivation
https://github.com/foundry-rs/foundry/issues/1202

## Solution

Show fuzzing run stats including rejection reason counts.

### Example
`Fuzz.t.sol`:
```solidity
pragma solidity 0.8.10;

import "forge-std/Test.sol";

contract ContractTest is Test {
    function setUp() public {
    }

    function testFuzzAssume(uint256 a) external {
        vm.assume(a % 2 == 0);
        require(a % 2 == 0);
    }
}
```
`fuzz.max_global_rejects = 16` in `foundry.toml`

#### Before

Screenshot 2022-09-08 at 01 11 00

#### After

Screenshot 2022-09-08 at 01 12 31

### CODE REVIEW

**Comment by mds1** [comment]
Ah nice, I like this. Mixed feelings though since it's a bit confusing given that its called "global rejects" even though from a user-standpoint the rejections are local to a single test. I'm wondering if we should implement the rest of #1202 (remove local rejects from config and rename `max-global-rejects` to just `max-rejects`), then modify the formatting a bit to something like this:

```
[FAIL. Reason: Too many rejects in vm.assume]
Fuzz run stats:
  successes: 12
  rejections: 16
```

**Comment by onbjerg** [comment]
@mds1 Briefly mentioned this formatting in a PR earlier today that improved some error message handling internally in Forge for cheatcodes, really want to get a custom error type added that can handle "hints" as well (like in your example), which would also be useful for `expectEmit`, as well as allowing us to write more "long form" explanations

Not sure how I feel about this PR - it breaks with the formatting we use now and tbh I'd rather wait a bit for better error messages or implement that first

**Comment by gakonst** [comment]
agree not a fan of the formatting here, but useful overall. vote close and we revisit later once our error logging is better?

**Comment by 0xYYY** [comment]
Thanks a lot for the feedbacks! I'll redo to formatting of the error message and also add the parts for renaming the config parameter name mentioned in the original issue. In the mean time, i'll move this PR to draft.

**Pull request closed without merging**
