### PR TITLE
perf: simplify diff_score

### PR DESCRIPTION
**Pull request by DaniPopes**
We don't have to compare bytecodes of different length as all constructor args are the same for the same contracts, we just have to filter out different constructor args.

This improves testing for sablier-v2 in debug mode from 2:30m to 40s.

This doesn't do much outside of debug mode because this function gets optimized very well so calls to it become insignificant, and also it mostly runs on the main thread in parallel to other tests running.

### CODE REVIEW

**Review by mattsse — APPROVED** [review]

**Comment by mds1** [comment]
> We don't have to compare bytecodes of different length as all constructor args are the same for the same contracts, we just have to filter out different constructor args.

This heuristic will often work, but fails for contracts that append arbitrary data to their runtime code though which can affect length. For example [clones with immutable args](https://github.com/Saw-mon-and-Natalie/clones-with-immutable-args) deploys minimal proxies but stores "immutables" at the end of the proxy runtime code and passes them via extra calldata. And because of the way these immutables work they can be e.g. arrays of varying length, so different proxies can have different code length

**Comment by klkvr** [comment]
ah, I haven't noticed that PR before opening #7105 

> This heuristic will often work, but fails for contracts that append arbitrary data to their runtime code though which can affect length. For example [clones with immutable args](https://github.com/Saw-mon-and-Natalie/clones-with-immutable-args)

@mds1 CWIA appends immutable args to the minimal proxy which is basically a set of opcodes looking like this: `0x363d3d373d3d3d3d610042806035363936013d73284ac791c28c0576e31439c17ff143147fb3c6dc5af43d3d93803e603357fd5bf3010000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000100042` 

Because of that we can't identify them in traces (because they don't match any artifact), for example, optimism explicitly labels CWIA proxies https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/test/dispute/FaultDisputeGame.t.sol#L78

however, I am not sure how safe it is to completely ignore all artifacts with different length, wouldn't it cause problems when identifying contracts with appended metadata hash?

**Comment by mds1** [comment]
The metadata hash is also present in the artifact bytecode when that setting is enabled. Check out https://playground.sourcify.dev/ which is a great resource here

**Comment by klkvr** [comment]
> The metadata hash is also present in the artifact bytecode when that setting is enabled

right, I was thinking about a use-case when we are identifying contract from fork, but this is probably fine as we can fallback to etherscan data in that case

**Comment by DaniPopes** [comment]
Superseded by https://github.com/foundry-rs/foundry/pull/7108

**Pull request closed without merging**
