### PR TITLE
feat(forge): shallow clones

### LINKED ISSUE #5095: Speedup forge install with git shallow clone
### Component

Forge

### Describe the feature you would like

Right now, it appears that `forge install` clones the entire history of the git submodules.

But what we actually need is just the latest commit or a particular commit.

If possible, we can make it clone only the relevant commit. 

https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

Of course, we will still need to clone all the dependencies recursively.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DaniPopes**
## Motivation

Closes #5095

Best reviewed with whitespace disabled in github viewer

## Solution

- Refactor git commands in foundry-cli (see `Git` struct)
- Add `--depth=1` to clone and submodule commands
  - note that this is technically breaking, since tags are fetched at the given depth, so now the default behaviour won't automatically switch to the latest tagged version branch unless `--deep` is specified
- clone commands (which are likely to "hang") now print git progress by default, silenced by `--quiet`

TODO: `--deep` with shallow by default, or viceversa? cc @mattsse @Evalir

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
this sounds great,

I'm a bit hesitant though, because every time we touch this something breaks

but I'm okay with adding this

**Review by Evalir — APPROVED** [review]
Clean as always. I haven't QA'd enough yet for merge—I'd like to hold on for a little bit @mattsse to have some time to test this against usual edge cases.

**Review by mattsse — CHANGES_REQUESTED** [review]
there are lots of unrelated changes?
I would like to keep this PR minimal in case we need to revert

**Comment by Evalir** [comment]
@mattsse the unrelated changes seem to be ABI code—for some reason the autogenerated code is no longer marked as ignore by rustfmt?

**Comment by DaniPopes** [comment]
oh idk what happened there, sorry

**Comment by DaniPopes** [comment]
> I'm a bit hesitant though, because every time we touch this something breaks
> 
> but I'm okay with adding this

I've refactored error handling and made all executed commands get logged. Should be much easier to debug any future issues

> @mattsse the unrelated changes seem to be ABI code—for some reason the autogenerated code is no longer marked as ignore by rustfmt?

It's gakonst/ethers-rs#2482

**Review by mattsse — APPROVED** [review]
let's try this!

ty @DaniPopes !

**Review by Evalir — APPROVED** [review]
lets send it!

**Comment by llllvvuu** [comment]
BTW you can config it to also affect future installs/updates:

https://stackoverflow.com/a/38895397/5938726

**Pull request merged**
