### PR TITLE
fix(forge/test): issue error when no tests match

### PR DESCRIPTION
**Pull request by 0xYYY**
## Motivation

Closes https://github.com/foundry-rs/foundry/issues/1420

## Solution

Check the number of filtered tests before running.

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
looking good, 
any chance we can integrate `suggestions` here:

https://github.com/foundry-rs/foundry/blob/d18e55e84e5674b60a7e6afa5b74b7e14d0844bc/cli/src/suggestions.rs

**Comment by 0xYYY** [comment]
perhaps we can filter functions with pattern `test*` and provide those as candidates?

**Comment by mattsse** [comment]
great idea!

**Comment by 0xYYY** [comment]
This will list all tests under the supplied path/contract and get a suggestion form it. Let me know what you think.
(Will squash the commits when ready to merge.)

**Comment by ChiTimesChi** [comment]
@0xYYY @mattsse 
Would be nice to have an option to ignore this check. My usecase is having a lot of tests in forked environment, so I have one common big-ass script for running tests in environment based by their contract name (used both for local testing, and in the CI):
```bash
# Test contracts ending with exactly "Test" don't require any forking
forge test --match-contract "$1.*Test$" -vvv || exit 1
# Test contracts ending with exactly "TestAvax" require Avalanche RPC and block number: 2022-04-25
forge test --match-contract "$1.*TestAvax$" --fork-url $AVAX_API --fork-block-number 13897000 -vvv || exit 1
# Test contracts ending with exactly "TestEth" require Ethereum RPC and block number: 2022-04-24
forge test --match-contract "$1.*TestEth$" --fork-url $ALCHEMY_API --fork-block-number 14650000 -vvv || exit 1
# More like this below
```
Post-update this script fails if there are no contracts matching the filter.

**Comment by mattsse** [comment]
I see, 
hmm now I wonder if this is indeed too permissive.

Perhaps a middle ground is, 
we silently exit if the glob contains wildcard and fail if exact name was set?

can we move this to a new issue to discuss this further?

**Comment by ChiTimesChi** [comment]
> I see, hmm now I wonder if this is indeed too permissive.
> 
> Perhaps a middle ground is, we silently exit if the glob contains wildcard and fail if exact name was set?
> 
> can we move this to a new issue to discuss this further?

Opened an issue here:
https://github.com/foundry-rs/foundry/issues/1575

**Pull request merged**
