### PR TITLE
feat(script): add --unlocked flag

### LINKED ISSUE #3609: Support --unlocked in forge script
### Component

Forge

### Describe the feature you would like

Same as `forge create --unlocked`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #3609 

adds `--unlocked` flag for `forge script` for sending via `eth_sendTransaction`

@mds1 could you please try this

### CODE REVIEW

**Review by mds1 — APPROVED** [review]
Tested locally, works exactly as expected. Thanks!

**Review by rkrasiuk — APPROVED** [review]

**Comment by m-waqas88** [comment]
> Tested locally, works exactly as expected. Thanks!

@mds1 What am I doing wrong here?

My locally running node is a fork of mainnet.

`cast balance 0xf56EA77d821b0845D1bd634f52F4739257191856 --rpc-url http://localhost:8545`
23535271522980

`forge script script/WyScript.s.sol:WyScript --rpc-url http://127.0.0.1:8545 --via-ir --broadcast --unlocked 0xf56EA77d821b0845D1bd634f52F4739257191856`

Error
```bash
Error: 
Failed to send transaction

Context:
- server returned an error response: error code -32602: No Signer available
```

Script.sol
```solidity
function run() public {
        vm.startBroadcast(0xf56EA77d821b0845D1bd634f52F4739257191856);
        _deployWellUpgradeable();
        vm.stopBroadcast();
    }
```

**Comment by mds1** [comment]
@m-waqas88 What is your foundry version? Please open a new issue with that info + steps to reproduce :)

**Comment by m-waqas88** [comment]
> @m-waqas88 What is your foundry version? Please open a new issue with that info + steps to reproduce :)

Done.

**Pull request merged**
