### PR TITLE
fix: smarter `getCode` validation

### PR DESCRIPTION
**Pull request by klkvr**
## Motivation

One more fix after #7334 

If we've found multiple matching artifacts for `vm.getCode` and exactly one of them matches version of the currently running test/script source, return that.

Ref https://t.me/foundry_support/52016

## Solution

This changes test runner flow a bit so we now create executor for each `ContractRunner` to alter cheatcodes config with running contract version

### CODE REVIEW

**Review by mattsse — CHANGES_REQUESTED** [review]
I see, this check makes sense to me,

can we add a test for this as well?

**Comment by klkvr** [comment]
@mattsse created a separate profile for tests in multi-version environment

**Comment by klkvr** [comment]
As we're already here, also added more input options for `getCode`/`getDeployedCode` cheats. It now can parse all of those formats:
```
vm.getCode("Counter.sol");
vm.getCode("Counter");
vm.getCode("Counter:0.X.X");
vm.getCode("Counter.sol:0.X.X");
vm.getCode("Counter.sol:Counter:0.X.X")`
```

**Review by DaniPopes — APPROVED** [review]
lgtm

**Pull request merged**
