### PR TITLE
feat: add serde feature flag to anvil-core

### LINKED ISSUE #3602: feature flags for serde & rlp in anvil-core
### Component

Anvil

### Describe the feature you would like

Anvil core provides a lot of useful types that could benefit the larger Eth Rust ecosystem. To make it easier to use the create, it would be beneficial if the crate had feature flags to limit trait implementations.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Wodann**
Resolves #3602 

To Do:

- [ ] feature flag for `rlp`

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
I can see how this can be beneficial.

lgtm.

**Comment by mattsse** [comment]
made serde the default feature

**Comment by mattsse** [comment]
I'm merging this as is, feel free to open another one that does the same for rlp.

**Comment by Wodann** [comment]
Thanks for merging. W.r.t.

> made serde the default feature

Something to note when choosing your default features:

> Note: Be careful about choosing the default feature set. The default features are a convenience that make it easier to use a package without forcing the user to carefully select which features to enable for common use, but there are some drawbacks. Dependencies automatically enable default features unless default-features = false is specified. This can make it difficult to ensure that the default features are not enabled, especially for a dependency that appears multiple times in the dependency graph. Every package must ensure that default-features = false is specified to avoid enabling them.

    Another issue is that it can be a [SemVer incompatible change](https://doc.rust-lang.org/cargo/reference/features.html#semver-compatibility) to remove a feature from the default set, so you should be confident that you will keep those features.
    
Quoted from: https://doc.rust-lang.org/cargo/reference/features.html

That's why usually crates leave out serde from the default features and let people opt in to them instead.

**Comment by mattsse** [comment]
given that this is primarily used by anvil which requires it, opt-out is appropriate here imo

**Pull request merged**
