### PR TITLE
feat: add config for empty modifier format

### LINKED ISSUE #5633: `forge fmt` formatting with `Modifier-style base constructor call without arguments` compiler error
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dffdfde 2023-08-14T00:22:15.788827000Z)

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

```solidity
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {ERC1155} from "solmate/tokens/ERC1155.sol";

import {IAchievements} from "./interfaces/IAchievements.sol";
import {SoulBound1155} from "./abstracts/SoulBound1155.sol";

contract Achievements is IAchievements, SoulBound1155, Ownable {
    constructor(address owner) Ownable() ERC1155() {}
}
```

While formatting this piece of code with `forge fmt`, it removes parentheses for `ERC1155` inline derived constructor call. Then, the compiler gives such an error on `forge build`:
```
vladikopl@Vladichek-Air core % forge build
[⠊] Compiling...
[⠢] Compiling 1 files with 0.8.20
[⠆] Solc 0.8.20 finished in 18.36ms
Error: 
Compiler run failed:
Error (1563): Modifier-style base constructor call without arguments.
  --> contracts/Achievements.sol:17:42:
   |
17 |     constructor(address owner) Ownable() ERC1155 {}
   |                                          ^^^^^^^
``` 

May it be caused by `SoulBound1155` contract as it is already derived from `ERC1155`? Anyways, I think formatter should recognise it, and not change `ERC1155()` to `ERC1155`

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #5633

adds a new fmt config value: `empty_function_modifier_calls = "always"` to keep modifier `()`

FYI @vladikopl01

### CODE REVIEW

**Comment by Evalir** [comment]
Right, I mean this should *not* be performed on constructor functions—they should always have parenthesis e.g

This is correct:
```solidity
contract Achievements {
    constructor(address owner) Ownable() ERC1155() {}
}
```

This is incorrect:
```solidity
contract Achievements {
    constructor(address owner) Ownable ERC1155 {}
}
````

See https://github.com/ethereum/solidity/pull/3853 — the solidity compiler will warn you about this

**Comment by mattsse** [comment]
so we don't need the config at all but must check for constructor name instead?

**Comment by Evalir** [comment]
yep, ideally we'd not format these constructor functions _at all_ and leave them up to the user to make them compile

**Comment by mattsse** [comment]
simplified, please take over @Evalir

**Pull request closed without merging**
