### PR TITLE
fix: toString() print address with checksum

### LINKED ISSUE #2183: feat: `vm.toString(address)` should return a checksum address
### Component

Forge

### Describe the feature you would like

The cheatcode `function toString(address) external returns (string memory);` returns the address as all lowercase. Related to the effort in https://github.com/foundry-rs/foundry/issues/2071 to default to checksum addresses, this cheatcode should also return a checksum address.

cc @odyslam 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by odyslam**
fixes #2183

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
nice

**Comment by gakonst** [comment]
one more @odyslam (maybe worth running the tests locally & wait for them to pass before pushing :D)

> running 1 test
> test fmt::tests::can_pretty_print_optimism_tx ... FAILED

**Comment by odyslam** [comment]
Hm, i did run locally. Weird 🤨

**Comment by odyslam** [comment]
So interestingly, `cargo test` did not run that particular test. I had to run `cargo nextest run` in order to see it.

**Review by onbjerg — APPROVED** [review]

**Pull request merged**
