### PR TITLE
feat(forge): rememberKey cheatcode

### PR DESCRIPTION
**Pull request by devanonon**
## Motivation

As originally intended along with #2299, finally adding an implementation for a `remember` cheatcode which allows one to add private keys to the local forge wallet inside of a script.

This allows scripts to become more declarative so it is no longer needed to load a wallet in via the CLI.

I think getting script invocations down to just `forge script Script` while still supporting all features is a massive dev ex boost.

## Solution

A `script_wallets` variable / parameter is basically sprinkled around the entire `script` module. These wallets are collected in the `Cheatcode` `state` via the `remember` cheatcode and passed all the way to `MultiWallet` where they are matched with required address from the script.

### Note

Will add PRs to [book](https://github.com/foundry-rs/book) and [forge-std ](https://github.com/foundry-rs/forge-std) once this is accepted.

### CODE REVIEW

**Comment by mattsse** [comment]
@mds1 wdyt?

**Comment by mds1** [comment]
IIUC the final UX of scripting from this + #2299 would be something like this:

```solidity
uint256 deployerPrivateKey = vm.deriveKey(vm.envString("MNEMONIC"), 0);
address deployer = vm.remember(deployerPrivateKey);

uint256 governancePrivateKey = vm.deriveKey(vm.envString("MNEMONIC"), 1);
address governance = vm.remember(governancePrivateKey);

vm.broadcast(deployer);
Contract contract = new Contract(governance);

vm.broadcast(governance);
contract.addPair(vm.envString("PAIR"));
```

That seems reasonable. FWIW personally I never use mnemonics for deployer accounts and typically use dedicated private keys which I'd argue is best practice / simpler / less error-prone. But if people do want to use mnemonics (and we already have `deriveKey`) it seems ok to support it.

What's the use case for separate `derive` and `remember` cheats? Should those be combined into a single cheat? The only use case I can think of is needing to `vm.sign` something from the deployer, which does seem like something that would be nice to support. So that means options are:
- Merge them, and have the cheatcode return address and private key
- Keep them separate, and consider a forge-std heplper that combines them

An alternative approach which I think prefer: keep `deriveKey`, delete `remember`, and add broadcast overloads that just directly take a private key. This is simpler UX as it removes a cheatcode, and being able to pass a private key to `broadcast` seems logical.

If we keep `remember`, we should also consider a clearer name like `rememberKey` to mirror `deriveKey`

**Comment by devanonon** [comment]
Thanks for the feedback @mds1!

Regarding using mnemonics over private keys, I have two points on this.
1. it's very helpful in a set of smart contracts with multiple actors. The example that spurred this was Lens Protocol which, when deploying locally, uses the address at index 0 for the deployer and address at index 0 for governance. This means we can then do full e2e testing on the UI by simply importing the mnemonic into MM. Of course we could import two private keys, but I prefer to have a separate browser profile with a test mnemonic loaded so I can a) test quickly and b) keep test private keys separate from anything remotely production.

2. is to simply achieve feature parity with Hardhat. Many Hardhat deploy scripts contain a line like: `const [deployer, someOtherUser] = ethers.getSigners();` which providers multiple signers from the supplied mnemonic. 

Regarding the separate `derive` and `remember` cheatcodes, aside from the `sign` use case, in the previous JS code example `someOtherUser` may not sign / broadcast anything, it might be used as a param in a contract deployment. For this reason, `deriveKey` should be separate. I think it's quite logical to go from mnemonic -> private key -> address as separate steps for the developer. This way our cheatcodes are quite primitive / flexible and we can have a simple `forge-std` helper to get a `(address,uint256)` tuple if that's desired.

On `broadcast` overloads that take the private key directly, this is a nice idea. My preference would be to support both in order to keep flexibility for script writers. 

Option A (current, with new supposed forge-std helper):
```solidity
string memory mnemonic = vm.envString("MNEMONIC");

address deployer = deriveRememberKey(mnemonic, 0);
address governance = deriveRememberKey(mnemonic, 1);

vm.broadcast(deployer);
Contract contract = new Contract(governance);

vm.broadcast(governance);
contract.addPair(vm.envString("PAIR"));

```

Option B (broadcast overload, with new supposed forge-std helper):
```solidity
string memory mnemonic = vm.envString("MNEMONIC");

uint256 deployerPrivateKey = vm.deriveKey(mnemonic, 0);
uint256 governancePrivateKey = vm.deriveKey(mnemonic, 1);
address governance = vm.addr(governancePrivateKey);

vm.broadcast(deployerPrivateKey);
Contract contract = new Contract(governance);

vm.broadcast(governancePrivateKey);
contract.addPair(vm.envString("PAIR"));
```

Personally I think Option A is nicer because we can just use the `governance` variable in both the `Contract` deployment and the `broadcast` cheatcode. Also, I'm envisaging that anyway most of the mnemonic loading is done in a BaseScript / helper function of some kind so in the actual scripts that one writes they can just use the address and know that it's loaded into Foundry. I'm open to supporting both of course.

Finally, on the naming of the cheatcode, originally I wanted to use just `derive` and `remember`. When looking at the cheatcodes originally I noticed that most are short / just one verb. Alas it seems this has anyway changed over time so I'm fine to change this to `rememberKey` to keep it in line with `deriveKey` or change it to something else if you think it makes more sense.

**Comment by mds1** [comment]
> Regarding using mnemonics over private keys, I have two points on this.

Valid points 👌

>  I think it's quite logical to go from mnemonic -> private key -> address as separate steps for the developer. This way our cheatcodes are quite primitive / flexible and we can have a simple forge-std helper to get a `address` or `(address,uint256)` tuple if that's desired.

Also fair, there's definitely value to having composability / granularity. My main concern was that we introduce too much granularity which would add confusion, but I don't think we are. My thoughts are:
- I think supporting both `rememberKey` and `broadcast(uint256 privateKey)` is ok
- There now are a decent amount of options for specifying senders (CLI flag, reading private key, reading mnemonic, then using `remember` vs. `broadcast` overload. So maybe we should come up with some guidelines/recommendations on when to use each? Are there any security tradeoffs for any of them? E.g. CLI flag means secrets are in shell history, other options mean secrets are in solidity so you can accidentally console.log them

> Personally I think Option A is nicer because we can just use the `governance` variable in both the `Contract` deployment and the `broadcast` cheatcode. Also, I'm envisaging that anyway most of the mnemonic loading is done in a BaseScript / helper function of some kind so in the actual scripts that one writes they can just use the address and know that it's loaded into Foundry. I'm open to supporting both of course.

Agreed in this example Option A is cleaner, but if you didn't need `governance` as an input anywhere, I think that's where the `broadcast(uint256)` overload would fit nicely. Either way as long as us + @mattsse and co. are ok with supporting both `rememberKey` and `broadcast(uint256 privateKey)`  then it's all personal preference / use-case dependent anyway 🙂

> I was just now thinking that because your prefer to use dedicated private keys, actually the remember cheatcode is the one which would be most helpful for you

Oh great point, I do really like those!

--------

Ok so proposed spec based on this convo:
- Keep this PR (code changes maybe needed, @mattsse will lead that) which adds `function rememberKey(uint256 privateKey) external returns (address)` to the Vm interface and behaves as specified
- Add new `broadcast(uint256 privateKey)` and `startBroadcast(uint256 privateKey)` overloads 
- TBD how to prioritize these and describe their tradeoffs / when to use each for the book?

**Comment by devanonon** [comment]
Thanks again @mds1! 100% agree with all of your points. Especially on the fact that we probably now have good feature coverage on many different private key loading mechanisms (albeit with tradeoffs).

* I've updated this PR to change the function name to `rememberKey`. Let me know if there are any other changes required here.
* I will get started on `broadcast` and `startBroadcast` overloads which take in a private key in another PR as suggested.
* Regarding the tradeoffs and cases which we should explain in the book, I'm also happy to do a first pass on this. I would suggest that first we get simple PRs into `forge-std` and `book` to just add / show this new cheatcodes exists and some basic usage. Then, in a follow-up PR to the `book`, I am happy to contribute an "advanced scripting" tutorial (or something akin to that) which demonstrates how to load in private keys / mnemonics along with some security considerations when doing so.

Happy to hear feedback on the above!

I'm super excited for this and #3021 to land. We will be able to call complex scripts from the CLI as simply as `forge script Script --fork-url mainnet`.

**Comment by devanonon** [comment]
Strange, `cargo +nightly clippy --all --all-features -- -D warnings` and `cargo clippy --all --all-features -- -D warnings` pass fine for me locally but is failing in the CI here. Is clippy running with a different config on CI?

**Comment by devanonon** [comment]
@mattsse I think @mds1 is happy with this PR and the follow-up actions I'll be doing. CI also passes now.

Any feedback on your side? :)

**Review by gakonst — APPROVED** [review]
this looks good to me - @mattsse any objections?

**Comment by devanonon** [comment]
Just realized that I had not considered resuming and needing to reload the private keys. With the latest commit I do now.

**Comment by gakonst** [comment]
let's also document the patterns in the book @devanonon ?

**Comment by devanonon** [comment]
@gakonst Yes, definitely. I will update the "Solidity Scripting" tutorial and the cheatcode sections.

**Pull request merged**
