### PR TITLE
feat(`invariants`): real-time runs counter

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation

proposed way to handle #585

multiple

## Solution

- add a global invariant reporter to collect test runs and completed runs
- display in terminal on thread that polls data progress each 100ms
- reporter is enabled if `show_progress` option is set to true (or run with env var `FOUNDRY_INVARIANT_SHOW_PROGRESS=true forge test`)

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
I think this is a very nice UX improvement, ty

pending @DaniPopes @klkvr

**Comment by DaniPopes** [comment]
Have you tested this in the context of multiple other unit and fuzz tests? It looks like it will constantly get "overwritten" by the other test results that stream in, so I don't think this is right.

This is something I've thought about before, and I think I'll post a proposal as an issue soon and we'll discuss this internally soon.

Also I would prefer you follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/), at least for PR names :smile_cat: (instead of `feat abc (issue)` you could write `feat(abc): do this thing)

**Comment by DaniPopes** [comment]
Yeah you can see the spinner gets interleaved with the other results, I'd prefer we hold off on this for now.

That's a much better title, thanks!

**Comment by grandizzy** [comment]
test-progress
A different approach using `indifcatif` library

**Comment by grandizzy** [comment]
retired in favor of #7914

**Pull request closed without merging**
