### PR TITLE
feat: add timeout option

### PR DESCRIPTION
**Pull request by farman13**
## Motivation

In our recent contribution to the open-source project, we focused on enhancing the robustness of the RPC handling mechanism within the `cast` CLI tool. The primary motivation for our changes was to improve the user experience by implementing a timeout feature for RPC requests, which addresses potential issues of hanging requests that can lead to frustration during usage. By introducing a configurable timeout, users can now have better control over their interactions with the RPC, ensuring that they receive timely feedback even in the event of network delays or server unresponsiveness. This enhancement not only optimizes performance but also aligns with best practices in software design, contributing to the overall reliability of the tool.

The solution implemented in our code change involves adding a timeout feature for RPC requests in the `cast` CLI tool. By introducing a `timeout` argument, users can specify the duration (in seconds) for which the CLI will wait for a response from the RPC server before aborting the request. This is achieved by leveraging the `Duration` type to set a timeout that prevents hanging requests, enhancing the overall user experience. The new feature is integrated seamlessly into the existing command-line argument parsing and request handling, ensuring backward compatibility while improving the responsiveness and reliability of the tool.

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
lgtm

**Comment by farman13** [comment]
update the code !

**Comment by farman13** [comment]
there is some issue related to my github i reopen it with as new issue

**Comment by farman13** [comment]
Review the updated code!

**Pull request closed without merging**
