### PR TITLE
chore: migrate revm 3.0

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
bump revm to 3.0

this is a bit horrible...

@DaniPopes would you be interested in taking on this task by any chance? 
I know it's pretty thankless work, but it's desperately needed.

There are a lot of breaking changes due to revm and the ruint/primtive-types situation.

I think the right approach would be to migrate `foundry-evm` first, step by step

### CODE REVIEW

**Comment by Evalir** [comment]
Hey @mattsse , i think with some guidance I should be able to at least soften the workload on this—Happy to help on it!

**Comment by mattsse** [comment]
this would be much appreciated.

we have a lot of breaking changes here.

mainly affecting the foundry-evm crate, which we should focus on first.

Tbh I guess the best approach is by letting the compiler guide you. I started with replacing revm types, there's still some work to do with all the new types, for example everything that calls `evm.transact` etc needs to be updated.

I'd probably start with running `cargo c` in foundry-evm and start fixing errors.

**Comment by Evalir** [comment]
awesome, will do—i'll start by branching off from here then (unless you want it done another way)

**Comment by mattsse** [comment]
sg!
also recommend bumping revm again, we have additional From impls for the different H256 U256 types now

**Comment by Evalir** [comment]
just started here: https://github.com/mattsse/foundry/pull/2

as you're working from a fork i had to direct the PR to your repo instead of upstream

**Pull request closed without merging**
