### PR TITLE
feat(fmt): add sort_imports config

### PR DESCRIPTION
**Pull request by meetmangukiya**
## Motivation

Sorting imports is a desirable feature.
Closes https://github.com/foundry-rs/foundry/issues/3396. I didn't check the issues first and went head first into the implementation because I wanted import sorts but see now that @rkrasiuk is already assigned to the issue 😅 .

## Solution

Sorts the `SourceUnitPart::Import` parts before running it through the formatter. Sort works but blanks and slicing need to be fixed. Also, as I built this I have realized few things:
1. Contiguous imports detection based off just contiguous `SourceUnitPart::Import` wont be correct because blank lines do not have a `SourceUnit` entry. Need to use `self.blank_lines` somewhere to better determine the slice boundaries.
2. Currently, it uses `blank_lines` to determine if there should be a space between formatted units, need to fix it. I am thinking maybe there is a way to use the `needs_space` callback in conjunction with the `import_slices` to determine the blank spaces to add correctly.

Opening a WIP PR, because it might not be the best or even a correct way to do this.

### CODE REVIEW

**Comment by Evalir** [comment]
hey @meetmangukiya i think this is good! do you plan on finishing this, or should we take over?

**Comment by meetmangukiya** [comment]
Will get back to this when I find time. In the mean time if you want to take over it's also fine.

**Comment by meetmangukiya** [comment]
I also am interested in a feature for sorting functions by receive, fallback, visibility, mutability, payable, etc. as [here](https://docs.soliditylang.org/en/v0.8.21/style-guide.html#order-of-functions).

**Comment by aviggiano** [comment]
Hello

This is a great feature. 
Would it be possible to also include "remove unused imports" in the PR?

**Comment by mattsse** [comment]
I completed this by taking the original approach and merely modifying the group detection.

This currently only sorts individual import groups (separated by newline) and does not reorder groups. I guess we could reorder groups as well but this should be a separate setting.

there's a limitation when a group contains a comment, but we can live with that for now.
perhaps there are other edge cases but since this is opt-in, this should be good for now until they get reported.

**Comment by meetmangukiya** [comment]
🐐

**Review by Evalir — APPROVED** [review]

**Pull request merged**
