### PR TITLE
Pretty printed logs and events in cast run

### PR DESCRIPTION
**Pull request by ioterw**
## Motivation

Recently I got quite big events in cast, so made them a bit more pretty printed, also fixed padding of topics in logs

## Solution

Before:
image
After:
image

P.S. I don't remember any log bigger than 4 topics, so removed number 13 for string formating.

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
I don't have strong feelings about this, but I find this easier to parse now.
I only worry about output bloat.

wdyt @klkvr @mds1

**Comment by DaniPopes** [comment]
If we accept this, we should also do this for calls too.

**Comment by mattsse** [comment]
looking at the failing tests, I think we want to this for topics > 1

**Review by ArkFunds — APPROVED** [review]

**Review by ArkFunds — APPROVED** [review]

**Comment by ioterw** [comment]
Added calls + fixed calls with no params
image

**Review by DaniPopes — CHANGES_REQUESTED** [review]
Please apply these changes in `revm-inspectors` and I will review there. I don't want to modify the code here

**Comment by zerosnacks** [comment]
Hi @ioterw, since the last update we've entirely moved to use the [`revm-inspectors` ](https://github.com/paradigmxyz/revm-inspectors) crate to render the traces. Any proposed changes should be added there.

Given that there is no actionable item left here I think it makes sense to close this ticket in favor of a future one to be opened by @ioterw in https://github.com/paradigmxyz/revm-inspectors

**Pull request closed without merging**
