### PR TITLE
refactor: use forge-std/Test.sol for tests

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
replace `<ForgeTest> is DSTest` with `<ForgeTest> is STest` so we use the actual `forge-std/Test.sol` for our tests

## Solution
copy excerpt of forge-std contracts into `testdata/lib/forge-std` and update usage in `testdata`

### CODE REVIEW

**Comment by gakonst** [comment]
LGTM - let's replace the checked in forge-std instead with a submodule?

**Comment by gakonst** [comment]
Hm but then we run in the risk of `forge-std` here going out of sync with the `forge-std` in the other repo. 
* What exact difficulties do you foresee via a submodule?
* Is it worth using [`git subtree`](https://www.atlassian.com/git/tutorials/git-subtree) instead?
* Is it worth pulling `forge-std` in the main repo? (Think not)

**Comment by mattsse** [comment]
> What exact difficulties do you foresee via a submodule?

complicates things, really don't like them.

> Is it worth using [git subtree](https://www.atlassian.com/git/tutorials/git-subtree) instead?

can't say never used it, no idea how it works.

> Is it worth pulling forge-std in the main repo? (Think not)

should remain stand-alone because of `forge install`

tbh I'm also fine with closing this entirely since we don't really need `forge-std/Test` as base because all the features it provides are tested, so perhaps even redundant to pull in like that.

**Comment by gakonst** [comment]
Yeah OK, my bad here, didn't think of the complication introduced via submodule. Let's close - sorry for the waste of time :S

**Pull request closed without merging**
