### PR TITLE
feat(fmt): checksummed addresses

### PR DESCRIPTION
**Pull request by rkrasiuk**
## Motivation

Address [recent comment in config issue](https://github.com/foundry-rs/foundry/issues/2173#issuecomment-1187712550) & [original comment from @gakonst](https://github.com/foundry-rs/foundry/pull/2170#issuecomment-1171492766)

## Solution

format addresses to checksummed

### CODE REVIEW

**Review by gakonst — APPROVED** [review]
beautiful - game changer for script developers that copy-paste addresses

**Comment by gakonst** [comment]
I feel like this is something I always want on, so let's avoid a config unless ppl ask for it!

**Comment by rkrasiuk** [comment]
@jpopesculian according to the docs:
```
Hexadecimal literals that are between 39 and 41 digits long and do not pass the checksum test produce an error.
```
so, I guess, we better force the checksum

**Comment by Ihtyijfd** [comment]
> ## Motivation
> 
> 
> 
> Address [recent comment in config issue](https://github.com/foundry-rs/foundry/issues/2173#issuecomment-1187712550) & [original comment from @gakonst](https://github.com/foundry-rs/foundry/pull/2170#issuecomment-1171492766)
> 
> ## Solution
> 
> format addresses to checksummed

**Pull request merged**
