### PR TITLE
perf(script): binary search gas estimation

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
atm gas limit in script is `gas as returned by the executor` * multiplier (=1.3)

however, the gas returned by the executor is the exact gas value the call consumed, which might not be enough if used as gas_limit

## Solution
use binary search over `(gas, gas*3)` to find the lowest gas limit with which the call succeeds and use that instead

### CODE REVIEW

**Comment by joshieDo** [comment]
Couple questions...

> however, the gas returned by the executor is the exact gas value the call consumed, which might not be enough if used as gas_limit

But that's why we added the multiplier... how would this help ? Or are you looking to remove the multiplier? Also... why isn't it enough locally ?

--

Given that, we should add the same logic to `deploy()` probably

**Comment by joshieDo** [comment]
https://github.com/mattsse/foundry/blob/dfb51e96c43617ebb7de12d11bf06561d775bd95/cli/src/cmd/forge/script/runner.rs#L160-L165

And we probably need the same logic here

**Comment by mattsse** [comment]
> Couple questions...
> 
> > however, the gas returned by the executor is the exact gas value the call consumed, which might not be enough if used as gas_limit
> 
> But that's why we added the multiplier... how would this help ? Or are you looking to remove the multiplier? Also... why isn't it enough locally ?

refunds are capped at 20%, but I think the previous impl didn't account for call stipend requirement 

https://github.com/foundry-rs/foundry/pull/2676/files#diff-e46d32134b17594d0ea6338a1e4a137f35b4b3cce68747279f74c67067847d64L213

so for tx that consume little gas, the 30% may not cover that.

in any case estimating like this is more accurate.


does deploy, commit? we can definitely add estimation there as well.

**Comment by joshieDo** [comment]
> does deploy, commit? we can definitely add estimation there as well.
yeah

**Comment by mattsse** [comment]
I see, I can rewrite the deploy code,

should we merge and followup for deploy?

**Review by joshieDo — APPROVED** [review]

**Pull request merged**
