### PR TITLE
fix: use revm to calculate gas stipend

### PR DESCRIPTION
**Pull request by DaniPopes**

### CODE REVIEW

**Comment by DaniPopes** [comment]
This also includes 21k+ for initial tx cost, idk if this is right, cc @mattsse @klkvr

**Review by onbjerg — APPROVED** [review]
looks right to me, given `calc_stipend` also includes 21k

**Comment by DaniPopes** [comment]
Right, missed that

**Comment by DaniPopes** [comment]
Also some extra perf because revm calculation is better

**Pull request merged**
