### PR TITLE
fix: enable `revm/blst`

### PR DESCRIPTION
**Pull request by klkvr**
## Motivation

we need this feature to enable BLS precompiles for prague and alphanet spec

### CODE REVIEW

**Review by mattsse — CHANGES_REQUESTED** [review]
we currently enable all the revm features in the crates, I think we should be consistent and also do this for anvil and the evm crate instead because this only really matters there?

ref `revm = {`

wdyt @DaniPopes

**Comment by DaniPopes** [comment]
Yeah I'd prefer that

**Comment by klkvr** [comment]
moved to evm-core as this is where we create EVM and configure the spec

**Review by DaniPopes — APPROVED** [review]

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
error unrelated

**Pull request merged**
