### PR TITLE
feat: use improved human readable function parser

### LINKED ISSUE #670: ```cast``` returning 'illegal abi' error when sending transactions to functions with tuples
### Component

Cast, Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (0b6b202 2022-02-04T16:36:20.877746906+00:00)

### What command(s) is the bug in?

```forge send``` and possibly others

### Operating System

Linux

### Describe the bug

```cast send``` used in format ```seth call [<options>] <to> <sig> [<args>...]``` does not correctly parse function signatures if they contain tuples. It seems this problem stems from the ```ethers-rs``` repo, specifically [here](https://github.com/gakonst/ethers-rs/blob/77dcccb7bae83a896a319e116bd34a6844b896ba/ethers-core/src/abi/human_readable.rs).

It looks like line 261 in particular would  be causing the issue since is splits the calldata arguments with '(' as the delimiter in order to separate input and output args, but that would break if there are any tuples present as args.

This issue is also present in ```seth```, although the error message is a little clearer here as it outputs ```seth-abi: error: unexpected character "(" at position 0 in "(bytes1,bytes32,uint64)"```.

### LINKED ISSUE #1903: cast 4byte-decode can not decode struct type param
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (20b2926 2022-06-10T00:15:22.550741Z)

### What command(s) is the bug in?

cast 4bd

### Operating System

_No response_

### Describe the bug

Example command: decoding with `cast 4bd`:
```
cast 4bd 0x64a3bc15000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000310d12ef15a00640000000000000000000000000000000000000000000000000000000000000002a000000000000000000000000000000000ae347930bd1e7b0f35588b92280f9e750000000000000000000000008d90113a1e286a5ab3e496fbd1853f265e5913c6000000000000000000000000911c2311503c0da6a4d82d40bc3bad4ade10d2380000000000000000000000008d90113a1e286a5ab3e496fbd1853f265e5913c6000000000000000000000000000000000000000000000000000000175336709400000000000000000000000000000000000000000000000310d12ef15a006400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000062a314f40833592b8044884c18244af94f82e7e8e5cb403b567a6aa7402b6560991d0012000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001e00000000000000000000000000000000000000000000000000000000000000024f47261b0000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024f47261b0000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000581b75ec8514073f54f6cd3e16379482cc8f76e1c47a99282b23283c69999887f0465f64630ec9391a9e3d6fa908f63475bcb3ef11ab702f26c29e2b04ff71cde755911c2311503c0da6a4d82d40bc3bad4ade10d2380012040000000000000000
```

Error:
```
The application panicked (crashed).
Message:  could not convert fillOrKillOrder((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes),uint256,bytes) to function
Location: utils/src/lib.rs:264
```

The abi-encoded data is the data of the internal transaction to 0x exchange proxy of a successful [transaction](https://etherscan.io/tx/0x3ed7cfbd4437a4c9238d851540cbc334f08d41ed0c83badd8f61116960296a97).

### LINKED ISSUE #2025: cast sig bug
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

_No response_

### What command(s) is the bug in?

_No response_

### Operating System

Linux

### Describe the bug

$ cast sig "aggregate((address,bytes)[])"
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Message("Expected input args parentheses at `aggregate((address,bytes)[])`")
Location: cli/src/cast.rs:651

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #670
Closes #2025
Closes #1903

uses an improved human-readable parser that can properly handle complex tuple types.

the reason `AbiParser`still exists is because it can resolve custom types as well (used in `abigen!`), however this is out of scope for the forge/cast commands that need parsing so we use it directly

## Solution

```
cast sig "aggregate((address,bytes)[])"                                                                                                                                                   
0x252dba42

```
https://www.4byte.directory/signatures/?bytes4_signature=0x252dba42

### CODE REVIEW

**Comment by mattsse** [comment]
it does:

```console
./target/debug/cast 4bd 0x64a3bc15000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000310d12ef15a00640000000000000000000000000000000000000000000000000000000000000002a000000000000000000000000000000000ae347930bd1e7b0f35588b92280f9e750000000000000000000000008d90113a1e286a5ab3e496fbd1853f265e5913c6000000000000000000000000911c2311503c0da6a4d82d40bc3bad4ade10d2380000000000000000000000008d90113a1e286a5ab3e496fbd1853f265e5913c6000000000000000000000000000000000000000000000000000000175336709400000000000000000000000000000000000000000000000310d12ef15a006400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000062a314f40833592b8044884c18244af94f82e7e8e5cb403b567a6aa7402b6560991d0012000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001e00000000000000000000000000000000000000000000000000000000000000024f47261b0000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000024f47261b0000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000581b75ec8514073f54f6cd3e16379482cc8f76e1c47a99282b23283c69999887f0465f64630ec9391a9e3d6fa908f63475bcb3ef11ab702f26c29e2b04ff71cde755911c2311503c0da6a4d82d40bc3bad4ade10d2380012040000000000000000
1) "fillOrKillOrder((address,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes,bytes),uint256,bytes)"
(0x00000000ae347930bd1e7b0f35588b92280f9e75, 0x8d90113a1e286a5ab3e496fbd1853f265e5913c6, 0x911c2311503c0da6a4d82d40bc3bad4ade10d238, 0x8d90113a1e286a5ab3e496fbd1853f265e5913c6, 100180324500, 56552033610000000000, 0, 0, 1654854900, 3709227417180565687725420283842435573329641510267313270658188471781665079314, 0xf47261b0000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec7, 0xf47261b0000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2)
56552033610000000000
0x1b75ec8514073f54f6cd3e16379482cc8f76e1c47a99282b23283c69999887f0465f64630ec9391a9e3d6fa908f63475bcb3ef11ab702f26c29e2b04ff71cde755911c2311503c0da6a4d82d40bc3bad4ade10d238001204


```

**Comment by gakonst** [comment]
This is a good opportunity for us to add docs to the book about how to call methods with arrays, tuples and structs

**Review by gakonst — APPROVED** [review]
clean otherwise - obvious net positive

**Review by onbjerg — APPROVED** [review]
test failure unrelated, some test stalled

needs rebase tho

**Pull request merged**
