### PR TITLE
refactor(cast): subcommands

### PR DESCRIPTION
**Pull request by DaniPopes**
## Motivation

ref #3125, from point 3 onwards. Please make sure that I haven't overwritten any new commits since that PR

## Solution

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
this is great, love the examples

**Comment by mattsse** [comment]
some failing cast test, is this related?

**Comment by DaniPopes** [comment]
oops, U64 parses str as hex

**Review by mattsse — APPROVED** [review]
🙏

**Pull request merged**
