### PR TITLE
feat(forge): install latest semver tag if it exists

### LINKED ISSUE #401: forge install: Installs development branch and ignores releases
`forge install openzeppelin/openzeppelin-contracts` installs the master branch of the repository. We consider this a development branch, and request that people use our releases instead. On one hand it's a matter of stability because the master branch may receive breaking changes, but it's also a matter of security. Our release process involves release candidates, an open review period, and a call to participate in the bug bounty, so we discourage using code that hasn't been through this process.

Ideally, for the OpenZeppelin Contracts repository, forge would fetch the tags and install the latest tag (according to semver) that is not a release candidate. This may not be a general enough solution since a git repository is not guaranteed to use tags in this way, and may even only have old tags that don't include the real latest version. There could be a flag to install the latest, but preferably this should be the default behavior for OpenZeppelin Contracts at least.

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #401

cc @mds1 

## Solution
after submodule clone, scans all semver tags and install latest, if not tag was provided as argument.

eg:

```
forge install "openzeppelin/openzeppelin-contracts"
cat .gitmodules
```

```
[submodule "lib/forge-std"]
        path = lib/forge-std
        url = https://github.com/foundry-rs/forge-std
[submodule "lib/openzeppelin-contracts"]
        path = lib/openzeppelin-contracts
        url = https://github.com/openzeppelin/openzeppelin-contracts
        branch = v4.8.0
```

### CODE REVIEW

**Comment by mattsse** [comment]
I just realized this would require additional work for updating as well.

for example, this would now pin forge-std always to 1.0.0, so we need to publish more frequently?

**Comment by mds1** [comment]
> How should update behave? bump to next semver tag?

Hmm good question. Curious what @frangio thinks. Since afaik we don't have the flexibility of e.g. cargo/npm to specify e.g. `=1.2.3` to never update, perhaps we only bump patch versions to be safe, and for other bumps the user needs to do it manually?

Presumably `forge update lib/my-dep@v2.0.0` should be sufficient to do that

> for example, this would now pin forge-std always to 1.0.0, so we need to publish more frequently?

This seems ok to me. We can definitely be better about tagging new forge-std releases

**Comment by mds1** [comment]
Two other questions/thoughts:
1. If no tags are found, I assume it just installs the latest master? Probably should print a warning that it might be unstable, when this happens
2. Say I do want to explicitly install the latest master, I can do `forge install foundry-rs/forge-std@master` right? (just making sure this doesn't get prevented. In the original issue I suggested a `--dev` flag but I don't think that's actually needed since you can use this syntax)

**Comment by frangio** [comment]
Regarding updates my opinion is that if a version bump is breaking the user should specifically request it somehow, or at least be notified. Minor version bumps are not supposed to be breaking (except for 0.x.y versions), so I would be okay if those were automatic as well. In any case, I wonder if foundry could also print a message saying that a more recent version is found and it requires a manual update command.

**Comment by landakram** [comment]
I wonder if we should not attempt to follow semver at all, and instead always move to the current HEAD of whatever ref the submodule is pointed to. If the user has installed a branch, `forge update` would move to HEAD of the branch. If a user has installed a tag, then `forge update` would do nothing. If the user wishes to move to a newer version, then they would explicitly need to install the newer tag. 

If we do automatic semver for tags but not for branches, we create a subtle difference between the two, where installing a tag might update the submodule ref, but installing a branch will not. A repo might use branches with version names (instead of tags, e.g. a branch named `v4.8.0`), in which case, a user might think that `forge update` will follow semver, but in reality, it only does that for tags.

We could make the behavior consistent for branches too, following semver where possible, but consider the situation where a repo uses branches with version names, e.g. a branch named `v4.8.0`, but for some reason, this branch is actively maintained with new commits coming in. The repo also has a branch called `v4.8.1`. Should `forge update` move the submodule hash to the HEAD of `v4.8.0` or jump to `v4.8.1`? 

IMO, better to keep behavior consistently "will move to HEAD of the submodule ref, where possible" and let users manually install newer versions explicitly with `forge install some-dep@some-version`.

**Review by gakonst — APPROVED** [review]

**Comment by frangio** [comment]
I tried `forge install` and it now does what I was asking for. I have nothing else in mind that I'd like to see regarding dependencies.

I am seeing errors with `forge update` though. I don't know if it's working correctly.

```
$ forge update
Error:
fatal: Unable to find refs/remotes/origin/v1.1.0 revision in submodule path 'lib/forge-std'
$ forge update lib/openzeppelin-contracts/
Error:
fatal: Unable to find refs/remotes/origin/v4.8.0 revision in submodule path 'lib/openzeppelin-contracts'
```

**Comment by mattsse** [comment]
right, update needs some work, will prioritize this.

**Comment by gakonst** [comment]
SGTM

**Comment by ZrowGz** [comment]
It seems like if you specify a specific tag or branch, it should preserve that. Like if I want to use openzeppelin v5.0.1, specifying that tag should prevent `forge update` from touching it. If I want to update something that was at a specific tag, then I should manually change that with a remove & reinstall. Or it should ask if you want to update something that's tagged? Since it doesn't store the tag=<v5.0.1> (for the OZ example), when someone else pulls down the repo & runs `forge install` it doesn't seem to install the correct version, just defaulting to OZ's main branch, which is constantly updated & not-yet-formalized release (ie, potentially unaudited).

If you specify a branch, like `release-v5.0` then it could update that branch to a newer version. But not if it was installed via tag. 

This would provide the most logical behavior for this intended usage, at least from my perspective/use of tags vs branches vs default behavior.

**Pull request merged**
