### PR TITLE
refactor(evm, inspector): use GasInspector for Debugger

### PR DESCRIPTION
**Pull request by shekhirin**
## Motivation

https://github.com/bluealloy/revm/pull/222

## Solution

Gas calculation in debugger works the same as before:
foundry

### CODE REVIEW

**Comment by gakonst** [comment]
nice! what are we missing to get this over the line?

**Review by mattsse — COMMENTED** [review]
lgtm. 

any remaining blockers? revm was also just bumped

**Comment by shekhirin** [comment]
@gakonst @mattsse I think it's done, wanted to test it a bit more to be sure that behaviour is the same. I believe it's fine.

**Review by mattsse — APPROVED** [review]
lgtm

**Pull request merged**
