### PR TITLE
chore: crates/ directory

### PR DESCRIPTION
**Pull request by DaniPopes**
## Motivation

1. move all crates into crates/
2. prefix manifest workspace.members with `crates/`
3. replace `../testdata/` with `../../testdata`

### CODE REVIEW

**Review by Evalir — APPROVED** [review]
as soon as ci is green this is good imo. let's make the flattening happen

**Comment by Evalir** [comment]
deferring to @mattsse for final merge

**Review by mattsse — CHANGES_REQUESTED** [review]
ah yikes, I only saw this one now after merging some other prs...

so there are a few conflicts unfortunately, sorry about that

requires rebase

**Review by mattsse — APPROVED** [review]
long overdue,

this will introduce conflicts in open prs, but those should be easily fixable, since this simply moves the files

**Review by Evalir — APPROVED** [review]
finally!

**Pull request merged**
