### PR TITLE
(feat) add conditional breakpoints

### PR DESCRIPTION
**Pull request by iFrostizz**
## Motivation

Implementing @mds1 's ideas about extending breakpoints, ref: https://github.com/foundry-rs/foundry/pull/4679#issuecomment-1503455791

## Changes

1. Add conditional breakpoints (`vm.breakpoint("a", true)` to switch on and `vm.breakpoint("a", false)` to switch off)
2. Write the `['<char>]: goto breakpoint` notice on debugger footer

## About the notice

It's getting somewhat big and I cannot see the whole footer (about 2/3 currently) at once. Why not adding a `h` to toggle help that would take more space, but could be collapsable ?

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
lgtm,

needs nightly fmt

> Why not adding a h to toggle help that would take more space, but could be collapsable ?

I guess that makes sense

**Comment by iFrostizz** [comment]
@mattsse wdyt about adding the toggling help notice with 'h' ? We could do it in this PR as it's quite lightweigth

**Comment by mattsse** [comment]
sgtm!

**Comment by iFrostizz** [comment]
Wanted to do smth similar to [vim-which-key](https://github.com/liuchengxu/vim-which-key) help modal that would pop up over the debugger using contexts, but that was doing some underflow and not sure why. So it's resizing the main window to leave some space for the help footer and collapse on `h` press, is it good enough?

**Comment by iFrostizz** [comment]
Seems like the conflicts doesn't resolve after a rebase

**Comment by iFrostizz** [comment]
@mattsse seems to be good now!

**Review by mattsse — APPROVED** [review]
lgtm, ty

**Comment by iFrostizz** [comment]
@mattsse there have been a conflict fail, which is why you had to put the trailing "_" to make clippy happy here: https://github.com/iFrostizz/foundry/blob/556e0b4580f92a7f4f079d536416f33c695faae4/ui/src/lib.rs#L369-L382
I had broken down the two help lines to make it more readable, because it's wrapping currently (plus lacking of the h key binding text)

**Pull request merged**
