### PR TITLE
[wip] feat(fmt): format buffer groups

### PR DESCRIPTION
**Pull request by rkrasiuk**
## Motivation

RE: @jpopesculian's comment on [comment](https://github.com/foundry-rs/foundry/pull/1682#issuecomment-1134930455) support PR

## Solution

Use groups & format buffer for indentation

### CODE REVIEW

**Comment by gakonst** [comment]
@jpopesculian fyi if you're back

**Comment by jpopesculian** [comment]
nice! im flying this evening and will take a look at the airport 😊

**Comment by rkrasiuk** [comment]
@jpopesculian nice, thanks! i only started with groups, last week was working on [writes in chunk](https://github.com/foundry-rs/foundry/pull/1717). in general, there is one remark to your initial comment, we should prob have the ability to `end_group` as well, because the statement `every line after beginning of the group is indented by indent + 1` does not uphold for multiline func/contracts definitions due to the trailing closing bracket `}`

**Comment by jpopesculian** [comment]
@rkrasiuk looking good! and thanks for handling the write chunks transition :heart_eyes: the group and indented helpers also make things a lot easier to read! i think in terms of the `end_group`, i don't know if its worth adding the complexity. i think maybe closing braces might be a case we may just want to handle individually? there seems to be more of a pattern with open parentheses/brace/bracket, indent items/statements, closing parantheses/brace/bracket. where we can maybe just treat the closing brace brace/etc as its own group after dedenting

**Comment by jpopesculian** [comment]
@gakonst would you like me to fork and pick up this task from @rkrasiuk tomorrow?

**Comment by gakonst** [comment]
As discussed, let's try to consolidate + merge all PRs on the `jpopesculian/comments` branch of the main repo (not the fork), and try to get that in so that we have full reconstruction of the code on `forge fmt` calls. Then, let's start adding visitors for the things we're missing one by one

**Pull request merged**
