### PR TITLE
feat(cheatcodes): add vm.assumeNoRevert for fuzz tests

### LINKED ISSUE #4090: `vm.canRevert()`: allow tests to revert in expected cases
### Component

Forge

### Describe the feature you would like

Often it's desirable to check properties of results, such as a new price of an AMM. However, these functions can contain error-checks and revert on certain inputs. And sometimes I want to make sure a property holds only if I actually get a result from a call and ignore the reverting cases.

An example of what this could look like is:
```solidity
    function test_getPrice_invariant(uint256 x, uint256 dx) public {
        dx = bound(dx, 0, type(uint256).max - x);

        vm.canRevert(Overflow.selector);
        uint256 y1 = amm.getPrice(x);

        vm.canRevert(Overflow.selector);
        uint256 y2 = amm.getPrice(x + dx);
        
        assertGte(y2, y1);
    }
```

A current workaround is to use low-level calls or `try ... catch ...`, but these have to be set up for each function manually.

```solidity
    function getPrice_canRevert(uint256 x, bytes4 selector) internal returns (uint256) {
        try amm.getPrice(x) returns (uint256 price) {
            return price;
        } catch (bytes memory reason) {
            require(bytes4(reason) == selector, "unexpected revert");
        }
    }
```

An implementation of `vm.canRevert`/`vm.allowRevert` could add to the counter of `vm.assume` checks to make sure that one isn't rejecting all calls.

### Additional context

_No response_

### LINKED ISSUE #7246: Add `vm.catchRevert` / `vm.ignoreRevert` functionality, to allow better fuzz testing for complicated cases
### Component

Forge

### Describe the feature you would like

# Problem
Fuzz tests are very useful to check specific conditions about complicated math and logic across the range of all possible inputs. Most smart contracts have a variety of safety checks like safe arithmetic, input sanitization etc. that result in many different error codes.

If someone wants to write a fuzz test that checks only one aspect of the logic across the whole range of inputs, they currently have to handle all other possible reverts explicitly. In many cases, this is equivalent to the task of rewriting much of the smart contract logic.

# Example
For example, in this test - 
``` 
    function test_swap_amm_pathIndependence(
        bool _isZeroToOne,
        uint256 _reserve0,
        uint256 _reserve1,
        uint256 _amountIn,
        uint160 _sqrtSpotPriceX96,
        uint160 _sqrtPriceLowX96,
        uint160 _sqrtPriceHighX96
    ) public{}
```

If someone just wanted to check the following things, across all possible variations of reserves, swap conditions, and spot price ranges:
1. Liquidity never changes after a swap
2. A swap of equal amounts in the reverse direction can never extract more money than what they started off with.
3. The swap reverts if the price equals the lower and higher ranges
etc.

It is very hard to write a test like this currently, because across this wide range of inputs, we could receive hundreds of different errors because of invalid states like - 
* ERC20 Errors -  insuffienct amount, insufficient allowance etc.
* Arithmetic Errors - Overflow, underflow, division by 0 
* Smart contract-specific errors - Maybe the spot price is out of bounds, or maybe reserves are incorrectly distributed.

It becomes almost impossible to handle all of these errors explicitly in the test. We know that these errors represent the correct functioning of the program, so we simply want to ignore them and move on to the next fuzz run, or the next part of the test.

I couldn't find a straightforward way to achieve this in foundry.
`expectRevert` does not work here, because for an external call there are some errors that may or may not occur depending upon the input. 
To write expectRevert statements for all possible errors, would be like recreating the smart contract logic in the tests.

# Solution
We introduce new cheat codes in the VM library called `ignoreRevert` and `catchRevert`. These instruct the tests that there is a possibility of a revert here, but we don't want to fail the test because of this.

There can be some variations of this -
1. `ignoreAllReverts` - ignore any revert that comes out of this specific function call.
2. `catchRevert(error code)` - if a revert happens, then go to this block, else continue execution normally.
3. `catchAllReverts`

### Additional context

# The Patchy Workaround
There is a possible workaround that involves using try-catch statements for such tests. 

## Example
```
            try pool.swap(params) returns (uint256, uint256 amountOutSecond) {
                assertGe(_amountIn, amountOutSecond, 'pathIndependence');
            } catch (bytes memory reason) {
                if (keccak256(reason) == keccak256(abi.encodePacked(hex'd19ac625'))) {
                    console.log('Reverted because of 0 amountOut');
                    return;
                } else {
                    emit LogBytes(reason);
                    revert('revert swap 2');
                }
            }
        } catch {
```
1. You need to manually calculate and check the error codes,  for the errors that you care about handling.
2. As the number of calls where you want to ignore the errors increases, the try-catch nesting becomes very complicated and confusing.

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
Closes #4090 
Closes #7246 

Similar with `assume` cheatcode, but for discarding inputs in fuzz runs that reverts:
```Solidity
    /// Discard this run's fuzz inputs and generate new ones if next call reverted.
    function assumeNoRevert() external pure;
```

## Solution

- split assume* cheatcodes in separate mod
- in call_end, if assumeNoRevert cheatcode set, discard run if we're at the same depth as cheatcode and call reverted by returning result with MAGIC_ASSUME output (caught by fuzz and invariant tests and discarded). If call didn't revert then reset chetcode state and continue test
- unit tests

### CODE REVIEW

**Comment by klkvr** [comment]
should this only re-run if _next_ call reverts? went through issues and seems like this is the common usecase, current version might result in footguns, especially given that sometimes it's hard to craft an array with addresses whitelist

**Comment by mds1** [comment]
Spec sgtm, and do we also increment the rejects counter the same way? A single test rejects counter for this + `vm.assume` seems like the best UX, to keep it simple

**Comment by grandizzy** [comment]
> Spec sgtm, and do we also increment the rejects counter the same way? A single test rejects counter for this + `vm.assume` seems like the best UX, to keep it simple

yep, the rejects counter is incremented same way

**Review by mds1 — APPROVED** [review]

**Review by mattsse — APPROVED** [review]
lgtm, pending @klkvr

**Review by klkvr — APPROVED** [review]

**Pull request merged**
