### PR TITLE
feat(forge): Pausable gas metering

### PR DESCRIPTION
**Pull request by brockelmore**
## Motivation
We get a lot of requests for being able to stop gas metering. 

related:
#2429
#3796

+ comments in telegram chat + twitter.

This will improve UX of people using scripting + FFI + etc

## Solution
This PR introduces 2 cheatcodes:
1. `pauseGasMetering()`
2. `resumeGasMetering()`

`pauseGasMetering()` pauses gas metering as soon as the call returns.

`resumeGasMetering()` resumes gas metering from where it was paused.

works by cloning the gas upon pause, and at each step, resetting the gas. Not the most efficient in terms of performance but gets the job done without hacking too deep into REVM.

i.e.:
```solidity
// SPDX-License-Identifier: Unlicense
pragma solidity >=0.8.0;

import "ds-test/test.sol";
import "./Cheats.sol";

contract GasMeteringTest is DSTest {
    Cheats constant cheats = Cheats(HEVM_ADDRESS);

    function testGasMetering() public {
        uint256 gas_start = gasleft();

        addInLoop();

        uint256 gas_end_normal = gas_start - gasleft();


        cheats.pauseGasMetering();
        uint256 gas_start_not_metered = gasleft();

        addInLoop();

        uint256 gas_end_not_metered = gas_start_not_metered - gasleft();
        cheats.resumeGasMetering();

        uint256 gas_start_metered = gasleft();

        addInLoop();

        uint256 gas_end_resume_metered = gas_start_metered - gasleft();

        // resume and normal are the same
        assertEq(gas_end_normal, gas_end_resume_metered);
        // not metered is truly 0 gas
        assertEq(gas_end_not_metered, 0);
    }

    function addInLoop() internal returns (uint256) {
        uint256 b;
        for (uint256 i; i < 10000; i++) {
            b + i;
        }
        return b;
    }
}
```

### CODE REVIEW

**Review by rkrasiuk — APPROVED** [review]
nice

**Review by mattsse — APPROVED** [review]
lgtm

**Comment by vapopov** [comment]
@brockelmore seems like this one doesn't solve the issue https://github.com/foundry-rs/foundry/issues/3796 ?

I've tried to test with latest master and got issue with run out of gas

```
Gas used: 9223372036854775807
Error:
Script failed.
```

**Comment by brockelmore** [comment]
> @brockelmore seems like this one doesn't solve the issue #3796 ?
> 
> I've tried to test with latest master and got issue with run out of gas
> 
> ```
> Gas used: 9223372036854775807
> Error:
> Script failed.
> ```

Please provide a reproduction

**Comment by vapopov** [comment]
@brockelmore https://github.com/foundry-rs/foundry/issues/3858

I've tried all option to call it at start but seems like, there another counter of gas which is used not for reports

**Pull request merged**
