### PR TITLE
feat(anvil): auto adjust hardforks by block number

### LINKED ISSUE #2252: automatically detect evm version when forking at a certain block height
### Component

Anvil

### Describe the feature you would like

it would be less surprising for a user if anvil used the evm which was in place at the fork block height when forking, instead of the latest one. this requires adding a mapping of known chain ids to block heights to evm version running since that height.

### Additional context

you can see a similar feature implemented in ape-foundry here
https://github.com/ApeWorX/ape-foundry/pull/9

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation

Blocked by #2277 

Closes #2252

## Solution
add hardfork block table and convert hardfork based on block number

### CODE REVIEW

**Comment by gakonst** [comment]
https://github.com/foundry-rs/foundry/pull/2277 is merged

**Review by gakonst — APPROVED** [review]
beautiful -- cc @banteg who encountered this

**Comment by mattsse** [comment]
needs followup with downgrade to revm compatible ref #2260

**Comment by sambacha** [comment]
This wont work on pre Constantinople blocks?

**Comment by mattsse** [comment]
> This wont work on pre Constantinople blocks?

do you mean whether pre Constantinople is supported by revm?

see also #2260

**Pull request merged**
