### PR TITLE
chore: add `--encoded-constructor-args` to `verify-contract` as alias for `--constructor-args`

### PR DESCRIPTION
**Pull request by Leechael**
Related: #6453

### CODE REVIEW

**Comment by DaniPopes** [comment]
I dont think the two commands' flags are the same even if they have the same name

**Comment by Leechael** [comment]
So what you purpose for? Considering:

```
forge verify-contract  --constructor-args a b c
```

vs:

```
forge verify-contract --constructor-args a --constructor-args b --constructor-args c
```

Related previous PR: https://github.com/foundry-rs/foundry/pull/622

Why does the behavior of `--constructor-args` differ between `create` and `verify-contract` when submitting a contract with multiple constructor arguments?

**Comment by DaniPopes** [comment]
verify-contract accepts the **already-encoded** arguments in one hex string, while script accepts the human-readable form that you would use anywhere else, so I'd rather change the verify-contract behavior.

**Comment by Leechael** [comment]
> verify-contract accepts the already-encoded arguments in one hex string

Is it better to change the argument name to be more explicit? e.g. `--encoded-contructor-args`

**Comment by Evalir** [comment]
@Leechael changing them would be a breaking change and we'd rather avoid this—but we can add an alias and recommend that instead. wdyt @DaniPopes / @mattsse ?

**Comment by Leechael** [comment]
If we can reach a conclusion, I would like to follow the decision and making that change.

**Review by Evalir — APPROVED** [review]

**Comment by Evalir** [comment]
hey @Leechael—added the change I described and changed the PR name—thanks!

**Pull request merged**
