### PR TITLE
feat(cast): add JWT secret configuration

### PR DESCRIPTION
**Pull request by Rjected**
## Motivation

I was trying to use `cast` as an engine API debug tool for reth, when I realized that ethers-rs does not have easy bearer token generation, and `cast rpc` did not have JWT secret support.

## Solution

Added bearer token generation utilities in https://github.com/gakonst/ethers-rs/pull/2529, which are used in this PR. This PR is dependent on the ethers PR, which is why there are patches.

## TODO
 - [ ] Idea from @gakonst: `cast rpc --jwt <file>`, which takes in a file, replaying the RPC calls in the file line-by-line. Similar to [hurl](https://github.com/Orange-OpenSource/hurl)
 - [x] Clarify `jwt` arg and env variable to make sure the user knows the input should be a hex-encoded **JWT secret**, not a token
   * should there be an option to use a raw token?
   * allow taking a file as input? for example the `jwt.hex` that reth outputs.
 - [x] Remove patches
 - [x] Add usage docs

### CODE REVIEW

**Comment by Rjected** [comment]
> hey @Rjected is this mostly g2g? do you want us to take over?

yeah I plan to do the following today:
* add some usage docs
* change flag name to `jwt-secret`

The `hurl` idea is cool but is probably out of scope for this PR, so once I do the above two this is good to go.
Another thing I probably won't have time for:
* file input

**Comment by Evalir** [comment]
That's alright, this is already pretty great—we can incrementally improve in future prs!

**Comment by Rjected** [comment]
@Evalir this is RFR!

**Review by Evalir — APPROVED** [review]
bro cooked with this one

lgtm! just pushed a smol commit to use `const-hex`, which we already have at the workspace level

**Pull request merged**
