### PR TITLE
fix: use provided gas price in env

### LINKED ISSUE #1143: tx.gasprice always set to 0
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5916d38 2022-03-30T16:31:01.267891+00:00)

### What command(s) is the bug in?

forge test

### Operating System

macOS (M1)

### Describe the bug

tx.gasprice is always set to 0. This is the case even when gas_price parameter in foundry.toml is set to non-zero value.

image

`function testDisplayBaseFeeAndGasPrice() public {
        emit log_uint(block.basefee);
        emit log_uint(tx.gasprice);
    }`

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #1143

## Solution
gas_price will be 0 by default, if it's manually set, then this will now also be set in the `Env` used when executing an transaction

### CODE REVIEW

**Review by onbjerg — CHANGES_REQUESTED** [review]
as discussed elsewhere, I'm pretty sure this breaks quickly. if you set the gas price to something realistic, revm will not execute any transactions since realistic gas price + the super high gas limit we have = not enough funds

this will also be the behaviour when forking, and that's why I originally split the block out to be an "execution block" (the one the executor uses) and an "environment block" (the one the user sees in tests)

We need to do the same for transactions I think

**Review by onbjerg — APPROVED** [review]

**Comment by onbjerg** [comment]
fixed now, will need a separate review

**Review by gakonst — APPROVED** [review]

**Comment by benesjan** [comment]
Hello,
I just fetched the newest forge and it seems that the gas_price parameter in foundry.toml is ignored. Current mainnet gas price is used instead.

My foundry.toml:

`[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/', 'forge-std/=lib/forge-std/src/']
eth-rpc-url = 'RPC_URL'
fork_block_number = 14411926
gas_price = 40000000000`

**Comment by gakonst** [comment]
@mattsse wanna take a look when you have time?^

**Comment by mattsse** [comment]
yeah, we're probably not setting the limit when creating the env for the fork,

@onbjerg I think there was a related issue, but I can't remember

**Pull request merged**
