### PR TITLE
fix(cheats): configure block correctly when forking at transaction

### LINKED ISSUE #3703: erroneous state set when using vm.createFork
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b65d58d 2022-11-17T00:05:05.963677Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

This repo reproduces the issue: https://github.com/sprw121/create-fork-repro. 

Note the network in question is polygon, not ethereum mainnet.

The state set by createFork here is inconsistent with the logs emitted from the transaction prior to it. I have tried to delete the ~/.foundry/cache folder but this did not help. It looks like the transactions aren't getting replayed properly, as the state is consistent with the head of the block.

The transactions in question are:
0x62d76e970d9c1c1cc71b1b7063a74ffe80244de65b855bd5d3ea36889d6f4034 (the one that sets the state)
0xbed0c8c1b9ff8bf0452979d170c52893bb8954f18a904aa5bcbd0f709be050b9 (the one immediately following)

The prior 2 transactions also change the state of the pools (I care more about this state), and the createFork is also inconsistent on those transactions. I choose these two as it's the first transaction after this sequence where the state does not change.

You can see the logs at https://polygonscan.com/tx/0x62d76e970d9c1c1cc71b1b7063a74ffe80244de65b855bd5d3ea36889d6f4034#eventlog, the relevant ones are Topics 0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67.

Unfortunately in this UI, the logs for contracts  0x847b64f9d3a95e977d157866447a5c0a5dfa0ee5 and 0x50eaedb835021e4a108b7290636d62e9765cc6d7 don't decode correctly.

Here are the relevant decoded logs:

```
0x45dda9cb7c25131df268515131f647d726f50608:
Swap (index_topic_1 address sender, index_topic_2 address recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)
sender: 0x49facffbd0c7643eb3ad9cdcb44b95d75d93a978
recipient: 0x200800030b0920400c0100b30bb0fd6bab300050
amount0 :
amount1 :19734536289101492745
sqrtPriceX96 :2158492202962238680259690147925313
liquidity :588702194510526627
tick :204261
```

```
0x847b64f9d3a95e977d157866447a5c0a5dfa0ee5:
Swap (index_topic_1 address sender, index_topic_2 address recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)
sender: 0x49facffbd0c7643eb3ad9cdcb44b95d75d93a978
recipient: 0x49facffbd0c7643eb3ad9cdcb44b95d75d93a978
amount0 :
amount1 :26567416250
sqrtPriceX96 :1076133273204200901840477866344
liquidity :1221531661829
tick :52178
```

```
0x50eaedb835021e4a108b7290636d62e9765cc6d7
Swap (index_topic_1 address sender, index_topic_2 address recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)
sender: 0x49facffbd0c7643eb3ad9cdcb44b95d75d93a978
recipient: 0x49facffbd0c7643eb3ad9cdcb44b95d75d93a978
amount0 : 143802159
amount1 : 
sqrtPriceX96: 29344980527396021373083957193598046
liquidity: 63106417987627857
tick : 256458
```

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #3703

when forking and replaying transactions, we need to fork `tx.block - 1` but configure the `env.block` with `tx.block`.

The `env.block = tx.block` update was incomplete and only included the block number.

cc @sprw121

## Solution
apply the same config updates for `env.block` as in `cast run`

### CODE REVIEW

**Comment by sprw121** [comment]
Does your CI auto update the nightly build on a successful merge? Just wondering what timeframe when this will be available through `foundryup`. If it takes a while I can build locally.

**Comment by mattsse** [comment]
nightly will get released in ~8 hours I believe

**Comment by sprw121** [comment]
Ok np, I'll go ahead and do a local build once this is merged.

**Comment by gakonst** [comment]
release nightly adn you can also `foundryup -b master`

**Review by gakonst — APPROVED** [review]

**Pull request merged**
