### PR TITLE
💄Edit(banner) : chisel - Consistent with foundryup banner

### PR DESCRIPTION
**Pull request by m0ham3dx**
- Color has been extracted from the main forge book repo banner

## Motivation

Add CLI banner similar to #4338 

## Solution

-  Add banner with useful information
- Edit original banner to describing exiting cli method 
- Color extracted from forge main [banner](https://imagecolorpicker.com/color-code/fffc90) 
- Repo owner can change it with RGB codes if something else is desired 

image

### CODE REVIEW

**Comment by mds1** [comment]
Hmm personally I'm not a fan of this unless there is a way to turn it off—I often jump into and out of chisel to test stuff, and this adds a lot of noise to my terminal every time I enter chisel

**Comment by m0ham3dx** [comment]
> Hmm personally I'm not a fan of this unless there is a way to turn it off—I often jump into and out of chisel to test stuff, and this adds a lot of noise to my terminal every time I enter chisel

ok yes that makes sense , jumpin in and out can make the terminal noisy , let me see if I can add a `--silent` maybe

**Comment by mds1** [comment]
Ideally would be a way to configure it globally so you don't need to start with e.g. `chisel --silent` every time, but there's not yet support for `[chisel]` and `[anvil]` config sections.

Tbh I also just question the utility of this in the foundry binaries—in `foundryup` it makes sense because it's not run frequently and it's the installation step, so introductory references to the book / tool are helpful and the art is fun. But `anvil` and `chisel` can be run many times per day, and have help commands built in which are likely more up to date than the book anyway. Def open to other opinions here though—I know @devtooligan likes ascii art so curious to hear what he thinks, maybe I'm being too harsh 😅

**Comment by m0ham3dx** [comment]
> Ideally would be a way to configure it globally so you don't need to start with e.g. `chisel --silent` every time, but there's not yet support for `[chisel]` and `[anvil]` config sections.
> 
> Tbh I also just question the utility of this in the foundry binaries—in `foundryup` it makes sense because it's not run frequently and it's the installation step, so introductory references to the book / tool are helpful and the art is fun. But `anvil` and `chisel` can be run many times per day, and have help commands built in which are likely more up to date than the book anyway. Def open to other opinions here though—I know @devtooligan likes ascii art so curious to hear what he thinks, maybe I'm being too harsh 😅

No , I appreciate the explanation,  I'm sort of getting to know this crab lang, and tinkering  with Foundry which I use all the time, gives me a direction on picking the lang up, ur also right technically it doesn't offer any utility, it's just cosmetic changes

**Comment by gakonst** [comment]
same reason as https://github.com/foundry-rs/foundry/pull/4338 ^^ thank you

**Pull request closed without merging**
