### PR TITLE
fix(forge): Don't ignore config.toml when running invariant tests for coverage

### LINKED ISSUE #6565: Forge coverage ignores config.toml when running invariant tests
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0ae39ea 2023-12-11T00:27:32.487222000Z)

### What command(s) is the bug in?

forge coverage

### Operating System

None

### Describe the bug

`forge coverage` ignores the `config.toml` file for invariant tests. 

Invariant testing in coverage mode thus uses the default 256 runs which is small, making coverage for big invariant tests (eg. using handlers) noisy/useless. This is not the case for regular (non-invariant) tests. Such a feature would bring us closer to #4007.

### PR DESCRIPTION
**Pull request by 0xmp**
`forge coverage` ignores the `config.toml` file for invariant tests. 

Invariant testing in coverage mode thus uses the default 256 runs which is small, making coverage for big invariant tests noisy/useless. This is not the case for regular (non-invariant) tests. 

## Motivation

This would bring us closer to having invariant tests as contributing fully to coverage (#4007).
Fixes #6565.

## Solution

The coverage runner now takes the correct `config` given when running tests. 

This is my first time writing Rust ever, so do feel free to ignore/rewrite completely.

### CODE REVIEW

**Review by Evalir — CHANGES_REQUESTED** [review]
Hey! thanks for this!

So, I don't see an issue with the code itself—however, invariants right now don't contribute to coverage at all, so this would only really make coverage slower for users in the meanwhile :s. I don't think we wanna get this in before having a proper plan on how to revamp coverage and make invariant testing work with it.

**Comment by 0xmp** [comment]
> invariants right now don't contribute to coverage at all

That's weird, I'm running an invariant test and getting some coverage info following this [Twitter thread ](https://x.com/DevDacian/status/1732645103867773236) by using
```
forge coverage --report lcov --report-file test/myfile.lcov --match-contract myInvariantTest
genhtml ./test/myfile.lcov -o output
```
and then checking the output html. 

The coverage does seem to increase on my test when I increase the number of runs. Maybe I'm getting "fooled by randomness" and it's just a question of seed or something?

**Comment by Evalir** [comment]
Interesting thread—thanks for sharing. However we do not officially support coverage for invariant tests 😅 so while this might actually be working I'm really wary about this affecting CI to people. Wdyt @mds1 ?

**Comment by mds1** [comment]
Not sure if this is a common opinion, but:
1. You should have good coverage even with 1 fuzz run and no invariant runs. This gives a stricter measure of your test coverage by ensuring you aren't relying on fuzzing/randomness.
2. It is still useful to be able to see how much coverage many fuzz runs or many invariant runs provided, to gauge the effectiveness of your fuzz and invariant tests.

As a result, my preference is two coverage modes:
1. One mode ignores config settings, sets fuzz runs to 1, ignores invariant tests.
2. Second mode respects config settings,

I think people's expectation is that (2) is the default, and perhaps (1) becomes something like `forge coverage --strict` 

I'm not sure where this PR fits into that potential design/UX

**Review by Evalir — APPROVED** [review]
let's go with this for now—we'll respect the invariant settings, and we can add the `--strict` mode later.

**Pull request merged**
