### PR TITLE
ci(workflows): refactor and improve build perf

### PR DESCRIPTION
**Pull request by sambacha**
## Motivation

- CI build time improvement. 
- Leverage new features to speed up time drastically.
- Additionally, the existing actions-rs are not maintained, they are over two years old with no updates and actually have genuine security issues.

#### rust nightly (side note)

`CARGO_UNSTABLE_SPARSE_REGISTRY` is only available `nightly` I will time the differences 

> [The performance improvement for clients should be especially noticeable in CI environments, particularly if no local cache of the index exists.](https://blog.rust-lang.org/2022/06/22/sparse-registry-testing.html#details:~:text=The%20performance%20improvement%20for%20clients%20should%20be%20especially%20noticeable%20in%20CI%20environments%2C%20particularly%20if%20no%20local%20cache%20of%20the%20index%20exists.)

> [sparse index rfc ref](https://rust-lang.github.io/rfcs/2789-sparse-index.html)

## Solution

All these GitHub Actions are `drop in` replacements, meaning they take the same arguments/params. 
```diff
-        uses: actions-rs/toolchain@v1
+        uses: dtolnay/rust-toolchain@v1
```

### Use fixed shared-key across workflows to persist cache across CI 

```diff
-       - uses: Swatinem/rust-cache@v1
+      - uses: Swatinem/rust-cache@v2
+       with:
+        shared-key: cache-ci-
+          cache-on-failure: true
```

## Alternative for caching 

CI could do this as an alternative:

```yaml
- uses: actions/cache@v3
  with:
    path: |
      ~/.cargo/bin/
      ~/.cargo/registry/index/
      ~/.cargo/registry/cache/
      ~/.cargo/git/db/
      target/
    key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
```

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
switching to dtolnay/rust-toolchain@v1 makes sense imp

not sure about this one though

https://github.com/ClementTsang/cargo-action

> A simple GitHub Action to invoke cargo/cross and commands. Inputs and usage inspired by action-rs' [cargo action](https://github.com/actions-rs/cargo), with dtolnay's [rust-toolchain](https://github.com/dtolnay/rust-toolchain) as reference.

> Written for use in personal projects, though feel free to use it on your own. Big fat disclaimer though that it may or may not work for your use case - if that's the case, I'm open to issue reports and PRs.

what benefits does this have?

is there a reference project that's already using this combination?

wdyt @onbjerg ?

**Comment by onbjerg** [comment]
Seems ok wrt the toolchain action, the other one I don't really see a benefit since both of them are just wrappers around calling `cargo`, there isn't really a lot to maintain and it is working fine currently.

Wrt cache keys I'd be extra careful that we don't accidentally poison the cache of other jobs that would then lead to errors

**Comment by sambacha** [comment]
> Seems ok wrt the toolchain action, the other one I don't really see a benefit since both of them are just wrappers around calling `cargo`, there isn't really a lot to maintain and it is working fine currently.
> 
> Wrt cache keys I'd be extra careful that we don't accidentally poison the cache of other jobs that would then lead to errors

yup, Ill make some test for this cache and make the relevant changes to align with you and @mattsse comments

**Comment by gakonst** [comment]
it's not obvious to me that these changes improve perf from looking at the times above, so erring towards using the standard toolchain is better imo.

**Comment by sambacha** [comment]
> it's not obvious to me that these changes improve perf from looking at the times above, so erring towards using the standard toolchain is better imo.

There is no standard toolchain: they are unmaintained.

**Pull request closed without merging**
