### PR TITLE
Checksum address output in log_address event and broadcast files

### PR DESCRIPTION
**Pull request by tgfukuda**
## Motivation

https://github.com/foundry-rs/foundry/issues/2975
## Solution

Change logged address (input, output, ...) to checksummed with `ethers::core::utils::to_checksum`.
It converts `Address` to `String`, so including fix for some formatting.

still not fixing `broadcast` json file, WIP

This is my first PR, so I'm sorry if it's in a wrong manner.

### CODE REVIEW

**Review by gakonst — COMMENTED** [review]
this should be fine, is it OK that we're skipping the chain id? guess so?

**Comment by tgfukuda** [comment]
> this should be fine, is it OK that we're skipping the chain id? guess so?

ethers-rs computes it as [EIP-1191](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1191.md) if chainId is specified and as [EIP-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) if not.
https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/utils/mod.rs#L279-L298
The Checksummed address as EIP-1191 is possible but it may require many change because some of the contexts like https://github.com/foundry-rs/foundry/pull/3108/files#diff-2a68e14bf95d2e3c7c7c72b92741c10dc2ea9027388a899a65a9a73b4152b80fR504 doesn't have chainId.
I like for PR to be as small as possible, so I think it is enough to checksum address in an EIP-55 style when it comes to this PR.
I don't know which one is better and want comments for it.

**Review by gakonst — COMMENTED** [review]
this is coming along nicely - maybe if we could add a test to ensure we don't break it later?

**Comment by tgfukuda** [comment]
@gakonst 
Thank you for your review.

I added the test for `format_token` method.

Additionally, addresses in a broadcast log of `forge script` becomes checksummed except for `TypedTransaction` of `TransactionMetadata`.
`TypedTransaction` is enum and the changes may be too large to review, I think. So it is not enough to the goal of this PR.

Log file generated by `forge script` is deeply depends on `serde` and `ethers-rs` implementation. To checksum every address of logs, need to modify the `Serialize` implementation of every struct related to it.

**Review by gakonst — APPROVED** [review]
sweet

**Comment by gakonst** [comment]
thank you fo rthe contribution @tgfukuda! very helpful.

**Pull request merged**
