### PR TITLE
feat(cast): let cast interface look for abi file in the out folder

### PR DESCRIPTION
**Pull request by DrakeEvans**
## Motivation
`cast interface` command needs a full file path to the abi which is annoying to look up.  Other commands just need the contract name

## Solution
If a name is passed instead of an address/abi_path we look for it in the out folder (which is loaded from the config file)

## Help Needed
I'm not sure where the proper location for the `find_file_in_folders` function is.  I would appreciate help getting this PR over the line.  As of now it is missing tests

### CODE REVIEW

**Comment by zerosnacks** [comment]
Thanks for the PR! Supportive of the feature. Would be great to get this ready for review / merged - do you see any blockers @DrakeEvans? The proper location of `find_file_in_folders` can be handled in the review

**Comment by DrakeEvans** [comment]
I dont think I have anything else Id do to get ready for review.  Unfortunately I dont have the bandwidth to take this over the line but happy to answer any questions via tg etc.

**Comment by zerosnacks** [comment]
> I dont think I have anything else Id do to get ready for review. Unfortunately I dont have the bandwidth to take this over the line but happy to answer any questions via tg etc.

No problem! Thanks, I'll pick it up from here

**Comment by zerosnacks** [comment]
Decided to turn this into a ticket here https://github.com/foundry-rs/foundry/issues/8580 given there have been improvements to the way interactions with artifacts occur / deals with certain edge cases

**Pull request closed without merging**
