### PR TITLE
feat(cheatcodes): expectRevert with specific reverter address

### LINKED ISSUE #5299: Add `vm.expectRevert` overloads that take an address arg, to distinguish between error selectors that are identical but in different contracts.
### Component

Forge

### Describe the feature you would like

As described in this [issue](https://github.com/foundry-rs/book/issues/945) in the foundry book:

If you have two contracts with identical custom errors:

```
contract A {
  error NotValid();
  // contract A specific code here...
}
contract B {
  error NotValid();
  // contract A specific code here...
}
```

then: `A.NotValid.selector == B.NotValid.selector`.

If you have a test that checks for a revert from `A.NotValid.selector` and the error is thrown by `B` in the test, the test will still pass as the error selector comparisons will pass. 

By including the address of the contract in `expectRevert`, you can specify with greater granularity which error you wish to test for. 

As it stands, it is not practical to refactor common errors into a shared interface as there is no way of checking the source of a revert. 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
Closes #5299 
Closes https://github.com/foundry-rs/book/issues/945
https://github.com/foundry-rs/foundry/issues/5299#issuecomment-1623838745

## Solution

- added `expectRevert` cheatcodes with reverter (expects an error on next call from the given address)
```Solidity
function expectRevert(bytes calldata revertData, address reverter) external;
function expectRevert(bytes4 revertData, address reverter) external;
function expectRevert(address reverter) external;
function expectPartialRevert(address reverter) external;
```
- when reverter arg passed then process expected revert for next call, at any depth. If address of contract that reverted the call (call's target address) is different than the expected reverter, then fail test with `Reason: Reverter != expected reverter` reason.
- code refactoring: pass `ExpectedRevert` directly to `handle_expect_revert` 
- added tests

### CODE REVIEW

**Comment by mds1** [comment]
Continuing from #4762:

>  I thought, like other `expect*` cheats, that expectRevert wants the revert to happen on the next call?
> >
> > That still holds true but it should be read as `expectRevert(reverterAddress) wants the revert to happen on the next call to reverterAddress`

Personally I am not a fan of this behavior, and I think `expectRevert(reverterAddress)` should expect the revert on the next call. The main reason here is this is consistent with how `expectEmit(emitter)` behaves—it always applies to the next call, and consistent is important for UX.

Additionally, I think "the next call to reverterAddress" is not always obvious, because calls to a different top level address may end up making subcalls to reverterAddress

**Comment by grandizzy** [comment]
> 
> Personally I am not a fan of this behavior, and I think `expectRevert(reverterAddress)` should expect the revert on the next call. The main reason here is this is consistent with how `expectEmit(emitter)` behaves—it always applies to the next call, and consistent is important for UX.
> 
Agree, consistency makes sense. However not clear how the bubbling revert described in https://github.com/foundry-rs/foundry/issues/5299#issuecomment-1623838745 could be achieved if we expect the revert on the next call, I could be missing something

**Comment by mds1** [comment]
> So it might be better to just consider all 3 of those bullets a success, i.e. we're expecting that A throws that error anywhere in the call stack, and does not have to be the originator

I think this is probably the simplest solution, just ignore whether or not it bubbled up at all, and as long as `reverterAddress` reverts with the expected error it's a success

**Comment by grandizzy** [comment]
> > So it might be better to just consider all 3 of those bullets a success, i.e. we're expecting that A throws that error anywhere in the call stack, and does not have to be the originator
> 
> I think this is probably the simplest solution, just ignore whether or not it bubbled up at all, and as long as `reverterAddress` reverts with the expected error it's a success

:+1:  will do so then

**Review by mattsse — APPROVED** [review]
lgtm, pending @klkvr

**Comment by klkvr** [comment]
is this basically `expectRevert` + assert the target of the next call?

**Comment by grandizzy** [comment]
> is this basically `expectRevert` + assert the target of the next call is `reverterAddress`?

yeah, see #5299 for identical selectors but 

> is this basically `expectRevert` + assert the target of the next call is `reverterAddress`?

yeah, pls check #5299 for identical selectors but in different contracts

**Comment by grandizzy** [comment]
@klkvr ptal and lmk if any things you'd like to be changed before merging. Thank you!

**Comment by klkvr** [comment]
the approach LGTM, though I don't think we're actually resolving https://github.com/foundry-rs/foundry/issues/5299 usecase here? eg there's no way to assert B triggering the revert without calling it directly.

IMO having a way to assert revert of the given contract at any subcall of the next call might be useful. such reverts might not even end up bubbled up, and this should still be fine — try-catch blocks are not used that much, and it's arguably useful to have a way to test them being entered as well.

I also think that this would be consistent, because `expectEmit(address emitter)` catches emits of any depth as well

**Comment by grandizzy** [comment]
> the approach LGTM, though I don't think we're actually resolving #5299 usecase here? eg there's no way to assert B reverting without calling it directly.
> 
> IMO having a way to assert revert of the given contract at any subcall of the next call might be useful. such reverts might not even end up bubbled up, and this should still be fine — try-catch blocks are not used that much, and it's arguably useful to have a way to test them being entered as well.
> 
> I also think that this would be consistent, because `expectEmit(address emitter)` catches emits of any depth as well

@mds1 would you concur with @klkvr comment? Imo makes sense but needs to be able to check subcalls of next call. So kind of a mix of how was implemented initially but only for the next call

**Comment by mds1** [comment]
> > is this basically `expectRevert` + assert the target of the next call is `reverterAddress`?
> 
> yeah, pls check #5299 for identical selectors but in different contracts 

Oh, I thought this was:  `expectRevert` + assert the revert came from `reverterAddress`, regardless of the target of the next call? I agree with @klkvr and think that is actually what we want to resolve #5299

**Comment by grandizzy** [comment]
> 
> IMO having a way to assert revert of the given contract at any subcall of the next call might be useful. such reverts might not even end up bubbled up, and this should still be fine — try-catch blocks are not used that much, and it's arguably useful to have a way to test them being entered as well.
> 
> I also think that this would be consistent, because `expectEmit(address emitter)` catches emits of any depth as well

@klkvr please recheck. thank you!

**Review by klkvr — APPROVED** [review]
LGTM

**Pull request merged**
