### PR TITLE
feat(forge): add labels for precompile addresses

### LINKED ISSUE #7530: Automatically label known contract addresses in traces
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7922fd5 2024-02-05T00:19:20.258041000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

This issue is a follow-up issue of [this one](https://github.com/foundry-rs/foundry/issues/639), but since that one is old, I'd like to issue a new one.

It seems `0x0000000000000000000000000000000000000001` is a contract automatically created by foundry, but not labeled in traces:

```
[0] 0x0000000000000000000000000000000000000001::fallback{value: 1000000000000000000}()
```

It can be reproduced [here](https://github.com/zhiqiangxu/es-op-batchinbox/tree/foundry_label) by running `forge test --mp test/BatchInbox.t.sol -vvv`

### PR DESCRIPTION
**Pull request by grandizzy**
## Motivation
Closes #7530 

Not all precompiles are labeled, this PR add missing labels

## Solution

- added precompile addresses in constants
- in precompile decode match on address
- add trace labels to all precompile addresses

### CODE REVIEW

**Review by DaniPopes — COMMENTED** [review]
Precompile calls should already be labeled with `PRECOMPILES::name(...)` already. I don't really know about this.

**Comment by grandizzy** [comment]
> Precompile calls should already be labeled with `PRECOMPILES::name(...)` already. I don't really know about this.

That's right, thing is that labels for precompiles are not displayed along all traces but only when precompile is decoded, so for example in #7530 for following test setup
```Solidity
        address target = address(1);
        batchInbox.deposit{value: 1 ether}(target);
        assertEq(batchInbox.balances(target), 1 ether);
```
traces are shown as
```bash
    ├─ [22647] BatchInbox::deposit{value: 1000000000000000000}(0x0000000000000000000000000000000000000001)
    │   └─ ← [Stop] 
    ├─ [519] BatchInbox::balances(0x0000000000000000000000000000000000000001) [staticcall]
    │   └─ ← [Return] 1000000000000000000 [1e18]
```

as with current PR the `ECRecover` label is attached making clear that's a precompile:

```bash
    ├─ [22647] BatchInbox::deposit{value: 1000000000000000000}(ECRecover: [0x0000000000000000000000000000000000000001])
    │   └─ ← [Stop] 
    ├─ [519] BatchInbox::balances(ECRecover: [0x0000000000000000000000000000000000000001]) [staticcall]
    │   └─ ← [Return] 1000000000000000000 [1e18]
```

IMO would be a nice addition but nothing critical so we could drop this one if you think it doesn't worth @DaniPopes

**Review by mattsse — APPROVED** [review]
pending @DaniPopes nits then this is g2m

**Comment by grandizzy** [comment]
closing in favour of #8367

**Pull request closed without merging**
