### PR TITLE
feat(forge-bind): `add_derives` for serde in contract bindings

### LINKED ISSUE #5835: forge feat: add `serde::Serialize` and `serde::Deserialize` traits upon abigen
### Component

Forge

### Describe the feature you would like

When generating contract bindings via `forge bind`, it would be excellent if the structs/enums created can implement `serde::{Serialize, Deserialize}` so that users may ultimately be able to output data collected from such calls/events/errors into other formats such as CSV or databases. 

Note that I also linked an issue in [`ethers-rs` here](https://github.com/gakonst/ethers-rs/issues/2599). However, I think this is not necessary as I have a quick addition to Forge that solves the problem and can be made more configurable.

See here:
https://github.com/foundry-rs/foundry/blob/ae89c92ee32b38d525429fe9c216a0919bc7bed1/crates/forge/bin/cmd/bind.rs#L122-L145

If we replace the `.map` on line 134 as such:

```rust
.map(|x| {
                Abigen::from_file(x)?
                    .add_derive("serde::Serialize")?
                    .add_derive("serde::Deserialize")
            })
```
then we find the additional traits are derived on the relevant structs/enums.

I am happy to implement these changes in a PR. Please see the additional context for more configurability.

### Additional context

The feature could also include a flag in a few ways, if we want more configuration. E.g.,
- `forge bind --with-serde` adds the addition to the map as shown, and otherwise leaves it as is.
- `forge bind --with-derive "serde::Serialize" --with-derive "serde::Deserialize"` adds each derive one by one. Could also allow for multiple strings as:
- `forge bind --with-derives ["serde::Serialize", "serde::Deserialize"]`

### PR DESCRIPTION
**Pull request by Autoparallel**
## Motivation

The change was made to close #5835 which would allow users to get more functionality out of enums/structs in contract bindings, e.g., parse contract events from a chain into a file format such as CSV.

## Solution

This is a basic solution where we just add in the `serde::Serialize` and `serde:Deserialize` traits via the `add_derives` method on `Abigen`. This does not give the end user any option in deriving these traits and, perhaps they may not want them. 

I am happy to provide flags as such described in #5835. Please let me know what you prefer.

### CODE REVIEW

**Review by mattsse — CHANGES_REQUESTED** [review]
this looks fine, however, I think we're missing support for configuring additional Cargo.toml dependencies in Abigen.

ideally serde would be added to the generated Cargo.toml as well.

currently we're only setting ethers:

https://github.com/gakonst/ethers-rs/blob/c702e6cdece63f3c47f3476c626024c11f4b8cec/ethers-contract/ethers-contract-abigen/src/multi.rs#L612-L612

so we need a way to also configure additional deps.

I think this should go here:

https://github.com/gakonst/ethers-rs/blob/c702e6cdece63f3c47f3476c626024c11f4b8cec/ethers-contract/ethers-contract-abigen/src/multi.rs#L367-L368

something like `dependencies: Vec<String>`

I don't want to add this as an additional arg to `write_to_crate` since this would break.

**Comment by Autoparallel** [comment]
Okay got it. Let me work on this.

**Comment by Autoparallel** [comment]
Would it instead be a simpler change to do this:

https://github.com/gakonst/ethers-rs/blob/c702e6cdece63f3c47f3476c626024c11f4b8cec/ethers-contract/src/lib.rs#L20-L30

In this `lib.rs`, just add
```rust 
pub use serde::{Serialize, Deserialize}
```

And then replace the 
```rust
add_derive("serde::Serialize")
```
with 
```rust
add_derive("::ethers::contract::Serialize")
```

and of course the respective change for `Deserialize`. This is pretty minimal change required.

**Comment by mattsse** [comment]
another fix would be to append the serde dependency manually in forge bind, but ideal solution would be support in abigen

**Comment by Autoparallel** [comment]
I was working on this for a while today inside `ethers-rs`. I am struggling to see a nice way to do it that doesn't involve more sweeping changes.

From what I can gather, there is a process like:
```
Abigen -> MultiAbigen -> MultiExpansion -> MultiExpansionResult -> MultiBindings -> MultiBindingsInner
```

where finally the `Cargo.toml` is written. 

I considered adding a:
```rust
add_dependency()
```
for `Abigen` as this is where we would also be adding a derive as well. However, carrying this dependency throughout as a `Vec<String>` in each one of these structs seemed to lead to larger changes than I expected. I think this is doable, but does this seem like the approach we want?

Do you have more thoughts on this? I want to do it the right way here!

**Comment by Autoparallel** [comment]
I made a fix here that pushes the relevant dependency into the bindings when generated via a crate. It will have to come after the change in `ethers-rs` of course!

**Comment by gakonst** [comment]
This has been fixed in Ethers

**Review by mattsse — APPROVED** [review]
ty for this!

sorry for the delay

**Pull request merged**
